### ISSUE TITLE
Stop Limit Question

### ISSUE THREAD

**Issue by EdFarrell** [valhalla/valhalla#1058]
I'm considering using Valhalla for basic routing and optimized. Both have to be able to handle 250-400 stops on a route (within ~10 sq mi area), with good performance. Mainly interested in pedestrian mode, but bicycle and auto are sometimes needed.

My question is, can does Valhalla meet these requirements? I'd rather know now before I dive in.

**Comment by dnesbitt61** [comment]
You should be able to run regular routes with that many stops on a local instance of Valhalla by changing the service limits in the configuration file. They would be slower with that many stops though, as each is a separate route path computation.

Optimized routes (where the order that locations are visited is optimized) likely would not work on this many locations without some tuning or a computer with lots of memory. We have run 100 stop source to target matrices (the input stage to optimized routes) but above that memory use starts to be a concern. There are a couple of potential optimizations but we have not tested to these limits to verify.

**Comment by EdFarrell** [comment]
Thanks for the quick response. For the regular routes, how much slower would it be with that many routes? Would this increase to seconds? minutes? (I realize you can't be very specific, ballpark is fine). For the optimized routes, how much memory would you anticipate?

**Comment by dnesbitt61** [comment]
For regular routes the response time should only marginally increase for each additional location in the input. As long as the locations are close together (like yours are) the response should still be on the order of seconds (at most) for that number of locations. I cannot say on the optimized route question - we have had some users try larger location counts within matrices even on larger machines in AWS and have run into issues when the location count gets above 100 or maybe a little higher. This needs further testing and evaluation - we just have not had time to look into this as generally any large matrix problem can be broken into smaller problems. Just takes a little code to break up the problem into separate source and target lists below the server limit, and then code to combine the results into the larger problem later. This is generally how we would tell someone who wants larger matrix requests. That does not work for Optimized Route though since we do not have an interface to do just the optimization step. Would be a good addition to Valhalla, it is just not something we have considered.

**Comment by EdFarrell** [comment]
Thanks for the thorough response. It sounds like breaking the optimized route of 300 into smaller "legs" may be a possible solution. For example, 6 legs of 50 stops, each leg having a start and end that is user defined (through web interface). Although this may not result in the same solution as running the full 300, it should get close, or at least acceptably close.

**Comment by dnesbitt61** [comment]
closing this issue. feel free to open a new issue or elaborate further if this is still a problem
