### ISSUE TITLE
Slow munmap() syscall on macOS leads to very slow valhalla_build_tiles

### ISSUE THREAD

**Issue by danpat** [valhalla/valhalla#1192]
When trying to build tiles on a non-trivial dataset on macOS (I'm testing this with `us-west-latest.osm.pbf` from Geofabrik), `valhalla_build_tiles` gets really slow right after it logs this message:

```
2018/04/10 00:12:47.524104 [INFO] Creating graph edges from ways...
```

I left this running overnight on a new Macbook Pro (i7-7567U CPU @ 3.50 GHz, 16GB RAM, 500GB SSD).  Wasn't finished when I woke up.

I did some debugging, it looks like the culprit is the `munmap()` syscall on OSX.  Here's the output of a short profiler run:

<img width="750" alt="screen shot 2018-04-09 at 2 35 09 pm" src="https://user-images.githubusercontent.com/1892250/38529657-1cc5067c-3c1b-11e8-817e-8e92b9392d26.png">

Results look similar on larger datasets.

From what I can tell, the problem is being triggered here:

https://github.com/valhalla/valhalla/blob/e9aeabc745a562a230ba417c3a736dbd639b6d4e/src/mjolnir/graphbuilder.cc#L194

Ultimately, almost any function that touches the `nodes` object here triggers a `flush()` call, which in turn triggers the `munmap()` syscall.  A whole pile of the functions in `sequence.h` call `flush()` before they do anything, so operations I'd expect to not cause a flush *do*.

The example above is in a pretty hot loop too - this gets called for pretty much every intersection node in the graph, which is a good portion of them.  It seems like the use of `flush()` everywhere is defeating the purpose of the `write_buffer` in `sequence.h`.

`munmap()` performance on Linux is significantly better than on macOS, so I suspect this problem has been around for a while, but nobody noticed.  (Un?)fortunately, we're not all on Linux, and this problem makes `valhalla_build_tiles` unusable on large datasets for me.

**Comment by kevinkreiser** [comment]
Flush is all over the place because the iterator interface would be broken without the elements in a contiguous address space. The only time flush does something is if stuff is in the write buffer though. There are basically two patterns with sequence: write stuff, read stuff. Mixing the two hasnt been optimized and shoild only occur in maybe two places in the code.

We have had many people over the years building tilesets with Valhalla on mac so this is pretty surprising to me. It seems pretty unlikely that they were all trivially small but i suppose anything is possible!

I guess the real fix here is to map a bunch of space up front based on stats we know about appx number of graph edges and nodes given number of osm ways and nodes and modify sequence to work that way. Basically implement std::vector::reserve for sequence.

In the meantime, what happens if you use docker to build larger tilesets? Some sort of mem map inception?

**Comment by kevinkreiser** [comment]
When i wrote it i should have forces it to be either read or write mode but left it up to the user how to (ab)use it. In this instance it seams that all its doing is getting the last node and setting a property on it. We could just implement sequence::last and give back a reference to either the influshed last element or the flushed element from the mmap pointer. That would be a quick easy way to work around it. Basically dont use the iterator interface

**Comment by kevinkreiser** [comment]
@danpat i guess so! i had always thought of iterators as a standardized container interface for iteration but i guess its true that sequence doesnt have to provide a `random_access` iterator (although that is what i clearly had in my head). thanks for noticing the simple flexible way to fix this!
