### ISSUE TITLE
Data processing - remove driveways?

### ISSUE THREAD

**Issue by gknisely** [valhalla/valhalla#1249]
Should we remove driveways from the Valhalla tiles to reduce the size the of tiles.

- [x] Review what OSRM does with driveways.  
- [x] Run RAD tests for NA and EU.

**Comment by kevinkreiser** [comment]
does `driveway` == `highway:service` && `access:private`?

If so I would urge us to consider keeping some of them in certain circumstances:

1. if the driveway has a name: this makes it searchable in some fashion and therefore i would argue it should be in the route graph 
2. if the driveway is sufficiently long: if the route input lat,lon is an address parcel centriod it could be at the end of the "driveway". this can be common in rural areas. the closest point on the the non-driveway route graph could be far away from where the driveway connects to that road. this has the potential for confusion on the drivers part when they reach the destination (either its passed the driveway or is reached before the driveway). the shorter the driveway the less likely you'll get a snapped point far away from the mouth of the driveway or that the user can't see their actual destination.

**Comment by gknisely** [comment]
@kevinkreiser no it actually has highway=service and service=driveway and access=private.  
I agree with number 1.  For number 2, it would be nice if the geocoder had routable points for these cases.

**Comment by kevinkreiser** [comment]
Routable points is a good thing for sure but I think Valhalla should remain geocoder agnostic, meaning not assume what type of geocoder input it's getting. If it's configuarable then then it doesn't matter each person can somewhat right forntheir intended use.

Also I would image an implementation of routable lat lon for a poi would be more likely to be there on non rural pois and I'm specifically worried about the out of the way places since they are near and dear to my heart :o)

**Comment by coxchapman** [comment]
@kevinkreiser @gknisely that has been the design intent for the routable points effort -- to ensure the "contract" between the routing engine and the geocoder remains the same. At the end of the day they'll return a lon/lat pair; it's up to the geocoder (or requester) whether that coordinate comes from the centroid or the routable point, if available.

**Comment by dnesbitt61** [comment]
1) removing driveways is a configurable option in Valhalla tile building. It is currently set to continue to include driveways by default. SO anyone who wants to continue to build data with driveways can. 2) the number of driveways is significant - they bloat tiles, lower performance, and often do not have use in routing. There are many cases where a route that takes a driveway would be a bad route. I also question how many driveways in OSM actually exist today (at least in many parts of the US). Many of the long driveways in rural areas are farm field access roads or tree covered remnants of driveways that no longer exist.

**Comment by kevinkreiser** [comment]
I might be misunderstanding here but i think I'm arguing for loose coupling, which I think means really no contract (assumptions) between a geocoder and the routing engine. Concretely a geocoder could provide a route ll for a poi and you can send that to Valhalla but Valhalla shouldn't ditch all driveways because we know of a geocoder that will handle the problem upstream.

If the person or group running valhalla knows that the geocoder they will use with Valhalla removes driveways then we should provide data building options to allow a tighter coupling though.

I just think that we shouldnt assume what geocoder will be used with a Valhalla service or what overlap in data a geocoder and router will have. We can give options for the people deploying this to fit thier use cases though.

I hope this makes sense and apologies if it doesnt!

**Comment by kevinkreiser** [comment]
@dnesbitt61 I agree that most of them are bloat as you say. I just thought that instead of nuking them all we might be able to keep the 2% of them that are useful? I knew that we had the config option I just thought instead of on or off maybe there could be some selection criteria. Although the nuance might be more annoying to explain I hate to think of a worsened experience to save a couple hundred bytes.

Btw what was the tile size and performance impact? Did we measure those while doing RAD or something?

**Comment by gknisely** [comment]
@dnesbitt61 didn't you have numbers on that already?

**Comment by dnesbitt61** [comment]
Removing ALL driveways (highway=service, service=driveway) reduced data size by 10%. I do not know what the numbers are if you add private. Performance impact is primarily on pedestrian and bicycle routes (did not compare). This issue has nothing to do with geocoding - the impetus is to remove a large number of edges which are mostly not usable for routing and can create bad experiences. It is better to get to a real road near an address than to route to a precise point ending by taking the wrong driveway.

**Comment by kevinkreiser** [comment]
I was just saying if a geocoder or a person puts the input location on the end of a long "driveway" but we remove it from the routing graph then the router will snap the point possibly confusingly far away from where ever the driveway is.  Maybe it won't ever happen but it could happen.
