### ISSUE TITLE
cmake cleanup

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#1323]
doing `make check` shows a couple of regressions that are new since the change to cmake.

- [x] the first one is this:

    /home/kkreiser/sandbox/valhalla/valhalla/valhalla/valhalla.h:9:0: warning: "HAVE_HTTP" redefined
     #define HAVE_HTTP
     ^

- [x] the second is at the end of the tests:

    === Failed 0 tests ===
    [ 86%] Built target run-astar
    CMakeFiles/Makefile2:278: die Regel für Ziel „CMakeFiles/check.dir/rule“ scheiterte
    make[1]: *** [CMakeFiles/check.dir/rule] Fehler 2
    Makefile:197: die Regel für Ziel „check“ scheiterte
    make: *** [check] Fehler 2

- [x] finally, the test output is sent to the screen instead of just giving a pass/fail for each test (for small projects this might be ok but for larger ones like valhalla its just too much information to be useful). instead i think we should prefer a pass/fail for each test and if one of them fails we can run that test in isolation.

**Comment by oxidase** [comment]
@kevinkreiser 
* you have to remove generated `valhalla/valhalla.h`. The new location of the generated file is `build/src/valhalla/valhalla.h`

* it can be due to a missing dependency `add_dependencies(run-matrix utrecht_tiles)`, I will prepare a PR to fix it.

* output is produced by [`tee`](https://github.com/valhalla/valhalla/blob/b860d71c2581ff9a5dd7af97b03e599ec7ba4274/CMakeLists.txt#L226) and can be changed to ` >& ${CMAKE_CURRENT_BINARY_DIR}/unit_tests/${test}.log && echo "PASS ${test} || (cat ${CMAKE_CURRENT_BINARY_DIR}/unit_tests/${test}.log ) ; exit 2)` or similar

**Comment by kevinkreiser** [comment]
I swore I removed that generated file! I'll check again, thanks!

**Comment by kevinkreiser** [comment]
you were totally right about not removing `valhalla/valhalla.h`. i checked my bash history and saw that i removed the other generated ones in there `config.h` and the like but missed that one. sorry for that!

**Comment by oxidase** [comment]
Closing as fixed by  #1326
