### ISSUE TITLE
Recommended approach for precise linear references

### ISSUE THREAD

**Issue by chrisfosterelli** [valhalla/valhalla#1374]
The benefits of the OSMLR tiles is that they are stable and provide a base for doing linear referencing against. I can see in the code how this would be made to work in buckets on each OSMLR segment for traffic, but how can precise or ranged linear references be done?

I want to identify that a particular feature occurs at `x` distance along an OSMLR segment, rather than identifying only that a feature occurs on an OSMLR segment. I believe I can do this from a given edge or lat/lon by traversing the graph from the current edge and taking note of the associated OSMLR ids. Once I have the whole OSMLR ID mapped, I could find the "start" of it and calculate distance along it using the edges' shape data to know if I'm close to `x` along it. Is there a more effective way?

How do I go about creating these mappings? I can see the Python API allows me to export matched segments for a given query, but it doesn't seem to include info about the portions of the segment so I don't see how to calculate the distance along each segment from that API.

**Comment by chrisfosterelli** [comment]
Thanks for the reply @dnesbitt61! To be concrete, I have a dataset of roughly-street-centerline polylines, each with an attribute value, that I want to represent in a stable way. Then, when I have live GPS traces, I can map match those in Valhalla, find the corresponding OSMLR segment, calculate the length along it, and find the related attribute. My approach uses dynamic segmentation.

The segmentation table looks something like this:

OSMLR ID | Start | End | Value
------------ | ------------- | ------------- | -------------
1231209821 | 10 | 390 | green_road
1231209821 | 390 | 470 | red_road
1230812309 | 0 | 380 | red_road

The parts that are not clear to me are:
1. The best way to calculate distance along a segment from a reference to an edge. I can get the associated OSMLR ID from the edge after running the traffic association tool, but it's not a complete reference so it is unclear how to get the distance in terms of the segment.
2. How to go from the polyline data to the segmentation table. I roughly have been following the opentraffic reporter implementation using the Valhalla Python API, but it also only returns OSMLR IDs and no info about what section of the segment it matches against.

Does that better describe my problem? I can elaborate more if it'd be helpful. 

If I understand your suggestion, you think I could use the OSMLR ID's from the edge and from the Python API to look up the corresponding segment in the GeoJSON dataset and then use the full geometry there to calculate the distance along the segment for the corresponding lat/lon point? I think that might work. Is the GeoJSON geometry the higher resolution OSM geometry or is it an interpolation from the LRPs?

**Comment by chrisfosterelli** [comment]
Also, since you mention not working on OSMLR much... is this barking up the wrong tree entirely? I've been keeping an eye on the sharedstreets project, but looks a bit early to use and it's unclear to me how to integrate it right now. I considered doing this in terms of the raw valhalla edge ID's, but I believe they are not stable. If there is a better approach, I'm open to it!

**Comment by dnesbitt61** [comment]
Tough questions!  Part of the problem with OSMLR is that it requires a central way of defining the OSMLR Ids and then some way of maintaining them through time and OSM data changes. The process of deprecating Ids, adding new ones, tracking lineage, and other considerations was not entirely finished. Shared Streets and OpenLR offer ways of communicating linear references to street segments but do not have central ways of defining such segments. 

The reason OSMLR Ids were created and embedded into Valhalla was to do map-matching against defined segments. Doing this with OpenLR or SharedStreets seems like it would be difficult. 

Valhalla edge Ids are not persistent. If you update OSM and create new Valhalla data the edge Ids will be different.

We are currently focused on Valhalla being used as a routing engine with externally defined traffic and other information associated to the graph using OpenLR rather than OSMLR. External systems will be responsible for creating the OpenLR references and maintaining their data. This reduces the scope of what Valhalla is responsible for (at least within our current efforts). 

Not sure this helps. Basically creating traffic data is hard and Valhalla is currently focusing on using externally created data, rather than being used within systems to create such data.

**Comment by dnesbitt61** [comment]
I have not followed SharedStreets and OpenTraffic closely and may have over generalized some of my comments. I do not know if SharedStreets is providing a central repository of segments or OpenTraffic project is planning to provide any updates to OSMLR definitions. 

Matching OpenLR to Valhalla edges is an area that we are working on currently. At this time thought I don't think we are planning to store OpenLR specifiers within Valhalla tiles so we aren't really thinking about the inverse match. I assume if you have some set of OpenLR definitions you could build some lookups to find the candidate OpenLR segments based on the Valhalla edge(s) node positions. Then some filtering using length and bearings (and perhaps form of way/road classification).

**Comment by chrisfosterelli** [comment]
Yes, I think that makes sense. I'd likely want to not do the inverse matching precalculated on tiles in my case anyway, like the OSMLR segments were, since there would have to be a tile update whenever the attributes changed. That's assuming I can get away with live calculating in terms of performance, of course 😄

Thanks for all your help, I think I have some exploring to do now!
