### ISSUE TITLE
Hardware recommendation for production release

### ISSUE THREAD

**Issue by vladoatanasov** [valhalla/valhalla#1435]
Hi,
sorry if this was already answered, but I couldn't find any information in the documentation or the issues. 

Are there any guidelines for the hardware for production deployment of the valhalla service stack? 

Thank you

**Comment by dnesbitt61** [comment]
A lot of this depends on whether you are trying to support a regional dataset for you application or need full planet support. I would look at the size of your Valhalla data - that will tell you how much disk you need? I would use the single tar file approach since it handles concurrency better by using a shared cache via mmap vs. separate caches. Valhalla probably works a bit better with more memory if you are supporting a planet dataset (e.g. 32GB or 64) but it will work with 16GB and that may be sufficient if you only using a regional dataset.

I am closing this issue. Please open a new issue if you have further questions. Thanks (and sorry it took a long time to respond).
