### ISSUE TITLE
Shortcuts can create inconsistent routes

### ISSUE THREAD

**Issue by legacychimera247** [valhalla/valhalla#1484]
hi everyone, i'm a sailfish os user, 
sailfish os has a navigation app which is called whogo maps, which uses open street map as maps provider and a program called osmscout for calcolating offline routes, maps and so on,
osmscout in turn uses valhalla for providing offline routes to whogo maps but it may happen it give the app some routes that are wrong or longer than expected. Considering whogo maps also support mapquest for online routing i decided to compare both valhalla and mapquest (both based on openstreetmap) and to my surprise mapquest gave me the exact route while valhalla a much longer one, and not correct due to street limitations not respected...why is that?

to give you a more concrete example, this is the exact route in mapquest

via migliori>via del popolo>via acquaviva>via dello splendore

while this is the one wrong in valhalla
via migliori>piazza della libertà>via vincenzo bindi>via 24 maggio>via filippo turati>via galileo galilei>via montello>via bertolino>viale dello splendore

This route is not only much longer but even unpraticable due to via bertolino being open only to church's processions

if you want to check both streets are in giulianova (abruzzo italy)

**Comment by kevinkreiser** [comment]
we'll need to see if something is wrong with our interpretation of the data or if the pathfinding algorithm is getting this wrong. thanks for the bug report!

**Comment by Pohli** [comment]
Maybe this is related. I experience similar, just see the two examples on the screenshots:
First example, calculated route included a detour
![screenshotroutea1](https://user-images.githubusercontent.com/26346589/45403717-22afe780-b65c-11e8-8bdb-09976a4da921.png)
After I didn't follow but took the optimal route Pure Maps automatically rerouted
![screenshotroutea2](https://user-images.githubusercontent.com/26346589/45403718-22afe780-b65c-11e8-8424-4179b4b72090.png)

Second example, exactly the same problem
![screenshotrouteb1](https://user-images.githubusercontent.com/26346589/45403719-23487e00-b65c-11e8-89be-ecbc180553ce.png)
after rerouting
![screenshotrouteb2](https://user-images.githubusercontent.com/26346589/45403720-23487e00-b65c-11e8-9acb-d25f04a7bc75.png)

If you need addresses or coordinates to reproduce the issue, just let me know.

I'm using Pure Maps (which is a fork of WhoGo Maps) with Stadia Maps routing on a Jolla1 phone.

**Comment by gknisely** [comment]
Yes, please provide the origin and destination lat/lngs for each route so that we can try to reproduce the issues.

**Comment by Pohli** [comment]
I don't remember the start points so I just chose random ones which reproduce the same issue. Both screenshots in my previous comment show the final part of the routes near the destination.

Example #1
Start:
Lat. 51.4981
Longt. 7.45578
Destination:
Lat. 51.5093
Longt. 7.40584

If I choose a nearer start point the route will be perfect. Start:
Lat. 51.5079
Longt. 7.42174

Example #2
Start:
Lat. 51.5248
Longt. 7.54642
Destination:
Lat. 51.5457
Longt. 7.54276

**Comment by gknisely** [comment]
@Pohli thank you.  We will look at these as soon as possible.

**Comment by dnesbitt61** [comment]
This behavior is due to use of shortcuts. For the short routes the forward search tree does not use a shortcut since it is near the destination but no such logic exists for the reverse search tree (do not use a shortcut when near the origin). This is also related to issue #249.

A couple possible fixes: 
1) Implement logic to exclude using shortcuts on the reverse search tree when near the origin (like the forward search tree does).
2) Address #249 and reduce speed on the shortcut edge to add cost to compensate for any loss of transition costs along the shortcut.

You could workaround this by using A* for short routes (edit src/thor/route_action.cc get_path_algorithm)

**Comment by dnesbitt61** [comment]
Changed the name of this issue. The issue occurs when using both shortcuts and regular edges on portions of the route - this can lead to inconsistent routes. Investigating a change to the logic to use either the shortcut edge or the regular edges. Use the shortcut edge when the next lower hierarchy is no longer being expanded - otherwise use the shortcut edges to bypass nodes where transitions downward can occur. This should fix the inconsistent route behavior (and fixes the reported issue). It also appears that this improves performance for longer routes. Further testing to validate route quality is being done.

**Comment by dnesbitt61** [comment]
These images show the inconsistency:
![image](https://user-images.githubusercontent.com/1838768/46087692-e494e680-c178-11e8-89b1-43f65389fd4b.png)

Moving the origin closer to the destination leads to a different path:

![image](https://user-images.githubusercontent.com/1838768/46087740-fe362e00-c178-11e8-856f-3d24ffd59163.png)
