### ISSUE TITLE
Contraction Hierarchies

### ISSUE THREAD

**Issue by lhorus** [valhalla/valhalla#1514]
So sorry about this question, I'm sure it pops up a lot:
- I've been trying to decide whether to use OSRM and Valhalla, and as far as I can tell, Valhalla is only behind on the use of Contraction Hierarchies and its 6.000 km max pathfinding - as far as I could tell. Are there any plans on implementing CHs?

PS- Planning on running this offline.

**Comment by danpat** [comment]
@lhorus The problem with CH is that it's basically the opposite end of customizable - one of Valhalla's strengths.  I would definitely not classify Valhalla as "behind" here - it's made a deliberate choice to focus on customizable routing.

Valhalla implements some speedups that are CH-like (shortcut edges and the tile hierarchy) that achieves good performance without compromising too much on the customizability front.

If you're running your own offline build for Valhalla, you can edit the code to remove the 6.000km limit if that's a problem for you.

(Note: I'm one of the core OSRM devs).

**Comment by lhorus** [comment]
Thank you so much for your reply.

So for new projects, especially offline where isochrones are really useful, you would recommend Valhalla?

Don't take me wrong, I just get confused by two so similar yet distant projects, and I fail to see what one provides that the other one doesn't.

As far as I could tell, both OSRM and Valhalla focus exclusively on Routing? No extra services?
And their key difference is OSRM uses CH for speedups, Valhalla has customization?

**Comment by kevinkreiser** [comment]
@lhorus no worries. yes it pops up from time to time. it is unlikely that we will be implementing CH any time soon. it would be possible to support multilevel dijkstra using the valhalla tiles as cells and storing a table of weights based on a given costing configuration but this work is also likely very low priority and given the larger size of our tiles might not even be advantagous except for very long routes.

When considering which technology to use for offline its important to think about your use case and hardware limitations. Here are some general points about the two technologies:

OSRM:
1. it precomputes routes so requests are super fast (faster than valhalla)
2. the precomputed stuff is stored in memory so depending on your dataset you might need a lot of ram
3. precomputing them means you cant get different routes at runtime (ie. avoid tolls, favor hills, penalize ferries, etc)
4. because its precomputed it will only support one mode of travel
5. localization support is better although comes via a javascript add-on
6. @danpat can you fill in some more here im not an expert

Valhalla:
1. it only stores the graph so routes are computed on the fly (slower than OSRM)
2. it doesnt store the entire graph in memory so you can run it on memory constrained devices
3. you can get different routes at run time by varying some parameters in the request
4. since it stores the graph you can change mode of travel on the fly (bike/ped/car/motorcycle/truck/etc)
5. localization is built into the engine but not as extensive as OSRMTI
6. the data is tiled so you can make the planet and then distribute smaller extracts
7. supports time based routing
8. supports transit routing
9. supports isochrones

**Comment by danpat** [comment]
@kevinkreiser 

> precomputing them means you cant get different routes at runtime (ie. avoid tolls, favor hills, penalize ferries, etc)

OSRM is able to compute some subgraphs to support some of these combinations, but they end up being strict "exclude", rather than weighted "avoid" - the feature is very limited, you still need to define the possible combinations at pre-processing time.

@lhorus Kevin's point about mode of travel is very valid too - the dataset generated by Valhalla is usable by all the costing options - bike/walk/car/truck/whatever.  It's a little larger than OSRM's dataset, but with OSRM, you can only do one type of routing on a single dataset.

**Comment by lhorus** [comment]
@danpat and @kevinkreiser - thank you so much for your time and replies! Its all clear now!

@kevinkreiser two last questiosn:
- Valhalla requires that we have .pbf files, use Mjolnir to convert them to .vtiles to feed Valhalla. This would mean having the road information on an .mbtile for rendering, and road information in .vtile for Valhalla loading?
- Is Valhalla capable of handling multiple .vtiles for a single computation? (say from 2 files from 2 different countries)

**Comment by danpat** [comment]
> This would mean having the road information on an .mbtile for rendering, and road information in .vtile for Valhalla loading?

@lhorus yes.  AFAIK, there's no open specification for a unified visual/routing data format for offline navigation.  We've definitely been thinking about it here at Mapbox, but there's no implementation at this time.

In the commercial world https://en.wikipedia.org/wiki/Navigation_Data_Standard fills this role, but there's no open equivalent that I know of.

**Comment by lhorus** [comment]
@danpat - Any idea on a typical .vtile size? I know its a hard question, but just to check how much it would impact on an offline application with each country in its own .mbtile hence, with its own .vtile.

**Comment by kevinkreiser** [comment]
@lhorus 

1. mjolnir converts them into a set of `.gph` tiles which is a valhalla proprietary binary format not related to vector tiles (but techincally it is a vector tile). these tiles can only be used for routing so for rendering a map you will need another set of tiles.
2. yes you can supply as many pbfs as you want to `valhalla_build_tiles` say japan and switzerland (not bordering), or you could do something like belgium and netherlands (bordering). in both cases valhalla will work. if you are talking about the `gph` tiles created yes valhalla can load them both if they are sets of flat files in the same directory structure. valhalla can also load tar files but it currently cannot load more than 1 at the same time. there was some work to allow loading more than one at the same time though i cant find the issue/PR right now. let me know which one you meant!

Also please note that Mapbox sponsors the developement of Valhalla and is looking to release an offline sdk for maps and navigation. If thats something you'd be interested in you might try contacting Mapbox directly to ask for beta access.

**Comment by lhorus** [comment]
Thank you so much, both of you @kevinkreiser @danpat

**Comment by kevinkreiser** [comment]
Great discussion, thanks all!

**Comment by PayasR** [comment]
This was a great discussion, so adding this here just for completeness: 
CH isn't exactly the "opposite end of customizable", there is some work on making the CH customizable using nested-dissection orders, and there is even an excellent open source implementation by the group behind it: 
Paper: (https://arxiv.org/abs/1402.0402) 
Code: (https://github.com/RoutingKit/RoutingKit)

The basic idea is that the CH graph preprocessing can divided into two stages: a slower first stage in which the routing graph is built and shortcuts added using only separators and the structure of the graph, followed by a 'customization' stage in which edge weights are added to the graph with shortcuts. The customization stage is typically much faster, so can be used for adding 'dynamicity' to the routing.

Now of course, valhalla understandably has a very different set of objectives with the tile-based approach, but routingkit is worth taking a look :)
