### ISSUE TITLE
Routes through the roads with tags "access=private". 

### ISSUE THREAD

**Issue by cranik** [valhalla/valhalla#1581]
Navigation mode for cyclists sometimes builds a route through the roads with tags "access=private". 

For example:
through this factory: https://www.openstreetmap.org/#map=14/47.1603/37.5605

![image2](https://user-images.githubusercontent.com/5064130/47079254-a5a10080-d20d-11e8-9981-06d1fa1813a6.png)

**Comment by gknisely** [comment]
Hi @cranik can you provide an example route for this issue?  Please provide an origin and destination latitude and longitude.  Thank you for reporting this issue.

**Comment by dnesbitt61** [comment]
Looks like most of this path is just highway=service. However one way is access=private:
https://www.openstreetmap.org/way/524072867
We will look into why we don't disallow (or penalize) this way.

**Comment by dnesbitt61** [comment]
It looks like only a small part of this path is set to access=private. The current way we penalize private access in bike costing is to modify the edge cost (based on length). Other costing methods use a penalty when first entering a private access way. We are looking at updating bicycle costing to use this approach as well. In the meantime a data side fix would be to set other ways in this area as access=private if that applies.

**Comment by molind** [comment]
Also there is lift gate in both sides of that road. https://www.openstreetmap.org/node/5100600476. May be it should add big penalty or even exclude road from route. It's a big factory. I don't think they would allow bike to pass trough.

**Comment by dnesbitt61** [comment]
Adding a destination only penalty (as other costing methods have) makes sense. A gate penalty is already present. It looks like these penalties have to be pretty high to avoid this as the primary road (H-20) is slightly penalized for cycling. The idea with destination only (applied for access = private, driveways, parking aisles, drive-thru) is to penalize so that routing is allowed if the destination is in/on the private road but to try to avoid using the private road as a thru road.
