### ISSUE TITLE
Installing on bionic Ubuntu 18.04.1

### ISSUE THREAD

**Issue by Sherleen** [valhalla/valhalla#1630]
when perform `sudo add-apt-repository -y ppa:valhalla-core/valhalla`
there will be an error: `E: The repository 'http://ppa.launchpad.net/valhalla-core/valhalla/ubuntu bionic Release' does not have a Release file.`
Could you tell me how to solve this issue?

**Comment by kevinkreiser** [comment]
We dont currently have PPA builds for anything past xenial and even that is quite old. We've been meaning for some time to make new PPA builds but haven't gotten around to it. Much of this is due to switching the build system to cmake. While cmake does have the ability to build debian packages which we could upload to launchpad we need to do some work to finilize that pipeline. For now your best bet is to install from source. Please follow these instructions: https://github.com/valhalla/valhalla#building-from-source

Also note you may want to change the `if` to look for `bionic` instead of xenial. Apologies for the inconvenience we need to do some maintainance here. Thanks for bearing with us.

**Comment by Sherleen** [comment]
I am going to build from source, but when I perform `make -j$(nproc)`, 
there are some errors:
`src/valhalla/proto/CMakeFiles/valhalla-proto.dir/build.make:61: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:1031: recipe for target 'src/valhalla/proto/CMakeFiles/valhalla-proto.dir/all' failed
make[1]: *** [src/valhalla/proto/CMakeFiles/valhalla-proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target valhalla-midgard
[  2%] Built target libvalhalla.so
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`
Did I make some mistakes?

**Comment by kevinkreiser** [comment]
a couple of things, if you want to build this with the http server you'll also need to build https://github.com/kevinkreiser/prime_server#build-and-install

that project has a few dependencies so `apt install` those first, they are `czmq` and `zmq` dev packages.

after that and back in valhalla, you should check that you fetched the submodules. you'll want to do smoething like:

    git submodule sync
    git submdoule update --init --recursive

then try building again.

also what version of cmake are you using, the message you got seems to imply something is wrong with the generated make files. from the root of the cloned valhalla repo what is the output of:

```
rm -rf build
mkdir build
cd build
cmake ..
````

**Comment by dnesbitt61** [comment]
Note the added script: scripts/Ubuntu_Bionic_Install.sh
