### ISSUE TITLE
build on windows

### ISSUE THREAD

**Issue by gisshan2012** [valhalla/valhalla#1645]
How can i build on Windows?

**Comment by walkerke** [comment]
I've successfully run Valhalla on Windows using [Docker](https://docs.docker.com/docker-for-windows/install/).  

[This repo from the Dallas Morning News](https://github.com/DallasMorningNews/tx-valhalla-docker) contains a Dockerfile that can help you get started, though there are some changes you'll need to make.  Change the OSM extract to your desired data file, and change the `valhalla_route_service` command to `valhalla_service`.

**Comment by kevinkreiser** [comment]
we should be able to build it natively. @mloskot has done a bunch of work to make that possible. we dont yet have a section in the readme though for how to do it. perhaps you could give it a go and contribute it back. docker is also a reasonable approach of course :smile:

**Comment by mloskot** [comment]
Yes, Valhalla should build on Windows using Visual Studio 2017 without any problems, for both 32 and 64 bit.

Basically, fill the `...` gaps below and you should be able to build it:

```
cmake ^
    -S C:\path\to\valhalla ^
    -B C:\path\to\valhalla\_build ^
    -G "Visual Studio 15 2017 Win64" ^
    -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DBOOST_ROOT=... ^
    -DBoost_USE_MULTITHREADED=ON ^
    -DBoost_USE_STATIC_LIBS=ON ^
    -DCURL_INCLUDE_DIR=... ^
    -DCURL_LIBRARY=... ^
    -DLUA_INCLUDE_DIR=... ^
    -DLUA_LIBRARIES=... ^
    -DLZ4_INCLUDE_DIR=... ^
    -DLZ4_LIBRARY=... ^
    -DLZ4_GOOD_VERSION=... ^
    -DProtobuf_INCLUDE_DIR=... ^
    -DProtobuf_LIBRARIES=... ^
    -DSQLITE3_INCLUDE_DIR=... ^
    -DSQLITE3_LIBRARY_DIR=... ^
    -DSQLITE3_LIBRARY_NAME=... ^
    -DZLIB_INCLUDE_DIR=... ^
    -DZLIB_LIBRARY=...
```

Alternatively, I've committed in #1606 the `CMakeSettings.json` for convenience of the VS2017 integration with CMake.

**Comment by mloskot** [comment]
@uu3474 My PR #1605, among other things, is an attempt to work around this limitation.

**Comment by uu3474** [comment]
@mloskot thanks, i try to continue build, face next problems:
1) i don't understand why, but compiler didn't see any lib .h files, only boost works fine 
2) conflict macros MIN and MAX from windows.h with std::min, std::max. Can be roslved with #define NOMINMAX or escape with brackets, like (std::min)
3) in third_party/date constexpr/noexcept defines don't work for me, don't understand why, just replace by hands

fixed it all, but last one, i cant:
**C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. 
Done executing task "Exec" -- FAILED.**
its all, and no error in "errors" tab

btw, I've built the linux version, going to try with it

**Comment by mloskot** [comment]
> i don't understand why, but compiler didn't see any lib .h files, only boost works fine

Sorry, no idea what you mean.

> conflict macros MIN and MAX from windows.h with std::min, std::max. Can be roslved with #define NOMINMAX or escape with brackets, like (std::min)

The #1605 does also attempt to fix those, e.g. https://github.com/valhalla/valhalla/pull/1605/files#diff-95e351a3805a1dafa85bf20b81d086e6R52 (`NOMINMAX` may not help at all times though).
Keep in mind, my PR is 3 months old. New issues might have been introduced during that period.
Having said that, you really should be more clear about version/revision you are actually building.

> in third_party/date constexpr/noexcept defines don't work for me, don't understand why, just replace 
by hands

If you are not more specific about how the problem manifests, then no idea (my crystal sphere has broken :))

However, I can't see why `constexpr` or `noexcept` uses in the third-party could be a problem:

* Valhalla builds as C++11 `constexpr` is available - Check.
* [Visual Studio 2017 builds by default with `-std:c++14`](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2017) - Check.
* No use of C++17 `constexpr if` in `third_party/date` - Check

**Comment by mloskot** [comment]
I think, first thing we need to do is to set up VS2017 builds on AppVeyor and/or Azure Pipelines.
Without a working reference build, we will be chasing our tails.

**Comment by uu3474** [comment]
Sorry for my awful english.   

>i don't understand why, but compiler didn't see any lib .h files, only boost works fine

VS2017 compiler cannot find header files for protobuf, zlib. But cmake successfully find protobuf and zlib. I try vcpkg, try build protobuf for myself, result the same.

>I think, first thing we need to do is to set up VS2017 builds on AppVeyor and/or Azure Pipelines.
Without a working reference build, we will be chasing our tails.

sounds great, but I have never used these things before

**Comment by mloskot** [comment]
No problem.

I built Protobuf and zlib myself from sources. Although I use vcpkg myself, for Valhalla build I have not tried it.

I'm hoping to be able to work out the CI builds with VS2017 soonish, this month.

**What version/revision are you trying to build exactly?**

**Comment by mloskot** [comment]
FYI, CI builds on Windows using VS2017 proposed in #1691

**Comment by angiebs** [comment]
> > i don't understand why, but compiler didn't see any lib .h files, only boost works fine
> 
> Sorry, no idea what you mean.
> 
> > conflict macros MIN and MAX from windows.h with std::min, std::max. Can be roslved with #define NOMINMAX or escape with brackets, like (std::min)
> 
> PR #1605 (already merged) does also attempt to fix those
> 
> https://github.com/valhalla/valhalla/blob/57a7faf9fea26bcbf2cfbed5b62ced99db777928/src/CMakeLists.txt#L50-L52
> 
> 
> https://github.com/valhalla/valhalla/blob/57a7faf9fea26bcbf2cfbed5b62ced99db777928/src/CMakeLists.txt#L118-L120
> 
> `NOMINMAX` may not help at all times though.
> 
> Keep in mind, changes from that PR are 3 months old. New issues might have been introduced during that period.
> Having said that, you really should be more clear about version/revision you are actually building.
> 
> > in third_party/date constexpr/noexcept defines don't work for me, don't understand why, just replace
> > by hands
> 
> If you are not more specific about how the problem manifests, then no idea (my crystal sphere has broken :))
> 
> However, I can't see why `constexpr` or `noexcept` uses in the third-party could be a problem:
> 
> * Valhalla builds as C++11 `constexpr` is available - Check.
> * [Visual Studio 2017 builds by default with `-std:c++14`](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2017) - Check.
> * No use of C++17 `constexpr if` in `third_party/date` - Check

Hi

I have started building Valhalla on Windows and I really have followed all the instrucctions here and also looking into the other issues referenced in this post (#1606 and #1605).  It was a really demanding work since I have not worked with CMake in the past, so now I am learning.

I have faced all the problems with protobuf between others.

1. The most difficult problem to resolve was the: **conflict macros MIN and MAX from windows.h with std::min, std::max.  
In this case I had to  **#include <algorithm>** into the file util.h located in \valhalla\valhalla\midgard. 

2. I have commented the line 291 in the CMakeLists.txt => #add_subdirectory(test).  Can I do that without affecting the process? 

And finally I got a success Build in ALL_BUILD proyect in visual studio.

Then I executed "Build" into the proyect **INSTALL**, but I get this error

<img width="432" alt="Capture" src="https://user-images.githubusercontent.com/16880640/57708117-1788dd80-7669-11e9-97e7-cdf29da31e16.PNG">.

Any idea why?

**Comment by angiebs** [comment]
Hi

I have started building Valhalla on Windows and I really have followed all the instrucctions here and also looking into the other issues referenced in this post (#1606 and #1605). It was a really demanding work since I have not worked with CMake in the past, so now I am learning.

I have faced all the problems with protobuf between others.

The most difficult problem to resolve was the: **conflict macros MIN and MAX from windows.h with std::min, std::max.
In this case I had to include the library algorithm into the file util.h located in \valhalla\valhalla\midgard.

I have commented the line 291 in the CMakeLists.txt => #add_subdirectory(test). Can I do that without affecting the process?

And finally I got a success Build in ALL_BUILD proyect in visual studio.

Then I executed "Build" into the proyect INSTALL, but I get this error

error

Any idea why?

**Comment by angiebs** [comment]
Hi

I have started building Valhalla on Windows and I really have followed all the instrucctions here and also looking into the other issues referenced in this post (#1606 and #1605). It was a really demanding work since I have not worked with CMake in the past, so now I am learning.

I have faced all the problems with protobuf between others.

The most difficult problem to resolve was the: **conflict macros MIN and MAX from windows.h with std::min, std::max.
In this case I had to include the library algorithm into the file util.h located in \valhalla\valhalla\midgard.

I have commented the line 291 in the CMakeLists.txt => #add_subdirectory(test). Can I do that without affecting the process?

And finally I got a success Build in ALL_BUILD proyect in visual studio.

Then I executed "Build" into the proyect INSTALL, but I get this error

![error](https://user-images.githubusercontent.com/16880640/60708761-13fa3000-9f0f-11e9-8409-c9e73679cff3.png)

Any idea why?

**Comment by mloskot** [comment]
> The most difficult problem to resolve was the: **conflict macros MIN and MAX from windows.h with std::min, std::max.

Valhalla targets should have been protected against that issue by `NOMINMAX`, e.g.

https://github.com/valhalla/valhalla/blob/57a7faf9fea26bcbf2cfbed5b62ced99db777928/src/CMakeLists.txt#L50-L52

> I have commented the line 291 in the CMakeLists.txt => #add_subdirectory(test).

If you disable building tests, then no tests are being built but Valhalla library should still be built. 

>  Can I do that without affecting the process?

What process? Build? Disabling tests does affect the build process as it will not build the tests, quite obviously.

> Then I executed "Build" into the proyect INSTALL, but I get this error

I have never run `INSTALL` form inside the VS IDE.
I have never run `INSTALL` target for Valhalla.

However, there is some related configuration in place.
Perhaps you are not having permission or VS IDE runs with insufficient privileges to copy files where it wants to copy. You may need to read about/use [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html).

**Comment by angiebs** [comment]
Hi,

Yes I saw as well that the error was related with privileges in Program Files path.  I have modified the path value in CMAKE_INSTALL_PREFIX, where I know that I have enough access but still the error is happening.
