### ISSUE TITLE
incorrect map matching

### ISSUE THREAD

**Issue by xdmiodz** [valhalla/valhalla#1651]
Hi,

The following map matching request results in incorrect map matching

```
curl -X POST \
	  http://192.168.1.14:8002/trace_attributes \
	  -H 'Content-Type: application/json' \
	  -H 'Postman-Token: 7e2a5690-e919-4edf-9d8f-9aab28d4480a' \
	  -H 'cache-control: no-cache' \
	  -d '{"shape":[{"lat": 1.380112, "lon": 103.858198, "time": 1537461759}, {"lat": 1.392815, "lon": 103.85791, "time": 1537461819}, {"lat": 1.399078, "lon": 103.854918, "time": 1537461859}, {"lat": 1.401098, "lon": 103.85986, "time": 1537461879}, {"lat": 1.401242, "lon": 103.863942, "time": 1537461899}, {"lat": 1.401158, "lon": 103.868083, "time": 1537461919}], "filters": {"attributes": ["edge.way_id", "edge.speed", "edge.length", "matched.point", "matched.type", "matched.edge_index", "edge.id", "matched.distance_along_edge", "matched.point", "edge.begin_shape_index", "edge.end_shape_index", "shape", "matched.distance_from_trace_point"], "action": "include"}, "costing": "auto", "shape_match": "map_snap"}'
```

result is the following (you can find GeoJSON file with the result in the attachment)

<img width="416" alt="screenshot 2018-11-15 at 10 48 00 am" src="https://user-images.githubusercontent.com/563026/48526825-ef8c0d80-e8c3-11e8-8010-1fb4060b217b.png">

Here the markers are the original track, the straight line - is the matched geometry. 
Simple routing gives the correct result:

<img width="529" alt="screenshot 2018-11-15 at 10 49 17 am" src="https://user-images.githubusercontent.com/563026/48526884-282be700-e8c4-11e8-8243-18696d2e811a.png">

[result.geojson.txt](https://github.com/valhalla/valhalla/files/2583457/result.geojson.txt)

**Comment by xdmiodz** [comment]
Valhalla routing (from the start to the end points only) also gives correct result

**Comment by kevinkreiser** [comment]
the request has 6 points in it but the image has only 4. there are many factors at play when doing map matching but the two most important ones are the radius/accuracy supplied by each point and the timestamp. these determine what is possible and not for the match. i notice that the second to last point in the image is near many possible candidates. since there is no accuracy/radius provided in the request a default one is used which may exclude the path you expect. please try adding a `radius` parameter to each shape point or specfically the troublesome one. the value should be in meters
