### ISSUE TITLE
valhalla_build_tiles aborts after "osmid exceeded bitset" error

### ISSUE THREAD

**Issue by chrisfosterelli** [valhalla/valhalla#1710]
On the `valhalla/docker:build-2.6.1` image, after running `apt-get install libvalhalla0 libvalhalla-dev valhalla-bin`, I get an abort error:

```
root@019b37495557:/# valhalla_build_config --mjolnir-tile-dir /valhalla_tiles > valhalla.json
root@019b37495557:/# valhalla_build_tiles -c valhalla.json /data/british-columbia-latest.osm.pbf 
2019/02/06 21:11:18.846843 [INFO] Parsing files: /data/british-columbia-latest.osm.pbf
2019/02/06 21:11:18.848832 [INFO] Parsing ways...
2019/02/06 21:11:27.830722 [WARN] Max osmid exceeded bitset, resizing to fit id: 5744719695
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

This seems to work on other, city-based OSM exports from BC, but not the BC-wide export from Geofabrik. Any advice on getting this file to process?

**Comment by danpat** [comment]
@chrisfosterelli generally, `bad_alloc` from a C++ application means it tried to allocate more memory than you had free.

Your command-line looks a lot like a Docker container - make sure you've allowed sufficient RAM to the container - on MacOS, the default is 2GB, and 1GB on Windows.  I don't think there's a default limit on Linux.

**Comment by dnesbitt61** [comment]
The IdTable uses 1 bit for each OSM node Id (held within a vector of uint64_t). In current Valhalla this is set in pbfgraphparser to:

// This value controls the initial size of the Id table. If this is exceeded
// the table will be resized and a warning is generated (indicating we should
// increase this value).
constexpr uint64_t kMaxOSMNodeId = 6500000000;

If this limit is exceeded then it increases the reserved space for the vector by 1%, but it seems that resize copies from the current vector into a new vector  so temporarily more than double the space is needed. At least this appears to be what is happening. 

If you are able to build from source you could try changing this value (though I see you are using an old Docker image). Otherwise you may have to run the data ingestion for Valhalla on a system with larger memory capacity.

**Comment by chrisfosterelli** [comment]
That makes sense, increased the RAM to the container and we're looking good now. 
Thank you both @danpat and @dnesbitt61 !

In case it's useful to know, `valhalla_build_tiles` had to do about 8 of these resizes to fit up to id `6235001785` on the BC dataset.
