### ISSUE TITLE
Vizualisation of elevation data

### ISSUE THREAD

**Issue by AurelienLP** [valhalla/valhalla#1832]
Hello guys !

Is there a way to visually inspect the elevation data our server is currently using?
I've tried using the elevation demo from here but I only get a blank screen with a slider.

Thank you for your answer.

Aurelien

**Comment by kevinkreiser** [comment]
you need to download elevation data with `scripts/valhalla_build_elevation` and then you need to configure your `valhalla.json` config to point to the loaction where you downloaded the data. after that calls for `/height` should return elevation information along a path. note that elevation data is in its own tile set, not in the routing tiles

**Comment by AurelienLP** [comment]
Hello Kevin,

I can properly call the /height API on my server but I'd like to see the content of my directory directly on a map. Is it possible?

Thank you very much!

**Comment by kevinkreiser** [comment]
oh oh im sorry now i understand.. yeah the elevation demo points to long since decomissioned servers but... you can have a look here to see how the demo chooses which server to send requests to: https://github.com/valhalla/demos/blob/gh-pages/elevation/conf/environment.conf

have a look through the javascript in the parent directory and see if you can hack it to hit local host instead of the non working url. sorry for the state of disrepair the demos are in, they need some TLC but unfortunately we dont have the time at the moment.

**Comment by AurelienLP** [comment]
So I'll try to make the demo works if it is what I need. If I manage to fix it I won't hesitate to open a PR!

Thank you again Kevin, you are a huge help as usual.

Regards,
Aurelien

**Comment by AurelienLP** [comment]
Hello again guys!

I've been playing with the elevation data for some days now. I'd like to know which version of SRTM is used for terrain-tiles (https://registry.opendata.aws/terrain-tiles/) ? I was scared that the data were not that good for some areas... Are you confident about these data yourself?

Regards,
Aurelien

**Comment by kevinkreiser** [comment]
@AurelienLP the valhalla developers were the original coallators of this dataset. it was originally comprised of NED, SRTMv3 ETOPO GMTED and Bathymetry from a UK source. Since then it has been revamped to everything described here: https://github.com/tilezen/joerd/blob/master/docs/data-sources.md

The trick about any raster data sets is how they are masked together and aligning their NO_DATA VALUES. It is true that they may have discrepencies or oddities specifically at these mask boundaries or on coastlines. In my opinion the dataset is quite good. Rarely you can see strange gradients in coastal areas or in tunnels or over bridges (ie places where you'd expect strange things). These are an extreme minority.

**Comment by AurelienLP** [comment]
Hi @kevinkreiser,

Thank you very much for your help! I've created a PR to fix some of the problems I have encountered with the elevation demo. https://github.com/valhalla/demos/pull/222

I think that I can close the issue now :)

Regards,
Aurelien
