### ISSUE TITLE
OSM Id exceeds max specified when building admins

### ISSUE THREAD

**Issue by DupuyNicolas** [valhalla/valhalla#1870]
Hi,

Trying to build Valhalla and load europe-latest pbf from OSM.
I encounter this error when building admins : 

```
> valhalla_build_admins --config /conf/valhalla.json /data/valhalla/europe-latest.osm.pbf
> [INFO] Parsing ways...
> terminate called after throwing an instance of 'std::runtime_error'
>  what():  NodeIDTable - OSM Id exceeds max specified
> Aborted (core dumped)
```

I can't figure out why an osm id would be out of range, since it's an osm extract.
Also have a core dumped when trying to build tiles, i assume it's linked : 

```
> valhalla_build_tiles -c /conf/valhalla.json /data/valhalla/europe-latest.osm.pbf
> Segmentation fault (core dumped)
```

Can anyone help me solving this please ?

EDIT:
Just tried with a smaller pbf : andorra-latest.osm.pbf, same issue :(

EDIT:
Used gisops_docker to build valhalla worked.

**Comment by shekoufa** [comment]
Hey DupuyNicolas. I have the exact same issue. Can I build gisops_docker on Ubuntu 16.04?
Is this the only way to fix this problem?

**Comment by nilsnolde** [comment]
Sure, you can. I think the easiest way to get Valhalla running. Make sure to use the latest, think it's not released on Docker hub yet:

https://github.com/gis-ops/docker/tree/master/docker-hub-images/valhalla

**Comment by shekoufa** [comment]
> Sure, you can. I think the easiest way to get Valhalla running. Make sure to use the latest, think it's not released on Docker hub yet:
> 
> https://github.com/gis-ops/docker/tree/master/docker-hub-images/valhalla

Thanks for your response. I'll give this a try and will let you know if I had any issues installing and running it.

**Comment by shekoufa** [comment]
@nilsnolde I did what you suggested and built the newest version of valhalla from gis-ops and ran the container resulting on valhalla starting to engage the entire planet's  i.e. planet-latest.osm.pbf. 
It's been 24 hours that it's running and since I don't get any logs (or at least I don't know how to get any logs of the progress) I am not sure if it's still going strong or something is wrong there. Do you have a ballpark estimation that how long valhalla would take to process the entire planet's pbf? Also, do you know if there's a way to look at some log files on the valhalla container to kind of see the progress? The only ways for me to make sure that the job is running is to run top and ps to make sure that valhalla shows up there as a process. I am really lost here and I would really appreciate any help.

**Comment by shekoufa** [comment]
> @nilsnolde I did what you suggested and built the newest version of valhalla from gis-ops and ran the container resulting on valhalla starting to engage the entire planet's i.e. planet-latest.osm.pbf.
> It's been 24 hours that it's running and since I don't get any logs (or at least I don't know how to get any logs of the progress) I am not sure if it's still going strong or something is wrong there. Do you have a ballpark estimation that how long valhalla would take to process the entire planet's pbf? Also, do you know if there's a way to look at some log files on the valhalla container to kind of see the progress? The only ways for me to make sure that the job is running is to run top and ps to make sure that valhalla shows up there as a process. I am really lost here and I would really appreciate any help.

@nilsnolde forgot to mention that the machine running valhalla has 16 cores and 64 GB RAM
