### ISSUE TITLE
Time Dependent Cost Matrix

### ISSUE THREAD

**Issue by Guo-astro** [valhalla/valhalla#1882]
Trying to figure out how to implement a Time-Dependent Cost Matrix referencing the TimeDepForward and TimeDepReverse implementations. 
Some naive idea below
=====================
In timedistancematrix.cc 
https://github.com/valhalla/valhalla/blob/f8424690b874f88095458b6bc271602ed594f196/src/thor/timedistancematrix.cc#L98

we can modify time-dependent restriction as 

  if (directededge->is_shortcut() || es->set() == EdgeSet::kPermanent ||
        !costing_->Allowed(directededge, pred, tile, edgeid, localtime, nodeinfo->timezone()) ||
        costing_->Restricted(directededge, pred, edgelabels_, tile, edgeid, true, localtime,
                             nodeinfo->timezone())) {
      continue;
    }

that's it Any gotcha I should care about?

**Comment by dnesbitt61** [comment]
You would need code to set the initial time and then advance it in the ExpandForward method as is done in timedep_forward.cc.

**Comment by Guo-astro** [comment]
@dnesbitt61 Thanks very much! I found that in matrix, we dont use hierarchy_limits :

  if (!from_transition && nodeinfo->transition_count() > 0) {
    const NodeTransition* trans = tile->transition(nodeinfo->transition_index());
    for (uint32_t i = 0; i < nodeinfo->transition_count(); ++i, ++trans) {
      ExpandForward(graphreader, trans->endnode(), pred, pred_idx, true);
    }
  }

Is that because we do not use Astar?

**Comment by dnesbitt61** [comment]
TimeDistanceMatrix cannot use hierarchy limits to filter out edges since it must be able to mark destination locations on edges within any hierarchy. With hierarchy limits the search would likely not be able to find some of the destinations. CostMatrix (bidirectional) can use hierarchy limits to perform a more efficient search, however that is problematic when using time.

The distance may be there since the cost does not include distance - so it needs to be able to update the new distance for the updated best path.

**Comment by nilsnolde** [comment]
Closing for a fresh one, now that I'll start working on it: https://github.com/valhalla/valhalla/issues/4038
