### ISSUE TITLE
When Upgrading Ferry Connections Drop Restrictive Tags

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#1889]
When routing from stockholm to gottland there are some edges marked as destination only. In our first pass of the path algorithm we tell the costing not to take destination only edges. This makes it so that we find an extremely circuitous route. We should, in `ferry_connections.cc` when we 
 are upgrading the edges on the shortest path from where a ferry connects to the more major roads, also drop destination only attribution or anything that would prevent seeing a ferry connection.

**Comment by kdiluca** [comment]
@kevinkreiser Regarding this route, 
![image](https://user-images.githubusercontent.com/12497844/62657441-7f7f5500-b934-11e9-817f-effebe4914db.png)

Since a few of the edges near the ferry are marked as `destination_only=true`, I looked into removing this `w.destination_only() ||` from the if https://github.com/valhalla/valhalla/blob/master/src/mjolnir/ferry_connections.cc#L122 and regenerated the sweden data but it's still not taking the ferry unfortunately.  

There's currently no way that I can see to mark an edge attribute to reset the destination_only to true.     https://github.com/valhalla/valhalla/blob/master/src/mjolnir/ferry_connections.cc#L190  Any other ideas?

**Comment by kdiluca** [comment]
@kevinkreiser After our discussion, I attached the fix in the #1905 PR.  After regenerating the Sweden data, the output is as expected.

![image](https://user-images.githubusercontent.com/12497844/62672323-4234ba80-b968-11e9-94cf-fc94a335d748.png)
