### ISSUE TITLE
admin info missing or incorrect in the Philippines and Malta

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1903]
## Issue
When testing - noticed the `drive_on_right` flag was incorrect in the Philippines. When looking at the admin info - it was missing:

![image](https://user-images.githubusercontent.com/7515853/62638285-1cc59380-b90b-11e9-9be6-242b8cf0e963.png)

```
node info
lon | 120.99157
lat | 14.584733
```

Noticed that some routes in the Philippines and Malta will alternate the `drive_on_right` value.

## Fix the following:

- [ ] Philippines
- [ ] Malta

**Comment by kdiluca** [comment]
- Initially printing out the admin info, we were getting the following:
            - Philippines Cavite PH CAV
            - Philippines Bulacan PH BUL
            - Philippines Bataan PH BAN

- Thru process by process logging, found that all of the admin levels for our polygon were being returned as 0.  This caused us to look at the actual polygons that were being returned vs. what we were looking for.

- Determined that the Metro Manila polygon was missing from the db.  This is due to the fact that Metro Manila is a level 3 admin area and not a state/providence.

![](https://paper-attachments.dropbox.com/s_4F178E8CF665BD2AE251C9FF794242072091DFFBFF21223A34EB3CEFB1734019_1566441849199_image.png)

- Added logic to always fall back to country should this arise in other places.  We also added the Metro Manila to the lua file so that it gets set as a state manually.  However, we need to research other Federal areas like this one so that we can properly fall back to country and inject a state.  Need to add an issue on how to handle these issues.

- Ran valhalla_build_admins on latest planet pbf so that we could get Metro Manila in as an admin level 4.  New admins that are return now are:
            - Philippines Metro Manila PH 00
            - Philippines Cavite PH CAV
            - Philippines Bulacan PH BUL
            - Philippines Bataan PH BAN
            - Philippines PH

**Comment by kdiluca** [comment]
**Manila, Philippines:**

**Fixed:** (screenshot after lua changes to manually create state level Metro Manila)
![image](https://user-images.githubusercontent.com/12497844/63548697-cf494900-c4fc-11e9-9810-62c8750525c5.png)

**driving_side issues are now fixed:** https://paper.dropbox.com/doc/20190806_213111_production_test_routes_20190801_300_standardGuidance-vs.-20190806_213111_production_test_routes_20190801_300_sharedGuidance-driving-side-diffs--AjWehdedXZP2fgtIQ9eaoJ4lAQ-LX1xOeJOXfIrKkzg4sE2p
