### ISSUE TITLE
How to combine tiles?

### ISSUE THREAD

**Issue by rkroelin** [valhalla/valhalla#1913]
First off - thanks to everyone who has worked on Valhalla, i've learned quite a bit tinkering with it but still have a long ways to go.

I have failed to figure out how to do the following:

A) Is there a straight forward way to combine tile regions?  Say I've already done the valhalla_build_tiles dance with arizona-latest-osm.pbf and want to add in california at some later date?  How would you go about this without re-processing arizona?  (Goal would be to avoid trying to process a larger region with limited resources)

**Comment by rkroelin** [comment]
Tried starting valhalla_build_tiles at different stages without much luck.  If there's a write up or example somewhere that would be very helpful.  It seems unlikely to be able to just combine separate files and have Valhalla run with that.  I'm sure there are some connectivity processes that have to run (valhalla_build_connectivity ?)

**Comment by kevinkreiser** [comment]
@rkroelin its pretty non trivial because the tiles stores nodes and edges as arrays and then references them as array ranges. if you insert one edge, then all of the ranges after that edge need to be updated. similarly adjacent tiles point into these arrays via a global indexing scheme. these would also need to be adjusted for every edge. its not something that is impossible but because the addition of data would trickle down to basically the whole graph the problem is pretty non trivial. it might even be more efficient to do them all together.

this has been something we wanted to investigate since we started the project but frankly hasn't been given much time due to the obvious hurdles i described above. sorry we couldn't be more helpful here.

if you are simply interested in having a dataset, say on a client device, that grows over time, then i would suggest you cut tiles for the planet and deliver tiles from that planet tile set as you determine the client needs them.
