### ISSUE TITLE
Possible duplicates at level: 1 = 2. What is it?

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#1915]
I produced a synthetic OSM PBF file from TomTom containing data for multiple separate regions. It adds data to the PBF for each region successively, so that internally the PBF is structured:
```
nodes_region1
ways_region1
relations_region1
nodes_region2
ways_region2
relations_region2
```
Valhalla built and I could route on the tiles successfully, but I got these warnings after tiles were built and binned:
```
2019/08/27 13:05:22.875586 [WARN] Possible duplicates at level: 0 = 0
2019/08/27 13:05:22.875645 [WARN] Possible duplicates at level: 1 = 2
2019/08/27 13:05:22.875660 [WARN] Possible duplicates at level: 2 = 0
```
I got a bit skittish, even though everything worked as expected as far as I could tell. I thought it might be an issue of mixed OSM feature order in PBF, so I tried to merge single PBFs of both regions with `osmosis`, which should do the right job when merging. However, I still got the same warnings. 

Is this something to worry about? These regions are close to each other (Vienna & Munich metropolitan regions) but don't overlap in the street network, so all OSM features only exist once.

**Comment by dnesbitt61** [comment]
This isn't usually anything to worry about. With OSM data sometimes a way is drawn with overlapping sections and these create duplicate edges between two nodes in the routing graph. Routing generally works fine in these cases, it is just annoying that some OSM editors choose to draw ways that have overlaps rather than splitting them up. In src/mjolnir/graphvalidator.cc you can see where this happens (in the GetOpposingEdgeIndex method). There is actually a list of wayIds that have the overlaps - you could uncomment the code that would log the problem_ways (look for TODOs in this file).

**Comment by nilsnolde** [comment]
Ah nice @dnesbitt61 thanks for elaboration! I imagined it wouldn't be big deal, still got a peace of mind now:)
