### ISSUE TITLE
Alternate routes

### ISSUE THREAD

**Issue by austinhallock** [valhalla/valhalla#1921]
I didn't see an existing issue talking about adding alternate routes into Valhalla, so I figured I'd start one. 

It looks like [this PR](https://github.com/valhalla/valhalla/pull/1811) added the interface for requesting alternate routes, but doesn't actually return alternate routes yet. Is there still working being done on that?

I see that Mapbox's Directions API supports alternate routes, but I'm guessing that's not using Valhalla yet

**Comment by kevinkreiser** [comment]
correct, at this point alternate routes are really just an interface change only. we only used this change in map matching (trace_*) where you can ask for the top-k most probable matches. we then use this refactor of having multiple routes per response to store the two separate paths so that they can be serialized out later in the request pipeline.

**Comment by kevinkreiser** [comment]
closing this in favor of #2580
