### ISSUE TITLE
Is it possible to use the GPU for processing the tiles?

### ISSUE THREAD

**Issue by bryanrideshark** [valhalla/valhalla#1998]
How much work would it be to optimize some of the scripts, like `valhalla_build_tiles` and `valhalla_convert_transit` to use a GPU? Is it possible?

**Comment by kevinkreiser** [comment]
i wouldnt dare to say its impossible, but i will say its not really some that is well suited to gpgpu style processing work loads. we'd have to think about how to pack information about the graph into pixels and completely redesign the process. i think a better approach would be to let it be cpu bound but change it to distribute the processing across multiple nodes. this would be much more acheivable and require a lot less work to accomplish. im assuming the thing you want is throughput, i think the best way to get it would be distributed computing rather than gpgpu.

**Comment by bryanrideshark** [comment]
That makes a lot more sense. How much work would it take to achieve that?

Instead of using the file system, could something like Redis be used? Would make it possible to do the distributed building of the tiles without having to worry about marshaling results back to one machine's disk.

**Comment by mloskot** [comment]
I'm no GPU expert, but where filesystem access and files creation is involved in processing, then GPU don't help really to speed up things, fromhttps://developer.nvidia.com/blog/gpudirect-storage/

> fast GPUs are increasingly starved by slow I/O

 Similar constraints apply to MVT/Vector Tiles, AFAIK.

There are technologies under development to improve it, but I have no idea if/what is production ready, e.g. https://github.com/gpufs/gpufs

**Comment by kevinkreiser** [comment]
in the end we made it possible to distribute the build stage of the tile building process. at mapbox that brought the 8 hour processing time fpr that stage down to like 45min iirc. we might be able to do the enhancer too and if so, builds could be very fast
