### ISSUE TITLE
valhalla_build_timezones API has changed

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#2118]
Looks like with commit https://github.com/valhalla/valhalla/commit/76ab18c71e5ee0d3af53fd190e4873e82d4ad996, valhalla_build_timezones prints out constructed database into stdout. I'd say its somewhat unexpected on the basis of docs, where it is stated (or suggested) that timezone file will be in 'mjolnir.timezone' after running that script.

**Comment by kevinkreiser** [comment]
i think we should update the docs on this. i made the change on purpose because its doesnt seem to make sense to me to pass a config file to the program just to read one value out of it. we could change the script to take the output location as the argument or we could do what i did which is have the caller redirect its output to file. i should have updated the docs and i missed this issue because i was probably taking some time away from the computer when you filed it 😄

**Comment by kevinkreiser** [comment]
i've updated the docs to tell you to forward the output to file. sorry for the miss there

**Comment by rinigus** [comment]
Thank you very much for fixing docs. Maybe you should also add this snippet from https://github.com/valhalla/valhalla/pull/2519#issuecomment-670961952 as an example of how to load it from config
