### ISSUE TITLE
Adding custom edge attributes for dinamic edge costing

### ISSUE THREAD

**Issue by alexey-gl** [valhalla/valhalla#2162]
Hello!

I would like to add custom edge attributes for my own 
```
valhalla:sif:DynamicCost
```
class.
What is the preferred way to do this?

I have found 
```
valhalla:mjolnir:GraphTileBuilder.directededges_ext_builder_
```
field.
https://github.com/valhalla/valhalla/blob/master/valhalla/mjolnir/graphtilebuilder.h#L491

But it is notes as unused.
https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/directededge.h#L1156

Give me advices please and examples if it is exist.

**Comment by dnesbitt61** [comment]
No examples exist for how to populate DirectedEdgesExt. This was added as a structure for future growth but has not yet been used or tested. Several parts would be needed: 1) how to populate the data in the tiles (with the builder), 2) how to access it during routing/costing (no interfaces exist yet to access it during costing - so the interfaces to edge costing would need to be extended).

**Comment by emshach** [comment]
Hello, I see this issue is pretty old but it was the closest I could find ho what I needed.

For a client project I implemented a custom field that adds an account ID to the edges (to the original way data actually) and filter in `Costing::Allowed` to implement account-segregating route-sets. It's very much a hack and I'd like to implement this properly with maybe a small set of custom fields that could be added to the config?

This would be my first contribution to an open source project so I would appreciate some guidance in how to go about this.

**Comment by nilsnolde** [comment]
I guess I understand broadly: a user would pass a `uid` or so and the road data has a property `uid` to signify that user is allowed on it? sounds a bit like bike `network`s, just without the costing part, you just don't want to allow it. 

doesn't sound like too much of a hack to me. if it works for you, I'd say roll with it. I don't think the public project can accommodate this. we have hardly space left on DirectedEdge which you'd need to put this `uid` attribute on. and it's not standard osm.

**Comment by alexey-gl** [comment]
Just to share my experience: I've solved my issue by implementing additional tile set (like traffic but with my own custom way's data). This able me not to touch core structure of valhalla tile.

**Comment by alexey-gl** [comment]
By the way I this I would close this issue if everybody don't mind

**Comment by nilsnolde** [comment]
Yeah that’s a very good way when your attributes have a dense coverage. 

Yeah agree, we can close here, it contains almost all options to extend the data side.
