### ISSUE TITLE
transition edges

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2183]
What I  can understand from code is if a end node of a tile is not preset in same tile then set_leaving_tile is set to true. 
In many cases, we check for leaving_tiles() boolean and then get the tile in which end node is present. 
But also we are able to get endnode by simply directed_edge->endnode();
So I want understand,
1) when to check if edge ends in different tile. 
2) is directed_edge->endnode() give endnode for all the edges whether they are transition edges or not

Also, if a directed edge does not have opposing edge, then can we say that it is one way??

**Comment by dnesbitt61** [comment]
Directed edges do not include transition edges. Transition edges basically change the hierarchy level - moving from a node on one hierarchy to the "same" node on a different hierarchy.  To get all directededges from a given node you do the following: 1) iterate through directed edges on the same hierarchy, 2) for each transition edge move to its endnode, then iterate through all directed edges from that node.

All directed edges have an opposing edge by design. Edges with oneway travel are determined by the access flags: a oneway for automobiles will have auto access in one direction but not the reverse direction.
