### ISSUE TITLE
no motorway junction found in level 2 

### ISSUE THREAD

**Issue by asheesh1202** [valhalla/valhalla#2221]
While extracting the nodes inside the bounding box using loki, I could not find any motorway junction at level 2 but motorway junction nodes are present at level 1. Is this intended??

**Comment by dnesbitt61** [comment]
This is probably due to the method that reclassifies links during data import/creation. OSM mappers generally set the highway *_link tag to the highest road classification: e.g. all ramps/links connecting to motorways are assigned motorway_link tag. This is generally tagging for the map in my opinion, as routing methods are generally more efficient if the link is classified/tagged to the lower classification that it connects: e.g. a ramp going from a motorway to a primary road will be changed to primary_link in Valhalla. Thus, when forming hierarchies the node gets placed on the arterial road network (level 1) which includes primary, secondary, tertiary highways and links.

**Comment by asheesh1202** [comment]
So How Can I get all the nodes at level 2 only? I don't want node at other levels.

**Comment by dnesbitt61** [comment]
Not sure I understand. Do you want to create tiles where everything resides on level 2? this would mean no highway hierarchies and shortcuts so long driving routes would be much slower to compute. Or do you mean how do you modify loki to find only the nodes on the local hierarchy (residential, service, footways, etc.)? If that is what you need I would just iterate through the results from loki within the bounding box and remove any that are not on level 2.

**Comment by asheesh1202** [comment]
I found that the edges and nodes for the motorways, trunk highways is not available at level 2 but these are available at level 0 only.

My purpose is not to calculate route but to extract road network information using Valhalla and get its geometries for all the roads within the bounding box. So for me it doesn't matter to get the driving large routes or not. Anyways, I will be filtering shortcut edges. So, I want to get all the road (highways, artery and local roads ) at level 2. Is it possible to modify Loki or graph readers to get all the nodes and edges for highways, artery and local level at level2 and not at other levels.

**Comment by asheesh1202** [comment]
I found that the edges and nodes for the motorways, trunk highways is not available at level 2 but these are available at level 0 only.

My purpose is not to calculate route but to extract road network information using Valhalla and get its geometries for all the roads within the bounding box. So for me it doesn't matter to get the driving large routes or not. Anyways, I will be filtering shortcut edges. So, I want to get all the road (highways, artery and local roads ) at level 2. Is it possible to modify Loki or graph readers to get all the nodes and edges for highways, artery and local level at level2 and not at other levels.
