### ISSUE TITLE
Both edge and opposite are appearing in some bins

### ISSUE THREAD

**Issue by danpat** [valhalla/valhalla#2336]
Using the new `edges_in_bbox` function in `node_search.cc`, I found that the edge list returned contains both an edge and it's opposite in some cases.

This should not occur - tile building is supposed to ensure that only one of the directed_edges for a given bidirectional edge is ever used in bins in the tile.

cc @kevinkreiser

**Comment by kevinkreiser** [comment]
@danpat my assertion about edge_ids in bins was wrong, but its not a bug. sorry to send you in a loop here. i re-reviewed the code and remembered that i had done an optimization to make it so that when loki is reading bins from a tile, the edge id that it sees will, as much as possible, be in the tile it is reading the bin from. this allows loki to skip an extra hit of the tile cache. what it means though is that when you have a bounding box that is across multiple tiles you can indeed see an edge and its opposing edge because the edge because each tile is taking which ever direction of the edge will give it a cache hit when loki reads it.

loki uses an unordered_set to avoid checking the same edge geometry twice (always gets the opposing one and sticks it in the set as well) so i reckon we could do the same inside the edges_in_bbox function. i guess a nice optimization would be to have a way to pass in a preallocaed unordered_set so we can avoid reallocations (assuming there are many calls to this function over time).

sorry again for the false alarm!
