### ISSUE TITLE
How to map match without respecting one-ways

### ISSUE THREAD

**Issue by flashspys** [valhalla/valhalla#2403]
Hey, we want to map match routes, where the drivers didn't respect one ways. As a result the map matched route are very crazy as they do not drive through one-ways in the wrong way. Is it possible to disable the functionality of one-ways in a map-match request?

**Comment by kevinkreiser** [comment]
@flashspys we have a costing called `auto_data_fix`. you might try using that, im fairly certain it ignores oneways.

**Comment by flashspys** [comment]
I assume you mean https://github.com/valhalla/valhalla/pull/1283 ? This is document nowhere 😧  
But looks great. Now I need exactly this for bicylce 😄  Any way to get this behaviour without writing it by myself?

**Comment by kevinkreiser** [comment]
@flashspys its a bit of a proof of concept at the moment which is why its never made it into the documentation. there isnt a way to get this for bikes without implementing it, sorry about that. the good news is if you want to just do it to try it out for oneways its not that much work. you'll notice the allowed method in the AutoDataFix class doesnt just check for forward accesss but also backward access. this is the key of ignoring one ways. you can do the same in the BicycleCost, modify its allowed function to not care which direction it has access and allow both.  Something like this in the allowed function instead of the access check that is there now:

`!((edge->forwardaccess() & kBicycleAccess) || (edge->reverseaccess() & kBicycleAccess))`

Also you'll need to modify the edgefilter function to allow both directions.

With these 2 modifications you should be good to test ignoring oneways. If you are feeling adventerous you could add a new option to the costing options that lets you optionally allow the user to request that bikes ignore oneways.

**Comment by flashspys** [comment]
Thank you very much, I'll try my best!
