### ISSUE TITLE
Escape '\' in polylines

### ISSUE THREAD

**Issue by mateusjunges** [valhalla/valhalla#2411]
Good morning!

I'm using valhalla router and in the past days i faced some issues with the '\' character. In valhalla's test website, http://valhalla.github.io/demos/polyline/, there is an option to unescape this character. 

In my system, clients submit the polyline via api so that it can be verified whether a certain point of interest is on the route described by this polyline or not. The problem is that the polyline can come from different sources, with a precision of 5 or 6, which is informed via a parameter in the api.

Testing some polylines manually on the site above, I found that sometimes, for the polyline to be valid, I need to use the command `str_replace`, to replace `\\` with `\`.
I do this as follows:

```php
str_replace("\\\\", "\\", $polyline)
```

The question here is: is there any way of knowing when this replacement is needed? If I leave the system without this command, some polylines don't work, but if I put them in, others may not work. The best would be a conditional that uses it only if necessary.

I appreciate your help. Below, I leave a polyline in which the use of `str_replace` is necessary:

```
tkilCfin_H_BeCCMG_ArIiHZ]^C\\?NMc@]_@a@q@y@Q[K_@I_@Ac@@_AA]C]K[MYSUuFmEkCiB{DyCi@Wk@So@M_AOGIEIEIAKCKLGLENAN?L@ND~BvA~D~Brc@`\\dHlFnE`D~@j@hCvA|Av@xAn@fE|ApKtDrAj@vFhC~F|CnDhBbCnAXNzC~AlFpCvC|AjE~BvC|A~@f@bBbA`Ap@tAnArA|AxAtBhAvBdAlCn@xBPx@Nx@N|@B`@BNLdAFdA@ZDjA?fBMpLK`JM`LC|ECnEMrHGhGCdDEzEIvGI`G@pEB`AD|AH`BJnBXnCf@zDf@nCn@~CfAtDhAdDvAbD~AzCfBfDtB|DdCtEdBdD|CdGbAvBpDzGv@pAlArBnArBpB|CzCpF~AnCvB~DrAxBbBvBnA|A`GdHl@r@rArBr@tAn@vAl@nB\\fAf@hAb@nA`@j@z@v@z@r@~@j@bA\\lAZhARz@JdA?`AAb@EjFg@fAKpDc@hG_AbG}@rYwDnIgAhC]fD_@lDe@r@Kf@GxBY~BYxB[vAUtOsBhTsCbPmB^GhOoB|JwAlDc@|Eo@nG{@vEm@zDi@tB]`C[xC_@dAMx@I`BSvC]t@I~BS`AGfAEz@CbACfAArCHrD?tDRf@DhD\\hBTPBjDj@lBd@`FxAp@T`QnFfFhB|TjH|GvBnStGvJ|CfCx@`EhA`AT|@PH@z@PbAR~@NhKxAxPzBxP|BvBZz@HtBVzBVjVtC~HfAba@jFvGv@vV`DnV|CfDd@hUxC~C`@`BPhBNjBNvBJhABnAD|@@vA@vA@x@?vAArACbBInBGrAIhBQ~CYhAOzB[zHyAxB_@vB_@tB_@nWsElAU|UqEzHwAj^wGjP}C|HyAxF{@zDw@lEm@pFe@xDMpC?dE?|ELfPd@bDJlFXxM^tLZzERfCHnPd@`L\\dFR~@HrADfAFvJX|CFvOf@`BFx@F|CLfSl@vHZnBHvLd@`LZfQf@nCL|Lb@~ITvDPxD^vDf@rEz@~EnAnDjAnFpBn@Rz@Zf@PfHfCzG`CfP|FdOhFnBt@bTvHjDpAbBj@~A~@|@h@dC`BnAt@r@d@RHTHPBN@R?PAPCREPINIPOJMHMJSFSDQBQ@WAYAUGYIWKQMOQOSQmB}AsD{CcAy@a@_@YWSWS]O[M_@K[G]E[C]A_@@g@Bo@d@uH|@wOl@mGnNgmBJmAPcCh@wHPqCb@cFzC}Sx@{W|AuRzAoRbBeQjBqSN_B|@}JH{@`@oDRkBTaBh@yCd@_Ct@qCz@yCr@qB|@qBx@eBvAqCnIcQpA_Dr@cCp@wCh@kDL{ANaCHsC@cEa@kRCiB?kBDiBHiBNiBRgBXgB\\cB`@cBf@aBb@kAHSn@{At@yAb@w@xVcf@pFgKhCkGdB_Ht@_Ef@mD\\{DX}ELgFCmFKkD]qEm@uEgXuaBeAgJUwIJaI|@sZb@}MhE_wAJ_DlKakD?EH{B?EzDuqALgCT}Bb@mCn@wCjAmDlGiNlM{Xb@mA`@oAZqA`@gB\\iBViBPkBJmBDmB@mBAaDOyKAgBDgBHeBNeBReBXcB^_Bb@_Bh@}Al@yAp@wAdH}LhF_J~R{\\dCwE|AsEbFiP~A_HdAyH^yFXgEh@mBVi@^a@jDuBnCgArBCtA`@`Bx@zEjFlWjYn@n@|ExEnUhSjA`Aj@f@@@hAbA~f@`c@|[`YlClB~EnCrErBjN`GpRnIxD|AvD~@vDh@bDT`GKzUq@hCEdBVbB|@vB|@rBd@nAf@pAbApAxBjBnCtDxD`DzCxB`BbBxAZXPNRPZPTFx@@h@DnCVrDf@~EZ`ADdMr@dDLbCJ`ADpBLpAF~ZlAx]tAnAFnKj@xALtA@|BHpAHL?r@AN?x@?RERK^Sl@]z@i@HGJKbBcCTQPO|CkBhAq@BAPKJIj@_@b@U`@Ov@CD?bAE~@@~@ElCWbAATANM~GwGrFwErFcFlCcCPWD]P{BF}@Fi@DQBKN[JOFIdAeBnGhCvAh@^PNJNKFQzBmDOM_@Y
```

**Comment by kevinkreiser** [comment]
@mateusjunges this problem stems from json (and other markup/programming languages) treating the `\` character as an escape character. because of that, the only way to know for sure is if the user can tell you whether the place they got it from was escaping it or not. usually what happens is someone looks at raw json and pulls the value out of that. what the person should do is parse the json and get the unescaped string from it... but anyway there are some tricks you can try:

1. if you ever see a single `\` without another `\` following it, then you know the string is already escaped
2. the trick you already found which is that, its fairly unlikely that you would find `\\` in a string so you can just simply replace all double instances with a single instance though its possible you will find a false positive with this approach.

**Comment by mateusjunges** [comment]
Thank you @kevinkreiser!
