### ISSUE TITLE
timeparsing.cc missing explicit sstream include

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2446]
This might of course just be my inexperience with cpp dev, but building Valhalla on Win 10 (mvsc_x64) with VS 2019 and the `vcpkg/scripts/buildsystems/vcpkg.cmake` toolchain for `TOOLS` and `DATA_TOOLS`, I had to patch the `mjolnir/timeparsing.cc` to `#include <sstream>` as it would give me an `incomplete type is not allowed` for all declarations of `std::stringstream` otherwise.

Is it me or can I PR it in?

**Comment by kevinkreiser** [comment]
@nilsnolde please PR it. this is a common t hing in c++. different compilers on different os's will include different implementations of the stl. what inevitably happens is that on one system you include one header which happens to include another header you rely on but then on another system that same  header doesnt happen to include the other header you were relying on. this has spawned an idiom known as: `Include What You Use` which essentially says if you see a type in your source then you should include the header that declares it. sadly, because our project doesnt use a tool to do this for us, we mess up and miss some things from time to time

**Comment by nilsnolde** [comment]
Thanks for the explanation, will do tmrw morning!
