### ISSUE TITLE
understanding elevation integration

### ISSUE THREAD

**Issue by farfromrefug** [valhalla/valhalla#2450]
I am using valhalla in a specific context where i cant "access" elevation data the same way.
So i have question about elevations during route costing computation.

So the first question is, is there a community place where we can ask questions about valhalla? Guess it would be better than here.

Now about the technical question. I use Valhalla inside [Carto Mobile SDK](https://github.com/CartoDB/mobile-sdk) where we have a custom GraphReader to read valhalla tiles from a sqlite database.
It is working great and i would like to add elevation costing.
I want to use elevation data from a secondary sqlite database ( because i want to use those elevation datas for hillshading drawing and more).
At first i thought elevation data was "read" during route calculation. But looking at the code it seems elevation data is actually added during tile creation using mjolnir. Is that right?
If so i dont get why, while using valhalla in a normal valhalla set-up, the elevation tiles exist in a separated directory. Are valhalla tiles generated on the fly?

I need to know to see if i can find a way to plug a secondary sqlite database (in mapbox terrain tiles format) to read elevation data in valhalla.

Thanks

**Comment by dnesbitt61** [comment]
To perform costing using elevation factors, Valhalla generates a "weighted grade" for each edge during tile creation (if elevation data is available and used during tile creation). This attributes estimates how much elevation changes along the edge with "climbs" creating higher weighted grade values and "descents" leading to low weighted grade values. Precomputing this "factor" allows fast route computation. Reading elevation data while routes are computed would be quite slow for most applications.

**Comment by farfromrefug** [comment]
@dnesbitt61 thanks for the explanation. Any idea on the size % increase on each tile for this?
I understand what you say and i am ok with it. I think i can try and create my tiles.
My tiles (or i should say my sqlite db) is generated using a python script which for now only takes the valhalla tiles and insert it in the db.
Can you describe a bit when  valhalla tiles are "upgraded" to add elevation? Is it done on first tile "query" ?
Can you point me to some code? That way i can see if i can add that to my python script.

Thanks

**Comment by dnesbitt61** [comment]
There is no size increase to Valhalla tiles when elevation is included. In addition to weighted_grade for each edge, a mean_elevation for the edge along with maximum positive and negative slope along the edge is stored. Elevation is added to tile with the Elevation Builder in src/mjolnir/elevationbuilder.cc. This expects elevation data in "skadi" format which is basically 3601x3601 array of heights for each one degree lat,lon elevation file. The skadi directories provide access code to elevation files.

**Comment by farfromrefug** [comment]
@dnesbitt61 thanks for the deep explanation. I know understand that something must have gone wrong with my Valhalla tiles generations and that elevation should be in it!
Again thanks for taking the time to answer this. A community space would be awesome to prevent spamming you with such questions on github.

**Comment by durkie** [comment]
If I may just throw in an additional question here: is there any reason to keep the elevation data around after the initial tile creation process? My ideal situation is that I could mount the amazon s3 elevation data bucket during tile creation and then unmount it once that's over. (I hear this might not be possible because the `mmap()` calls used in accessing elevation data are set to read and write, but barring that, it'd still be nice to free up the storage space for the elevation data as quickly as possible.)

**Comment by kevinkreiser** [comment]
@durkie the main reason you'd want to keep the data around is that we do have an API that allows you to query the server with a polyline and get elevation along it. if you dont want to support this api then its no problem to ditch the elevation data after you've created the tiles. creating of tiles and running the server are different processes that are run in sequence so mmap here is irrelevant. maybe you're talking about only mounting it when tile building needs it? the tile building is broken into stages. if you mount it just before you run the stage that needs it and unmount it afterwords that should work perfectly well.

**Comment by durkie** [comment]
Thanks @kevinkreiser -- I was referring to the issue in #1461, but it looks like I mis-interpreted it, since that issue relates to running the valhalla service and not tile building.

Also, the units returned from the elevation service are always in meters right? I didn't see a unit specified in the docs, but interpreting it as meters looks like about the right result.

**Comment by kevinkreiser** [comment]
@durkie yep its in meters

**Comment by kevinkreiser** [comment]
@HarelM yes its possible. the idea is to store fixed postings along every edge in the graph in the edgeinfo object. using the length of the edge and the constant of the postings you can compute how many elevation values would be stored in the edgeinfo record. its totally doable, we just havent implemented it yet. i wish we had done this from the start because the built in elevation information that we do have (mean and at graph nodes) is kind of wasteful and not as useful where as this would contain all the data we need for all of those things and more

**Comment by nilsnolde** [comment]
@HarelM the nodes Kevin is talking about are the graph nodes, ie intersections. You’ll need more elevation info than that since intersections can be far apart, that’s why he suggests these postings.

what I don’t really understand with that approach: how would the Z component be returned in the response? I’d expect it to be encoded in the shape. Not sure right now what makes up the final shape (is it raw OSM nodes?), but every one of those vertices would need the z value. Would you then interpolate the z value for those vertices from these constant postings?

**Comment by HarelM** [comment]
I'm currently talking about the web service (as I have not made it so far as to run this on a mobile device).
The web service returns a shape that is encoded in a way that I don't think I can add z value information to it (I might be wrong).
So my question or suggestion is to add another return field with the elevation values for all the coordinates in the shape.
I'm good with the current "resolution" of the elevation if it will be returned for every OSM node, that's good enough for me, that's what I'm currently presenting to the users on my site (based on graphhopper):
https://israelhiking.osm.org.il/
I have rgb terrain tiles sqlite database on the client side for offline hill shading (using maplibre-gl-js and cordova), so I can probably use that somehow, but if the data is already in the routing tiles it would take less processing to get the route with the elevation right away.
I'll look for the carto mobile sdk mentioned here, I see that they have a POC of a cordova plugin from 2017 which can be a good starting point.
Any help would be appreciated :-) I'm only starting to learn this subject.
Progress of my work can be found here:
https://github.com/IsraelHikingMap/Site/issues/1636

**Comment by HarelM** [comment]
> What you can do even now: you have the elevation tiles locally,

I know, but this is problematic in terms of disk space and memory usage when working on a mobile device (to my understanding, especially if I want to embed a more accurate elevation data which we have for Israel). this is why I hoped this is already stored in the routing tiles so that I will be able to retrieve it with the routing request/response. :-(
I can probably also query the rbg tiles I already have as mentioned above in this thread, but I think the best solution from my point of view is to have it inside the route tiles. But I understand this might be problematic or even not doable in this library...
Thanks a lot for the super quick and informative responses!
The problem with graphhopper is that their mobile ports are not maintained anymore by the company but rather by the community and I think their graph cache is not in the same versions, so in order to use grpahhopper I'll need to build a different cache for iOS, Android and my web service, which is less than ideal, assuming I'll be able to make them work...

**Comment by HarelM** [comment]
P.S. thanks for the reference to the python code where one can see that 3d is supported in this format, so there's no need for an extra return field, in theory, as one can simply encode it in the `shape` data.
