### ISSUE TITLE
avoid polygons

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2570]
We'd like to add the ability to avoid entire polygons, because the `avoid_locations` is often not the right thing if the client doesn't have access to road geometries to be able to set exact locations. Would that be interesting for you?

I guess it'd have to be an additional request parameter to not break the existing avoid_locations. E.g. passing a flat list of coordinates representing a ring? Or with the existing `avoid_locations` and a switch (e.g. avoid_polygon=true/false) to let valhalla know the locations represent a polygon?

Any red flags coming to mind? Also, if you're interested, a few pointers would be appreciated. 

I could imagine that an implementation isn't that straight-forward and possibly comes with (quite) a performance hit.

**Comment by dnesbitt61** [comment]
I would probably add a new request parameter so that multiple avoid polygons can be added, in case a single polygon does not suffice and it may be tricky to extend avoid_locations to support more than a single polygon. Another possibility is to use either bounding boxes or circles as the avoid regions - this could yield better performance than general polygons.

Probably the best performance would be attained by marking edges that lie within the avoid area (extending the logic that finds edges added by avoid_locations). Every time I think of this problem I start with finding all nodes within the polygon/area and marking edges that pass through those nodes. However, this will miss long edges that can pass through the area and not have a node within the area. An additional headache is that shortcut edges that intersect the area would also have to be found. The GetShortcut method in GraphReader can likely be used for this, but adds to the probable performance hit.

**Comment by nilsnolde** [comment]
Thanks for the suggestions!

I think multiple polygons would be great. There’d need to be a configurable total maximum of polygon area anyways (plus maybe a maximum total number of vertices to avoid 1000s of vertices making the geometry construction expensive). IMO it also doesn’t have to be able to cover entire cities, more like maximum a few sqkm in total for most use cases. 

With that in mind I’d prefer complex polygons, rather than simple shapes like circle/bbox. Although a circle could be nice additionally.

 I’ll get back to this once I’ll really start looking at it. Will be another couple of weeks though. Just wanted to test the waters:)

**Comment by nilsnolde** [comment]
I'll start working on this next week full-time, so I'd just like to clarify beforehand a few things:

- I'll implement a new `avoid_polygons` API parameter top-level and not mutually exclusive with the existing `avoid_locations`, so both could be passed
- it'll be nested JSON arrays to pass multiple exterior rings (interior rings don't make sense to me in this case..)
- config options in `valhalla.json` to set:
   - total maximum polygon area
   - (optional): total number of vertices in the polygons (??, idea being that polygons shouldn't be too complex)

Any comments/opinions @dnesbitt61 @kevinkreiser?

**Comment by dnesbitt61** [comment]
must polygons be convex or are general polygons allowed? Just thinking that convex polygons would be more efficient when finding nodes and especially edges within. What is the measure for polygon area? Squared degrees is easy since input would be lat,lon but wouldn't be intuitive to users. Other measures (square meters or square kilometers) may require projecting the lat,lon and Valhalla doesn't have coordinate projection support. Maybe there is an approximation that can be used based on the center latitude of the polygon but this computation could be tricky.

**Comment by kevinkreiser** [comment]
we have header-only boost::geometry. i would suggest using that to do anytihng with the polygons rather than rolling your own. then we wont have to worry about concave polygons being a pain in the butt. i would also suggest that we add a new search method to loki to do this similar to how node_search works. another thing i would suggest is to associate both directions of the directed edge at once so  you only have to intersect the shape once. what i would do is intersect the geometry of the spatial bins with the geometry of the polygons. then you have a list of bins to iterate over. from there you iterate over the edges in the bins and intersect each ones shape with the polygons. at the end you'll have a list of edges to avoid. we can work on the actual args and return types of the api once you get started with the implementation

**Comment by nilsnolde** [comment]
thanks to both!

> What is the measure for polygon area?
Right, square degrees are really not that useful.. "Projecting" to pseudo mercator would make it more intuitive (and way cheaper to implement than accurate projections), though that still has the same problems with latitude. Since it's "only" a config to not blow up the server, I'd be more interested in the general magnitude and 200% inaccuracy (for me) would be sorta in a reasonable range. I'd be surprised if more than 2 users each year would notice the inaccuracy.

What do you think?

**Comment by kevinkreiser** [comment]
@dnesbitt61 i suggest we allow adding shortcuts to the bins. i suspect that wont affect the data size much at all and it will make it possible to treat shortcuts just like any other edge. The DynamicCost::Filter function should still filter them for regular edge candidates so it shouldnt matter that they appear in the bins anyway. for reference this line: https://github.com/valhalla/valhalla/blob/eb5fe912b96109d5763cf92c6f113518be4a3fca/src/mjolnir/graphtilebuilder.cc#L912

**Comment by dnesbitt61** [comment]
that seems fine to me. bins are created at the end of the data import pipeline so it shouldn't be too difficult

**Comment by nilsnolde** [comment]
Sounds great, thanks @kevinkreiser ! Doesn't sound that difficult at all:)
