### ISSUE TITLE
(INFO) how to get edge id in DynamicCost::EdgeCost

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#2598]
I have a use case in mind in which I want to save the path in the database and encourage users to use that path, for that I am thinking of making a new costing class, that will fetch all the save path in from the database and reduce the cost of all the edges in that path, 

For this use case I need a unique identifier of each edge which I can use to save path in database , and later use it in `Cost DynamicCost::EdgeCost(const baldr::DirectedEdge* edge, const baldr::GraphTile* tile)` but I can see that DirectedEdge have no param like edgeId can can uniquely identify an edge , 

Is there a way to get the edgeId of that edge, 
If is there is a way is that id same as the osm wayid

**Comment by kevinkreiser** [comment]
@pranavpandey1998official there are a couple problems here. first is that the edge_id isnt stable between different versions of data. so if you make data today with OSM and look at the edge_id of a certain road and then you make data again a month from now that same road might have a different edge_id.

the way_id is consistent (in so far as it is on OSM (fairly stable)) but we also dont have access to this from the edge either.

might i suggest something simplier? if i understand you right you are trying to do popularity based routing. that is you want to say these edges are good edges to take in the graph. could we do the same thing but instead of edges use the nodes? to do this you would need to modify `DynamicCost::Allowed(const Nodeinfo*)` to also take the `const GraphTile*` as an additional parameter. Using the graph tile you can then recover the lat,lon of the node in space and indeed your database can just be the lat,lons of all the nodes in the graph that you want to allow.  You can then do some fuzzy matching to say if its within X meters of my database of allowed nodes then i allow it and if not then i disallow this node. lat,lon should be pretty stable for intersections in the graph so you should be pretty good with that. adding the additoinal parameter to that costing method should be pretty easy as well since usually you have the tile you got the node from.

**Comment by pranavpandey1998official** [comment]
@kevinkreiser, I want to encourage the user to take the path, If I use `DynamicCost::Allowed(const Nodeinfo*)` I think as the name suggests he/she cannot use any other path if the Allowed is false right?, also I just want to store the edge in the database for not more than 6 hours, do edgID work in that case , I am thinking of using `tile->edgeInfo(edge->edgeinfo_offset())->wayid() ` will this work?

**Comment by dnesbitt61** [comment]
You could do this similar to how the user avoid edges work within DynamicCost. Build an interface to DynamicCost to add a list of EdgeIds to favor. The main issue is that EdgeCost methods do not have the edge Id (GraphID) passed into the method - you would need to add this to the interface and then if the edgeId matches any in the FavoredEdge list you could reduce the computed cost. Unfortunately this would impact many parts of code, wherever EdgeCost is called you would need to add the edgeId.
