### ISSUE TITLE
Cross-compilation with MinGW64

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2618]
@mloskot I'm trying to compile valhalla on fedora now with mingw64. Not because MSVC doesn't work, but I need to use its python bindings with a python which was built with mingw64. Fun, fun..

Of course that screws up all compiler & cmake conditionals using MSVC. Can I (safely) replace all your `_MSVC_VER` with `_WIN32` (and `MSVC` with  `WIN32` in cmake files)? Or is there a specific reason why you chose not to use the latter? As I understand those variables are only set if the target platform is Win, so should still be ok if cross-compiling on Win for others (though I hope noone does sorcery like that..)?

**Comment by nilsnolde** [comment]
Hm.. I guess there's also quite a few checks which should stay `_MSVC_VER`, esp with version checks involved?! Guess I'll just try to compile and replace/fix where it complains.. Some are more mysterious than others, but don't think I'm competent enough to judge only by the code if it's win or msvc which is relevant..

**Comment by mloskot** [comment]
First, I don't think the Windows port was developed with cross-compilation in mind. I also doubt Valhalla was ever built using MinGW. I don't use MinGW myself as I don't consider it a native Windows compiler for my use cases. 

### CMake

I don't think `s/MSVC/WIN32` is feasible in the CMake files

- `$<$<BOOL:${MSVC}>:VC_EXTRALEAN;WIN32_LEAN_AND_MEAN;NOMINMAX;NOGDI>` this seems to me highly MSVC specific, but perhaps it's also sensible for MinGW (sorry, no experience here).
- `    $<$<BOOL:${MSVC}>:${VALHALLA_SOURCE_DIR}/third_party/dirent/include>` this seems to be Windows-specific, but `dirent,h` may actually be offered by MinGW, otherwise replacing the condition with `BOOL:${WIN32}` may be a good idea.

### C++ sources

https://github.com/valhalla/valhalla/blob/5c367f45db27ad10b4537bc8aa5e5dfef4ca9ff7/src/baldr/curler.cc#L9-L20

This feels like MSVC-specific, unless WinSock headers are also used when building with Valhalla as cURL client on Windows using MinGW. If that is the case, then `defined(_MSC_VER)|| defined(__MINGW32__)` would be the desired condition.

https://github.com/valhalla/valhalla/blob/5c367f45db27ad10b4537bc8aa5e5dfef4ca9ff7/src/baldr/tz_alt.cpp#L175-L184

This is a third-party source and already seems `__MINGW32__`-aware, so I'd assume that `_MSC_VER` needs to stay as is.
The `#if !defined(_MSC_VER) || (_MSC_VER >= 1900)` conditions in that file look more like checks for C++ version to detect support of `std::chrono`, so I'd keep it as it is too. By the way, perhaps https://github.com/HowardHinnant/date/blob/master/src/tz.cpp is an updated version of this file, it may be worth to compare and update it in Valhalla sources.

https://github.com/valhalla/valhalla/blob/5c367f45db27ad10b4537bc8aa5e5dfef4ca9ff7/src/midgard/logging.cc#L19-L21

This also seems MSVC-specific as I'd expect MinGW toolset should offer `gmtime`.

https://github.com/valhalla/valhalla/blob/5c367f45db27ad10b4537bc8aa5e5dfef4ca9ff7/src/mjolnir/osmpbfparser.cc#L31-L35

I'm not sure about this one as I don't know where does MinGW provide `ntohl` from.

https://github.com/valhalla/valhalla/blob/5c367f45db27ad10b4537bc8aa5e5dfef4ca9ff7/valhalla/filesystem.h#L20-L26

This seems MSVC-specific, unless MinGW does not provide such POSIX functionality (headers).

https://github.com/valhalla/valhalla/blob/5c367f45db27ad10b4537bc8aa5e5dfef4ca9ff7/valhalla/midgard/sequence.h#L26-L33

This also seems MSVC-specific, similarly to above.

------

For now, I can only offer those hints and 'gut feelings'. You will need to try building with MinGW and see what errors you get, then we can try to discuss more concrete solutions.

**Comment by nilsnolde** [comment]
Cool thanks @mloskot . I'd love to have a cross-compilation ability, though I realize that burdens the maintainability a little.. @kevinkreiser let me know if this is a red flag for the project. Once it compiles, I can try to add a GH action for a Fedora mingw compilation, going the docker route.

Exactly, will do trial & error and hope to have a functional cross-compiled valhalla lib by tonight, draft a PR and we can discuss specifics. Not even talking about other tools, e.g. boost-python & luajit would need to be built from source (or re-packaged, mingw64 recipes for older versions/other platforms exist). It reached 50% compilation last night (initially broke down at 6%), hope that's proportional to the effort!
