### ISSUE TITLE
Valhalla build failing with latest OSM files (std::bad_alloc)

### ISSUE THREAD

**Issue by bboure** [valhalla/valhalla#2629]
Hi there.

I am quite new to Valhalla and I spent the last 3-4 weeks going crazy trying to build my first planet tiles. My builds were always failing with several issues (more info in [this issue](https://github.com/valhalla/valhalla/issues/2585)).

In the end, I managed to make it work with an older pbf file (from July 20). So I was wondering if the latest planet files have some kind of issue or some data that `valhalla_build_tiles` doesn't like.

The common thing I noticed between my attempts was this error in the build stage.

`
[ERROR] Failed tile 2/517753/0: std::bad_alloc
`

Some notes:
- the failing tile number was not always the same
- the build would not stop at this point. It would fail later on with different types of errors (se below)

On the top of my head, the errors I have seen are:
- `std::exception``
- `std::runtime_error`
- segmentation fault
- The process being killed by OOM killer

(The errors would happen randomly in my different attemps).

In my latest successful attempt, the 'bad_alloc' error did not show up. This is why I think this must be related somehow.

From the logs that I kept, here are some of the bad_alloc I have seen (from different builds)

```
[ERROR] Failed tile 2/517753/0: std::bad_alloc
[ERROR] Failed tile 2/517741/0: std::bad_alloc
[ERROR] Failed tile 2/693716/0: std::bad_alloc
```

As you can see, it did not always happen on the same tile.

The pbf files I have tried and have failed:
- Sept 11
- Sept 18
- Sept 25

I hope this helps.

**Comment by ImreSamu** [comment]
> In my latest successful attempt, the 'bad_alloc' error did not show up. 

please give more info about the **latest environment**:
- hardware ( cpu core, **memory** , **swapfile size** , kernel, os  ) 
- valhalla version, build option, docker version
- [any errors in the kernel ](https://upcloud.com/community/tutorials/troubleshoot-linux-memory-issues/)

> The pbf files I have tried and have failed:

you can check the osm file integrity with  [`osmium check-refs [OPTIONS] OSM-DATA-FILE`](https://docs.osmcode.org/osmium/latest/osmium-check-refs.html)

if you are still using ["(4 CPU, 16 GB RAM)"](https://github.com/valhalla/valhalla/issues/2585#issuecomment-698755872)
* then try with 16GB RAM **+ 64 GB Swapfile** ;  ( or better with 32GB RAM + big swapfile )


imho: 
* it is normal than latest openstreetmap file - needs more memory for processing,[ this is a known problem](https://blog.jochentopf.com/2016-04-20-node-locations-on-ways.html)   
* and the osm nodes .. just increasing every day ..  https://osmstats.neis-one.org/?item=elements see _"Nodes in the database"_
 
> segmentation fault

if you are still using v3.0.9; then a similar problem fixed https://github.com/valhalla/valhalla/issues/2479#issuecomment-662920852

**Comment by bboure** [comment]
@ImreSamu 

My latest env was (the one that worked): 
- 8 CPU + 32 GB of RAM (m5d.2xlarge on AWS)
- no swap file
- OS: AWS ECS optimized AMI (amzn2-ami-ecs-hvm-2.0.20200905-x86_64-ebs)
- valhalla version: latest master (20727f07ad292a28a9b66553b86ccc721293187f I believe)

In the **failing builds**, here are the several things things that I tried:
- 4 CPU + 16 GB RAM / 8 CPU + 32 GB RAM
- ubuntu and CentOs
- with and without docker
- added up to 16 GB SWAP
- reducing concurrency (to 4, on the 8 CPU machine)

Note that I have been watching RAM usage during the builds and I never saw it going above 2-3 GB

If I can, I will try a newer build again with even bigger swap and reducing concurrency to 1.

I did not check osm integrity but I did check the md5 checksum after downloading the files (they were good). Will try to do that too.

Thanks.

**Comment by ImreSamu** [comment]
>  with even bigger swap and reducing concurrency to 1.

AND
please backup the full  [install info,  logs, options, cmake commands, logs, etc  ](https://github.com/valhalla/valhalla#building-from-source)  , 
so we can find the answers for .. 
   -  static or shared libraries ? ( `-DBUILD_SHARED_LIBS `)
   - gcc version? 
   - using `ppa:valhalla-core/valhalla` or not ?
   -  ...

add (gnu) `time` - [for checking memory ](https://stackoverflow.com/a/774601) - and please share your result .. 
*  `/usr/bin/time --verbose valhalla_build_tiles --conf  .... `

imho:  it can be useful - for others ..

**Comment by kevinkreiser** [comment]
yep i agree with @ImreSamu we need a bit more information to get to the bottom of this.

1. the full build log would be helpful so that we could see what stage you were in when the process was OOM killed. im guessing it was in the "build" phase right after parsing based on your log line above but would be good to confirm
2. build the code with debug symbols `RelWithDebInfo` and run with gdb and tell it to catch exceptions `catch throw`. when the standard library throws `std::bad_alloc` the debugger will stop there and we can see why
3. if you are only using 2-3GB of ram then it must be that somehow a crazy high number is being passed to some allocator and that allocator is saying woah that is way more than we have available. i didnt scour the code to think about where this can happen but its totally possible. i think if you do step number 2 above then we'll be able to tell what exactly is going on because we'll be able to see what the allocation was and where it was asked for in the code

**Comment by mhendu** [comment]
Any updates on this problem? I've been trying to build the whole planet with a bunch of different PBF files, so far unsuccessfully. I'm running Valhalla in a virtual machine and have allocated in my latest attempt 20GB of RAM. It's been running for about 14 hours so far and this morning I got my first std::bad_alloc error (on the PBF image from October 31, 2022). This was on tile 2/464233/0. Previous attempts kept failing after a certain point, although I think I may not have allocated enough RAM before. I would've thought, from the threads here, that over 16GB that shouldn't be an issue, though.

**Comment by nilsnolde** [comment]
Half an hour ago, another planet instance was successfully built on the public servers. Yeah I would expect 20GB RAM to work for the planet. And it does sound like a RAM exception. The info of around 16 GB for the planet is sufficiently old I think. I'm not sure enough with the graph build, not entirely certain what exactly lies in RAM, but I'd guess the RAM is sorta linear with the size of network and the planet was growing like > 30% in the past 3 years or so. So might be that RAM requirements also went up beyond 20 GB.

Even so, how much RAM do you really have? What's the environment? Virtual vm of Linux on Win?

**Comment by mhendu** [comment]
Yes, correct, running Windows 10, and VirtualBox with Ubuntu 20.04. I was trying to check the swap file size and the machine was not really responsive so I killed it and am starting over - if I run into another issue maybe I'll try the latest planet instance, or find one from July 2020 if still available since that worked for another user. The swap file was only set to 1GB so I'm increasing it to 64GB. The computer has 32GB of RAM total.

**Comment by nilsnolde** [comment]
If it's swapping a lot, probably you'll have to have a long breath. Can only recommend to try natively on Linux, ideally a server vm that doesn't bog down your laptop with a planet build. Make it dual-boot, get familiar with Linux (if not already) and enjoy a barrier-free dev experience:) Just kidding, everyone's own decision.

**Comment by nilsnolde** [comment]
Probably won't change much (or even make the performance worse), but did you try with docker/WSL2?

**Comment by mhendu** [comment]
Haven't tried that but will give that a shot if this doesn't work. I built Italy just fine on my current setup so it's most likely either a resource issue or a problem with the PBF file. After I finally get the planet built I won't likely update it for a while, and I'm assuming running a query will take significantly fewer resources than building the planet (Valhalla worked fine for running queries on the Italy tiles with 1GB of RAM and 1 virtual processor) - for my day-to-day use the Windows environment works better for me, but appreciate the suggestion. :)

**Comment by nilsnolde** [comment]
> I'm assuming running a query will take significantly fewer resources than building the planet

We don’t support incremental tile builds if that’s what you’re getting at. Even if only a single road changed you’ll have to rebuild the entire planet graph. Some day..

**Comment by mhendu** [comment]
Right, I saw that. I mean once I build the planet I can reduce the system resources used to simply check routes via Valhalla against the tiles I've built.

**Comment by nilsnolde** [comment]
Ah sorry, I was not reading properly! Yeah, that consumes far less resources usually (beware of big matrices, that can easily be dozens of GBs).

**Comment by mhendu** [comment]
Well, it ran for quite a while, then reported 'Killed' but this time with no std::bad_alloc errors reported. I'm going to first try the July 13, 2020 full planet PBF before seeing if switching over to Docker does the trick.

**Comment by mhendu** [comment]
I could only get the July 13, 2020 planet as BZ2, and wasn't sure how to easily convert that to PBF, so I downloaded the latest tiles from Geofabrik, merged them with Osmium and tried again (although apparently you can feed Mjolnir multiple PBF files at once so maybe that step was unnecessary?). Was hoping that this would work since as I understand it the Geofabrik tiles exclude some of the metadata from the full planet PBF but still no dice. Again, I didn't get a std::bad_alloc error, but after a while building tiles dies with a 'Killed' error during the tile building stage. I can start the Valhalla service afterwards, but it says it only has 1580 tiles (out of 172824 that were reported during the tile building stage).

Apologies for the beginner question, but where do I see the log for what happened when building tiles died? I can't tell if this is a problem with my configuration somewhere, or an issue with the PBF file, and was hoping the log might give me some clues, but I don't see a log file and I couldn't find this in the documentation.

**Comment by kevinkreiser** [comment]
Bz2 just needs to be unzipped. Killed is almost certainly referring to being out of memory killed or oom killed for short. I would make sure your vm has 200gb of disk and maybe 16gb of ram. The build stage shouldn't need a lot of ram other than the memory maps it does on the parsed planet data but this amount is very flexible

**Comment by mhendu** [comment]
Got it, OK. The VM has more than 200GB of disk space, and 16GB of RAM with a 64GB cache. I built tiles for each region individually and they all worked within those specs (including Europe, which is almost as big as the rest combined), so I'm assuming I just need to bump up the cache to make this work for the planet, and it's not likely an issue with the PBF files. Will give that a shot.

**Comment by nilsnolde** [comment]
Actually I think disk is a bigger problem for you than RAM. A planet build takes by now at least that disk for temp stuff, not even counting the tiles. I’d provide at least 300 GB. Though you should’ve seen that on your last attempt if the disk was totally full I guess.

**Comment by mhendu** [comment]
Well I gave it 750GB of space, with now a 128GB swap file. I did run into disk space issues the first few times I attempted to do this, so I kept increasing the disk allocation. Hopefully what I've provided is enough.

**Comment by nilsnolde** [comment]
Oh yeah 750 gb is plenty enough, at least if you use PBF. If that’s surely not a problem, then we’re back to RAM.

**Comment by kevinkreiser** [comment]
The process being killed is almost always ram but if it's during the build stage I don't know how that could be because they all share that mmap. Maybe mem maps are somehow miscondigured on your system and it allows it to use up all the ram? Did you say you were or weren't building on windows?

**Comment by mhendu** [comment]
I'm building on Ubuntu 20.04 in a VM inside of Windows 10. I haven't changed any memory settings from the default, other than the size of the swapfile after finding that building tiles kept failing, but it's possible I suppose. Again, though, I've now successfully built every region using my setup, just not the entire planet.

**Comment by nilsnolde** [comment]
Hard to estimate how that behaves😄 I’d really just get a server VM for a week and do it there. 16 threads will build it in 1.5 days.

**Comment by ianthetechie** [comment]
Just make sure it has good disks ;) I/O is the silent killer. Use SSDs if at all possible.

**Comment by mhendu** [comment]
Yes, it's using an SSD (although connected via SATA, so not the highest throughput). It made it through the build tiles stage successfully, so that at least does appear to have been a memory issue, but since late last night I haven't seen any change in the console, and memory / CPU usage are down significantly from when it was building tiles. The most recent messages are warnings ('Tried to exceed max vias per restriction(reverse)'). May as well let it keep running for a bit and hopefully it will wrap up.

**Comment by mhendu** [comment]
Hmm. No progress in quite a while. The process is still running, but there haven't been any updates logged in the terminal lately, and no files appear to have been modified since Saturday night. It seems to be stuck on 'Adding Restrictions at level 1.' The terminal is still responsive (e.g., I can scroll to see earlier messages) but worried at this point that it will never finish. Any suggestions?

**Comment by nilsnolde** [comment]
@mhendu did if work out for you in the end?

**Comment by mhendu** [comment]
It wasn't making any progress, so I killed the process and started over - I downloaded the July 2020 BZ2 planet file, decompressed it, then tried to build tiles with it, but I guess the file was too big as it errored out. So, I compressed that file to PBF and it's processing now. Fingers crossed!

**Comment by mhendu** [comment]
Success! This took considerably less time than the more recent PBF files and worked out OK. So, I'm thinking either it's a) combining the PBF files from all the regions together didn't work so well, but maybe it would work if I downloaded a recent planet PBF file and built tiles with the increased cache file size or b) I'm running into some system limitation or maybe a code issue with Valhalla due to the size / complexity of the later planet PBF files.

**Comment by nilsnolde** [comment]
Congrats:) 

> combining the PBF files from all the regions together didn't work so well

I'd also assume that to be the main perpetrator. If you have enough RAM (i.e. min 16 GB, maybe even slightly more these days) and enough SSD (i.e. min 400 GB), recent planets build just fine; they're building on our public instance every day.
