### ISSUE TITLE
CMake Generate step failed - Manually-specified variables were not used by the project

### ISSUE THREAD

**Issue by dimnioras** [valhalla/valhalla#2630]
Hi everyone,

I tried to install valhalla on a server using this guide (https://gis-ops.com/valhalla-part-1-how-to-install-on-ubuntu-18-04/), but I am getting this error when running cmake for the valhalla repo before installing. Here is the error I get:

```
CMake Error in bench/thor/CMakeLists.txt:
  Target "valhalla" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "LUA_INCLUDE_DIR-NOTFOUND"


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_NODE_BINDINGS


CMake Generate step failed.  Build files cannot be regenerated correctly.
```
My generating options are the following:

```
cmake . -Bbuild \
  -DCMAKE_C_FLAGS:STRING="${CFLAGS}" \
  -DCMAKE_CXX_FLAGS:STRING="${CXXFLAGS}" \
  -DCMAKE_EXE_LINKER_FLAGS:STRING="${LDFLAGS}" \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DENABLE_DATA_TOOLS=On \
  -DENABLE_PYTHON_BINDINGS=On \
  -DENABLE_NODE_BINDINGS=Off \
  -DENABLE_SERVICES=On \
  -DENABLE_HTTP=On
```

The first error occurs multiple times before the generation fails. Does anyone have any clue? Thank you :)

**Comment by nilsnolde** [comment]
Yeah, that tutorial definitely needs a brush-up.. Probably rather close this here and open an issue at our [tutorial repo](https://github.com/gis-ops/tutorials/). 

Lots has changed since that was written (new dependencies etc, which is where your issue is coming from: you're liking missing the LuaJIT dependency). If you want to install natively on the server and the instructions in the README here in the valhalla repo are not enough for you, I'd recommend to look into the CI jobs, they're always up to date. Or if you can live with a docker instance, check out ours: https://hub.docker.com/r/gisops/valhalla.
