### ISSUE TITLE
format.sh to be used in precommit hooks (or CI)

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2650]
EVERY time I push CI fails bcs I didn't format. To counteract my own stupidity I usually use pre-commit hooks. Which is not possible with clang-format as there's no error. Is there a reason why error_on_dirty.sh is not part of format.sh?

Would you be interested in this wrapper: https://github.com/Sarcasm/run-clang-format, instead of the current dual approach? Small python script which has the same (relevant) inputs but errors out if there are diffs, hence doesn't commit if used as pre-commit hook (or ails CI). I'd PR it.

**Comment by PureW** [comment]
It sounds like you'd like for format.sh to exit with an error-code if it ends up introducing changes as part of formatting?

Doesn't that sound a bit odd? As a casual user of the script, I'd assume a faulty run would mean that the formatting could not be completed, probably because of incorrect C++ somewhere. I wouldn't expect an error code in the case of a successful format run.

In your pre-commit hook, can you not run `format.sh` first and then `error_on_dirty.sh` immediately after?

**Comment by nilsnolde** [comment]
> It sounds like you'd like for format.sh to exit with an error-code if it ends up introducing changes as part of formatting?

right, that's what I'm trying to do:) for linting IMHO it should fail if the lint is not successful, i.e. files are changed. Then at least I see that I shouldn't commit as-is (even without pre-commit hook), as the shell response to an error is arguably more visible (at least in the shells/themes I use) than having another round of git unstaged changes.

But it's fair if that's not wanted. Not necessarily good to change stuff other devs got so used to. `.git/hooks/precommit` is actually just an executable, so it can be filled with the contents of format.sh & error_on_dirty.sh respectively.
