### ISSUE TITLE
Specifying truck costing options in the REST request?

### ISSUE THREAD

**Issue by eugen-nw** [valhalla/valhalla#2676]
I'm very sorry for the bother, but I cannot figure out this part from reading the docs.  I'm wondering if the format below is what I need to use please?  I verified and it worked, but at the same time specifying "hazmat":"blue" did not return any error, so I am not certain that I'm on the right path.

```
, "costing": "truck", "directions_options":{"units":"miles"}, "costing_options":{"length":15.65, "hazmat":true}
```

Also, could someone please inform what are the default truck costing option values that Valhalla uses?

**Comment by dnesbitt61** [comment]
You need to specify truck within the costing_options (see example for auto costing options in the turn by turn API doc). Ty something like:
"costing": "truck", "directions_options":{"units":"miles"}, "costing_options":{"truck":{"length":15.65, "hazmat":true}}

This is needed since costing options for multiple "modes" can be used with multi-modal routing.

**Comment by eugen-nw** [comment]
Excellent!  Thanks very much for the info!
