### ISSUE TITLE
Question: difference between directed edge if and osm way id

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#2701]
I can see that in the code you have both, directed edge_id which is used in EdgeLable and also osm_way_id, I know what is osmway_id , I need to know
1) is there any relation between the two, are they interchangeable?
2) is there something to do with hierarchical tile, that you guys introduced directed edge_id, means let's say if you have 2 hierarchical tile system then the edge is identified differently with different edge_id on both hierarchical system, 
3) do you break the osmway into multiple directed edges based upon the tile, like if a osmway is between two tiles, you will break the osmway and give different edge_id to them?

**Comment by kevinkreiser** [comment]
1. directed edge ids and osm way ids are not related to each other
2. if the question is whether or not the same edge in the graph can have different edge ids, the answer is no. our graph is directed though, which means for any edge we do store 2 directed edges, each having their own id. but for a single direction of a given edge that edge will only be refered to with one id. the same does not hold true for nodes. because the same node may appear on one level of the hierarchy and then again on a different level we will have 2 different graphid's for these nodes and they will be connected by node transition information.
3. we do break osm ways into multiple edges where they are intersected by other ways, where they intersect themselves and also where the nodes along the ways may have certain properties (like a gate). when a way crosses from one tile to the next we do not clip the way at the tile boundary. the edge that is created starts in one tile, may touch any number of other tiles with its underlying geometry but will eventually end in either the same or a different tile
