### ISSUE TITLE
Installation from PPA fails - documentation outdated?

### ISSUE THREAD

**Issue by homtec** [valhalla/valhalla#2842]
The documentation describes these steps for installation from PPA 

> grab all of the valhalla software from ppa
> sudo add-apt-repository -y ppa:valhalla-core/valhalla
> sudo apt-get update
> sudo apt-get install -y valhalla-bin

Trying this, the installation fails with 
`Unable to locate package valhalla-bin`

Looking into https://launchpad.net/~valhalla-core/+archive/ubuntu/valhalla shows there is no valhalla-bin and all packages are very old. So I guess the documentation is wrong?

**Comment by kevinkreiser** [comment]
yes the packges in the ppa are very old (several years at this point). this is because moving to cmake neutered all of the tools i wrote to do ppa deployments. recently people have been using docker (which our CI has all the steps for) to make images to deploy etc. i know its not the same as just apt installing it but until we find the time to go back and figure out how to make pbuilder and all the rest of the tools work with the latest cmake based build system the ppa will remain out of date. sorry for the inconvenience

**Comment by homtec** [comment]
Docker is fine. I just recommend to remove this from the documentation then as it leads in a wrong direction.

**Comment by kevinkreiser** [comment]
@homtec updated readme accordingly, thanks
