### ISSUE TITLE
Avoid locations and truck profile

### ISSUE THREAD

**Issue by easyest** [valhalla/valhalla#2853]
avoid_locations option works fine with auto profile. But with truck profile it is completely ignored. Maybe that is by design, and should be mentioned in documentation.
P.S. Did not test with other profiles.

**Comment by nilsnolde** [comment]
ha weird.. I can confirm. quickly glancing at the source code that doesn't make much sense though, truck checks for avoided edges the same way all other costings do.. if no one else picks this up I'll have a look soon

**Comment by easyest** [comment]
I do not have enough c++ experience to investigate the code, but I have a feeling, that it could be related to the fact, that truck profile (at least theoretically) should check truck related restrictions. Maybe this logic overrides avoid_locations logic?

**Comment by nilsnolde** [comment]
I recently added avoid_polygons (#2570), tried that instead of avoid_locations and the exact same thing.. couldn't let that sit of course.. So, I got it, was a sorta subtle bug where the travel mode was not properly looked up when looking at avoids.. And for avoid_polygons I just copied the same bug. Will be fixed soon, I'll PR now, I'm sure @kevinkreiser will merge shortly after, it's a 2 line change.
