### ISSUE TITLE
Question regarding heirarchitcal_level , heirarchitcal_lemit and tile level

### ISSUE THREAD

**Issue by pranavpandey1998official** [valhalla/valhalla#2858]
I am confused as to how these things work, I know you have divided tiles in 3 levels (highway, arterial, local) but I can see that you have 8 heirarchitcal level by default, (https://github.com/valhalla/valhalla/blob/68f4fa3ba5870ea30b65ff95d2416e7654799d36/valhalla/sif/hierarchylimits.h#L19) how is that thing work, if you have 3 levels of tiles and 8 heirarchitcal level,

 also what does up_transition_count means , it is set to 400 for level 2 does this means i can go 400 level up, that doesn't make sense??(https://github.com/valhalla/valhalla/blob/68f4fa3ba5870ea30b65ff95d2416e7654799d36/valhalla/sif/hierarchylimits.h#L41)
 
 can you please explain it more deeply , also if there is some research paper I can read about this

**Comment by nilsnolde** [comment]
I'm not exactly the expert on this, but I'll try some:

> if you have 3 levels of tiles and 8 heirarchitcal level,

8 is for future flexibility I think (the GraphID also allows for 3 bits for level, though that might be chicken/egg), 3 are used (the ones you mention). I could stand corrected for transit, not sure how that fits in.

>  it is set to 400 for level 2 does this means i can go 400 level up

I'd like to hear some more from someone with a deeper knowledge on the implementation, so pls correct me if I'm wrong. Looking at the code, that's limiting the amount of _downward_ transitions during the **entire expansion** (path finding) the algo can do (upwards is always allowed, the idea being it's visiting a lot less edges on higher levels, since there are more shortcuts and generally longer edges). Why exactly it checks for `max_up_transitions` and not `max_down_transitions`, no idea, but they are closely related anyways. I think it's sort of preventing A* to go haywire on transitioning between levels, which seems to be pretty expensive. That limit can also be relaxed, i.e. set higher, if no path was found in a first pass.

There's some higher level explanation in the [docs](https://github.com/valhalla/valhalla/blob/master/docs/thor/path-algorithm.md).   The detailed way it works is immensely more complicated due to the intricate complexities of road network routing (all the little details, like u-turns, destination-only etc).
