### ISSUE TITLE
Route by OSM Map Feature?

### ISSUE THREAD

**Issue by TTitcombe** [valhalla/valhalla#2888]
Is it possible to find a route that prioritises going through a certain feature of OSM data?
For example, "Go from A to B while going past a sports stadium"

There are a couple of considerations here:
* Does valhalla retain all tag information when converting to tiles (from the documentation, my sense is "no")
* Is there a concept of a negative weighting, i.e. prioritise some feature rather than penalising others

**Comment by nilsnolde** [comment]
It's much easier (if I get your question right): pass the coordinates of the location into the request e.g. as `via` (i.e. don't generate an actual leg, just pass through): https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#locations

What you're asking for: How would valhalla know the location of the OSM feature if you don't pass it? Or would you expect to pass say `amenity=stadium` (or whatever) and the route would pass by _any_ stadium? I think for the latter there could be sorta interesting use cases, but it's typically solved by conflating POIs with route requests. 

Of course then you'd _definitely_ pass by the stadium and it's not up to the routing algo to decide _if_ that's the best route from A to B based on e.g. decreased cost of edges around the stadium. Maybe you can elaborate on your use case and expected behavior a little? 

> my sense is "no")

Right, that would blow up the tile size enormously. It just stores what it needs.

> Is there a concept of a negative weighting, i.e. prioritise some feature rather than penalising others

Sure, that's how valhalla's factors usually work: `use_hills` etc.. it's not exactly negative weighting, but usually a factor less than 1 you multiply the cost with.

**Comment by TTitcombe** [comment]
Thanks for the rapid response.

Yes, my original idea was to get a route that goes by any instance (or multiple) of feature `X`. I don't have a concrete, singular use-case, but consider somebody who wanted to do a road trip and was a sports enthusiast, for example. They would want a route which lets them see as many stadiums as possible without adding more than `n%` to the optimal route time. 

I suppose, as you suggested, one way to do this would be to feed coordinates of stadiums into Valhalla directly: pre-process OSM data separately to Valhalla to identify possible stadiums; get a route from Valhalla using stadium coords as waypoints; post-process the route to decide if the time penalty is acceptable

**Comment by nilsnolde** [comment]
I think that's the easiest. It'd be exponentially harder to really incorporate this in a router with some tough decisions to make. I also can't see toooo many use cases. That sorta reminded me of landmark-based routing, where the instructions don't say `Turn Right onto Highway X` but rather `Turn left at stadium X and head towards tower Y`. Very nice for pedestrians or bikers I think and would also need to incorporate some OSM features somehow.

FWIW there's POI services based on OSM, so you don't have to do the hard part yourself. One of our older projects deals with that as an HTTP API: https://github.com/GIScience/openpoiservice.

**Comment by TTitcombe** [comment]
Thanks for your help. I'll check that project out.
