### ISSUE TITLE
Valhall can't be compiled with -DENABLE_DATA_TOOLS=OFF and -DENABLE_TESTS=ON

### ISSUE THREAD

**Issue by PureTryOut** [valhalla/valhalla#2899]
Because multiple test targets try to link against Geos even though it isn't found when `-DENABLE_DATA_TOOLS=OFF`.

https://github.com/valhalla/valhalla/blob/master/CMakeLists.txt#L307

```
CMake Error at test/CMakeLists.txt:63 (add_executable):
  Target "tiles" links to target "GEOS::GEOS" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

**Comment by kevinkreiser** [comment]
yep, its always only a matter of time until this happens. becasuse CI takes so long we dont test every single constellation of cmake arguments and because of that, we run into this. there is a plan to make an arm build, which, imho will have ENABLE_DATA_TOOLS=OFF and ENABLE_TESTS=ON. once we have that we'll get 3 birds with one stone, but until then we'll have to tackle these as we notice them. sorry for the annoyance

**Comment by PureTryOut** [comment]
Would it be ok to add the tests linking against Geos behind a `ENABLE_DATA_TOOLS` guard as well? Not sure if they are related

**Comment by kevinkreiser** [comment]
Yep that's exactly what we do for those. You'll see all the other tests that make data (ie use geos) nested under that flag
