### ISSUE TITLE
how can I reflects live-traffic?

### ISSUE THREAD

**Issue by masonSeo** [valhalla/valhalla#2924]
hello there. 
I want to build a route service that reflects live-traffic information using valhalla.

What should I do to provide a service that reflects traffic information?
There seems to be nothing clearly explained anywhere.

**The question is... how valhalla does traffic updates?**.
How should traffic data be prepared, through what process is it created as valhalla data, 
and how is it reflected in valhalla_service?
(If possible, I want valhalla_service to be reflected without stopping)

For example in osrm, 
the traffic information is updated in the following way.

1) run osrm data build process (generated graph data file)
 > osrm-extract -> osrm-partition -> osrm-customize ..
2) run osrm-datastore 
   > load osrm graph data file & populate to shared memory
3) run osrm-routed (route engine server) with using-shared-memory options
4) preparing traffic speed data that created in csv format
5) run osrm-customize module (With the traffic speed data) 
   > to update edge speed & generated new graph data file
5) Replace graph data file
6) run osrm-datastore 
  >shared memory populate & notify to osrm-route

**Comment by PureW** [comment]
You'll want to look into updating the traffic tiles as defined in https://github.com/valhalla/valhalla/blob/master/valhalla/baldr/traffictile.h and configure Valhalla to read these tiles https://github.com/valhalla/valhalla/blob/master/scripts/valhalla_build_config#L286

**Comment by kevinkreiser** [comment]
@masonSeo the only way to get this to work currently is to make a tar file of all the traffic tiles and update the tar file as you learn about updates in traffic conditions. the code memory maps this tarfile so you can make changes to it outside of the running router and those will be reflected. please note that you should not change the order of the files in the tar. there is no telling what crazy stuff that would do. the tiles in the tar are all fixed size for a given tileset so when you need to update one you can update it directly at the existing location it is inside the tar file.

it should be noted that we do not and will not provide tools to do this as it will need to be customized to whatever traffic data your server is hooked up to. since that can be so varied and the mechanism for delivering those updates equally so, we chose to provide the interface here but not the tools. you'll need to roll your own on that.

**Comment by masonSeo** [comment]
Thanks you guys.  It helped me a lot
