### ISSUE TITLE
BidirectionalAstar: Search exhaustion in 1 direction can cause no route

### ISSUE THREAD

**Issue by mandeepsandhu** [valhalla/valhalla#2926]
When doing bidirectional search, if either of the search direction exhausts itself, it causes the the router to prematurely abort with a no-route error.

Eg: consider this simple map:
```
A---B---C---D---E
```
Assume AB & BC have very low speeds (1kph) while CD & DE are fast (100kph). Also assume that there are access restrictions on AB & BC which would prevent reverse search from expanding into them. Now when bidir astar starts, it will start the expansion from E (because edge costs of AB is very high)...and it continues to expand till it cannot expand further. At this point the fwd search has not yet started & reverse search is exhausted. This will give a route failure even though if we allowed fwd search to continue, it would've succeeded in finding a route.

I'm still trying to recreate this scenario in a gurka test.

**Comment by kevinkreiser** [comment]
Yeah looking over bidir a* it looks to me like what can happen is:

1. we start out searchign from both directions, both flags are true
2. all the lables in one search direction's queue are really highly penalized compared to the other search direction
3. on the second iteration of the main loop we are set to only one direction, the one with the queue with cheaper elements
4. we expand all of those until the queue is empty and then we hit the error that the search is exhausted

The important thing to keep in mind is that there are a few things that can empty the queue on one side of the search:

1. that side of the search is actualy inside of an small component (island) and cant get out. in this case its actually good that we fail the route as soon as possible
2. that side of the search hits either a closure or a not through region and the only way to connect over that region is for the other side of the search to come out of it

What we could do is continue searching the other side of the search that wasnt expanded at all when we exhaust the first side. All we have to do is detect that one is exhausted and the other still has more to go. This will make impossible routes waste more CPU though unless we start tracking the reason why the search was exhausted. In other words we would need to know that if all paths were pruned and none of them were closures or not throughs, then we can immediately terminate the search when its exhausted on that one side because there is still not way for the other side of the search to reach it

**Comment by kevinkreiser** [comment]
i pushed up a branch with an idea of how we might investigate what it would do to attempt to fix the route failures that fall into number 2 above. it fails a unit test so maybe ive got a small mistake there but the idea is pretty simple if you want to investigate further!

**Comment by dnesbitt61** [comment]
If restrictions are properly handled in the reverse direction then shouldn't the reverse search enter into the forward search area and complete the route? Unless there is a real disconnect (which means the route should fail) or one of the thresholds has been met.

**Comment by mandeepsandhu** [comment]
> If restrictions are properly handled in the reverse direction then shouldn't the reverse search enter into the forward search area and complete the route? Unless there is a real disconnect (which means the route should fail) or one of the thresholds has been met.

I _think_ restrictions are handled properly since we pass in the opposing edge when evaluating them in the reverse expansion. Although, I think not_thru edges should not be traversed in the reverse direction, since the previous edge would be open and not_thru pruning would be on. Its off only when starting from (or ending on) a not_thru edge, and that won't be known if we have only expanded from 1 direction. I need to replicate it with a test case though.

**Comment by mandeepsandhu** [comment]
https://github.com/valhalla/valhalla/pull/2936 addresses this issue

**Comment by mandeepsandhu** [comment]
Closed by #2936
