### ISSUE TITLE
Bidirectional astar finds nonoptimal route

### ISSUE THREAD

**Issue by genadz** [valhalla/valhalla#2928]
Bidirectional astar uses the same heuristic function as unidirectional search. In order to find optimal route we shouldn't stop iterations until we reach an edge with **sortcost** that is greater than **full cost** of the best route we found for the moment. But instead of full cost of the best route we uses its sortcost, that's incorrect. A simple example of such behavior was provided here https://github.com/valhalla/valhalla/issues/2884#issuecomment-785251845 - bidirastar found nonoptimal route.

There are 2 possible ways to fix this:
1. use **full cost** instead of **sortcost** in stop criterion;
2. use feasible for bidirastar heuristic function that ensures finding optimal route.

We should try each of them and choose the best one. @kevinkreiser @dnesbitt61 @PureW

**Comment by genadz** [comment]
@danpat I've implemented (https://github.com/valhalla/valhalla/commits/kgv_yet_another_bidir) solution from the article that you proposed https://github.com/valhalla/valhalla/issues/2884#issuecomment-785277797 . The key idea of this article is to detect nonoptimal routes as soon as possible and reject them based on the criterion. There are good news and bad:
*Good*:
- this solutions is really fast, it's slower than current master only by ~8%;

**master**
```
all items: 13632
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.010s	0.051s	0.066s	0.081s	0.103s	0.197s	0.420s	1.449s	3.026s
mean = 0.110
```

**kgv_yet_another_bidir**
```
all items: 13632
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.009s	0.051s	0.065s	0.081s	0.105s	0.205s	0.482s	1.610s	3.042s
mean = 0.119
```


*Bad*:
- we can't use it until we fix **hierarchy limits** logic. The problem here: hard hierarchy limits may prune optimal paths that makes the criterion invalid for some cases. This leads to the fact that the new algorithm can reject optimal paths. (checked for some examples).

@kevinkreiser I'd propose to come back to this optimization as soon as we get rid of hard hierarchy limits.

**Comment by kevinkreiser** [comment]
Removing the hard hierarchy limits logic is a huge change. Its great in that it will allow us to find routes where otherwise we would have had to do a second pass and loosen the limits but its bad in that for most cases it will simply add to the runtime cost and not really change the route. Also removing the `H` from Thor is pretty huge...

I'd be interested to figure out what the order of events are here. Do we want to patch the current version of bidira* to fix the issue with the heuristic and then come to this new implementation with differetn use of heirarchies (maybe it penalizes transitions instead of hard blocks them, so its still hierarchical but isnt a hard cut off? or maybe that leads to sub optimal routes too...).

**Comment by genadz** [comment]
Timings from **master** branch to compare with other solutions:
```
all items: 13632
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.010s	0.051s	0.066s	0.081s	0.103s	0.197s	0.420s	1.449s	3.026s
mean = 0.110
```

To summarize all work done for the moment. I've implemented **3 different solutions**:
1. Fix cost threshold to use **full route cost** instead of **sortcost** (https://github.com/genadz/valhalla/tree/kgv_fix_bidir_cost_thresh). This is the simplest and the slowest one. Average performance drop is about **45%**.
```
all items: 13632
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.009s	0.060s	0.078s	0.097s	0.131s	0.300s	0.789s	2.054s	3.701s
mean = 0.160
```

2. Solution from the [article](https://github.com/valhalla/valhalla/issues/2884#issuecomment-785277797) that @danpat proposed (https://github.com/valhalla/valhalla/tree/kgv_yet_another_bidir). This is the fastest one, average performance drop is about **8%**, but as I mentioned above some route that worked on master were broken because of hard hierarchy limits. So, we can't use this solution right now:
```
all items: 13632
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.009s	0.051s	0.065s	0.081s	0.105s	0.205s	0.482s	1.610s	3.042s
mean = 0.119
```

3. Solution that uses new (balanced) heuristic function (https://github.com/valhalla/valhalla/pull/2889). Average performance drop is about **20%**, but here is the same problem as in 2.: there are many nonoptimal routes (with long detours) because of hierarchy limits logic.
```
all items: 13631
percentiles	10%	50%	60%	70%	80%	90%	95%	99%	100%
response_time	0.009s	0.052s	0.066s	0.082s	0.108s	0.229s	0.574s	1.789s	3.858s
mean = 0.131
```

@kevinkreiser the only option that is acceptable in terms of quality right now is 1. But performance drop, IMHO, too big (45%). So, probably we should look at hierarchy limits logic (if I'm right and this is the root problem not result of some other bug) first and try to fix it

**Comment by kevinkreiser** [comment]
I mean surely the hierarchy limits are already affecting the optimality of the routes in master as htye gut off large swathes of the graph as you get further away from the start/end location. I suppose what is happening in solution 2 above is that we get even more extreme version of this because it implements an additional means of cutting off search space and now we've cut too much off. @genadz I completley agree. It seems the best path forward is to see how we continue solution 2 but maintain the performance benefits (or not lose too much of them) by modifying the means by which we exploit the highway hierarchy. @dnesbitt61 do you have any opinions here?

**Comment by dnesbitt61** [comment]
My opinion:

Trying to find the optimal route over a long distance is an academic exercise but in practical terms I don't think it is that important that long routes are truly optimal. For long routes, the solution should provide a "general" path. Navigation along that path can and should take care of changing local conditions that may produce local detours or shortcuts over roads that may have been removed due to hierarchies. 

If the route is being used without navigation assistance (e.g. a printed route like the old MapQuest days!) then any long route that takes minor roads in the middle of the route seems suspect to me. Without a navigation aid, a driver should take the "easiest" route which means staying on major roads rather than being instructed to use low class roads to potentially save a few seconds.

**Comment by genadz** [comment]
> My opinion:
> 
> Trying to find the optimal route over a long distance is an academic exercise but in practical terms I don't think it is that important that long routes are truly optimal. For long routes, the solution should provide a "general" path. Navigation along that path can and should take care of changing local conditions that may produce local detours or shortcuts over roads that may have been removed due to hierarchies.
> 
> If the route is being used without navigation assistance (e.g. a printed route like the old MapQuest days!) then any long route that takes minor roads in the middle of the route seems suspect to me. Without a navigation aid, a driver should take the "easiest" route which means staying on major roads rather than being instructed to use low class roads to potentially save a few seconds.

I got your point. But, unfortunately, optimality is not the only case affected by hierarchy limits. In some cases in the middle of the route we should take a low level road, but instead of that we continue moving on highway and get long detour. @dnesbitt61 do you have any thoughts about this case ? my idea (in progress right now) is instead of fixing hierarchy limits we can analyze graph and probably "move" low level road to the highest class if this road connects two high level roads, does it make sense ?

**Comment by dnesbitt61** [comment]
Are you talking about updating hierarchies at runtime or at data generation time? I'm not sure how you could do this at runtime due to the tight coupling of hierarchies and shortcut generation. I remember some discussions in the early days of Valhalla around someday doing some kind of road class "promotion" during data generation to "fix" the road class assignments. This seems difficult (so good luck in your investigation!). The real problem is OSM has a single tag indicating the highway type and no real tag indicating the importance of a road for routing. Commercial data sets for navigation generally have a "network class" (or similar term) indicating the routing importance with guaranteed connectivity at each network class.

**Comment by genadz** [comment]
> Are you talking about updating hierarchies at runtime or at data generation time? I'm not sure how you could do this at runtime due to the tight coupling of hierarchies and shortcut generation. I remember some discussions in the early days of Valhalla around someday doing some kind of road class "promotion" during data generation to "fix" the road class assignments. This seems difficult (so good luck in your investigation!). The real problem is OSM has a single tag indicating the highway type and no real tag indicating the importance of a road for routing. Commercial data sets for navigation generally have a "network class" (or similar term) indicating the routing importance with guaranteed connectivity at each network class.

I meant updating hierarchies at data generation time. Interesting idea about "promotion" roads, but seems difficult, as you noticed.

**Comment by genadz** [comment]
@kevinkreiser @dnesbitt61 looks like "fixing graph" this is the only option. because when I commented these 2 lines https://github.com/valhalla/valhalla/blob/master/src/thor/bidirectional_astar.cc#L202 and https://github.com/valhalla/valhalla/blob/master/src/thor/bidirectional_astar.cc#L418 where we just read low level tiles but skip expanding edges, performance decreased by ~600%.

**Comment by dnesbitt61** [comment]
yea, the whole idea of hierarchies is to avoid ever reading low level tiles except near the origin and destination.

**Comment by kevinkreiser** [comment]
yeah. so the idea of promoting edges at graph building time was something we did talk about long ago. i think this idea can work to mitigate non-optimalness in many cases (the basic cases) but because we have dynamic costing we allow the user to choose what is optimal to them. this means that whatever costing we use to figure out connectivity issues due to hierarchy culling and upclass those roads (to move them into another hierarchy) will not always allow for optimal routes for every permutation of costing.

you can imagine a costing option that favors only one thing, how scenic a route is. i could see that this type of option would probably want to stay on low class roads a lot even when it is not needed to get from one point to another.

in any case, what about the "yet another bidir" paper, when you disable hierarchy culling in that implementation, how does the performance look. i had thought the paper said his heuristic did a better job at bounding the search but maybe i misread that

**Comment by genadz** [comment]
@kevinkreiser algorithm from paper starts to prune edges only after first connection was found. Before that this is the same as current. So, it means that without hierarchy limits this will be extremely slow

**Comment by genadz** [comment]
was resolved here https://github.com/valhalla/valhalla/pull/3257
