### ISSUE TITLE
dockerfile-run references wrong dockerfile-build image

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#2930]
In https://github.com/valhalla/valhalla/blob/83de9845c96556f13fded4905172567744867933/docker/Dockerfile-run#L3

it's referencing the `3.1.0` snapshot, rather than `latest`, but `latest` is what is building on circle, and probably soon breaking the final image. Nothing to do with #2929, just realized it when building locally. I'll fix that in the same PR.

**Comment by kevinkreiser** [comment]
its on purpose. its kind of a chicken and egg thing. the main issue is that we didnt want to actually do a docker build every time someone pushed. isntead we wanted it just on merge to master, which is why #2929 didnt show up until we merged (sorry for the gotcha).

to me, i think when we tag we should tag and push the tagged builder, and tag the runner and push the tagged runner, and for latest i guess we should do the same. but the main problem remains. if you want to PR something that changes build but we dont actually build the runner from it how do we know it works. the simple solution is always build the builder and runner containers for every pr but that is quite heavy.

@PureW have you got any opinions on this?

**Comment by nilsnolde** [comment]
Yeah, I kinda see what you're doing and sort of why.. You just build the builder image on every push (I guess to check it's working?), but only push it to dockerhub (and only build the runner image)  when it's master or tagged. The downside is that a branch's circle test have their base image pointed at master's builder image, not their own. I think that's fine.

I'd just use build arguments for the runner image in the from clause, e.g. 
```
ARG DOCKER_TAG=latest
FROM valhalla/valhalla:build-${DOCKER_TAG}
```
and then add either `master` or `CIRCLE_TAG` as build arg in CI. Otherwise you'll have to remember to update the minor version in the dockerfile and anyone who ever pulls the runner image will be based on the `3.1.0` builder image (I guess not a problem if you publish minor valhalla versions for every dependency change..).. 

I also don't see how the tagged images are built in circle ci before pushing them.. Hmm, getting late, maybe I'm a little delusional already..

**Comment by PureW** [comment]
Yes, I struggled with this for some time before settling on this somewhat roundabout and annoying solution. In the past I've used Codeship for CI which handles this so much better than CircleCi. On codeship it was easy to have each run build the provided dockerfile, run tests in that dockerfile and publish when successful, all the while having great caching of docker layers which made it all snappy.

This sounds like an ad for Codeship I guess, but CircleCi is really weak in comparison when aiming for that workflow.

https://github.com/valhalla/valhalla/pull/2105 has more context around this.

**Comment by nilsnolde** [comment]
Oh yeah, I remember that long thread. Guess I understood and really don't wanna stir that up again.. As long as you're aware that each slight dependency change would mean a valhalla version (which it should anyways, but given the release history in the past 2 years..;)) and a manual update of the builder's Dockerfile, I'm good:)
