### ISSUE TITLE
Exceeding max. edge length

### ISSUE THREAD

**Issue by canadaka** [valhalla/valhalla#2948]
I am trying to run `valhalla_build_tiles` on some custom data I have, a mix of our own linestrings and OSM ways. I am getting the following error:
```
2021/03/17 18:42:40.129585 [ERROR] Exceeding max. edge length: 38531677
2021/03/17 18:42:40.129866 [ERROR] Failed tile 2/592870/0: DirectedEdgeBuilder: exceeded maximum edge length
```

I am stumped why this is happening, there are no ways greater than 2000 nodes in the data all ways are `ST_IsValid`, nothing over 80km in length.

well below the "[kMaxEdgeLength](https://github.com/valhalla/valhalla/blob/14bbbe00bc07b6f647660f02199641d9a73ce326/valhalla/baldr/graphconstants.h#L176)" of 16,777,215 meters

What makes this problem even stranger is I am merging multiple .OSM files into a single PBF. If I convert either OSM to PBF without merging they build independently fine. But when merged I get the "Exceeding max. edge length" error.

`.\osmosis\bin\osmosis.bat --rx canada-west.osm --rx canada-east.osm --merge --write-pbf canada.pbf omitmetadata=true`

Even more strange, if I omit the OSM way data in those files and just include our data, the same command above works. But soon as I include the OSM data it fails.

Maybe someone has some insight or ideas on this? It just seems very strange given either .OSM file converted to PBF works fine, but when merged it fails. both files have unique sequential WAY IDs. Where one files IDs end, the next starts.

**Comment by kevinkreiser** [comment]
if i had to guess i would look into what `osmosis` does when there are id collisions between your pbfs that you are merging. imagine you have a way in northern greenland and it references the nodeid 123 in one .osm file but then in the other .osm file you have that node at mcmurdo station in antarctica that is nodeid 123 in that dataset. 

using `osmium` (a different tool) you can actually renumber the items in your osm format data so that one files id space starts at 0 up to N, and then the next files id space starts at N+1 to M, and so on. this way you can avoid any id collisions.

again, this is just my guess, let us know what you find out!

**Comment by canadaka** [comment]
Thanks for the reply, right after posted I thought about this already. My way IDS are sequential, but the node id's could have collisions. Looking into that now.

I didn't know that about osmium, that is a good tip.
