### ISSUE TITLE
Isochrone: isochrone visits edges incorrectly

### ISSUE THREAD

**Issue by merkispavel** [valhalla/valhalla#2973]
1. Post visiting strategy. Isochrone [overrides](https://github.com/valhalla/valhalla/blob/master/src/thor/isochrone.cc#L277) `ExpandingNode` method so once the node is popped from the queue we look at the edge `(prev_node, node)` and do isochrone specific logic. 
2. Stop expansion. The prev.secs() is [used](https://github.com/valhalla/valhalla/blob/master/src/thor/isochrone.cc#L301) to check whether this edge is interested to us.

(2) looks ok. However when it's combined with (1) - they do evil things.

### Example
Say we have contour 5 min.

Queue elements:
1. prev = 4 min, current = 8 min
2. prev = 6 min, current = 7 min

(2) node(i.e current node) has less ETA(~ less cost) so it is popped first. It triggers stop expansion because `prev.secs = 6min > contour = 5 min`. **BUT** there is another (4min, 8min) edge which is interested to us because there's a segment (4min, 5min) that lie within the contour

### Possible solutions
Change visiting strategy post -> pre. So we can visit the edge at the moment we add it to the queue.

### Impact
Underestimated isochrone region. There might be(the change is high) reachable regions that isochrone response don't include

**Comment by kevinkreiser** [comment]
@merkispavel im pretty sure this is a known issue. @dnesbitt61 wrote the original implementation and there we added (and still do add) an extra bit of expansion (a buffer) to stop us from quitting too early. Your suggestion makes sense to me. We can add another pure virtual method (`EnquingEdge` or something) that is called when a edge is added to the queue and switch isochrones to use that method when updating the grid. This will cost more in one sense because we arent "drawing" only the popped edges but all pushed ones, but we'll be able to remove that buffer and quit when the queue is exhausted rather than when we hit a threshhold (because we'll prun paths that are outside of the contour)

**Comment by merkispavel** [comment]
I spend some time thinking about it ^. We probably don't need another visitor method. We can prune edge based on its start node time/distance https://github.com/valhalla/valhalla/pull/2990
