### ISSUE TITLE
Local Valhalla with MapBox

### ISSUE THREAD

**Issue by bmarcco** [valhalla/valhalla#3001]
I create an application for navigation using Ionic (Angular), OpenStreetMap and a local Valhalla server located on Ubuntu. Is there a chance that Mapbox GL is using an API call from a local Valhalla server and I get a view similar to [this](https://ibb.co/z7QjJS5). Thanks in advance for your reply.

**Comment by danpat** [comment]
@bmarcco That screenshot shows the UI constructed by the Mapbox Navigation SDK.  You can probably re-create _some_ parts of it, but quite a few pieces are not possible to re-construct with the open source Valhalla project.

(note: I work for Mapbox).

**Comment by bmarcco** [comment]
Thanks for your reply. Is there any open source javascript library that can be integrated with Valhalla, and I get navigation with the camera. Something like a Mapbox Navigation SDK?

**Comment by danpat** [comment]
There is an old fork of the Mapbox Nav SDK by GraphHopper here: https://github.com/maplibre/maplibre-navigation-android

But it is now quite old and hasn't been modified since the fork from what I can see.  I'm also not sure what you'd need to do to make it work with Valhalla.

I'm not aware of any other open source things like this.  You may be able to take one of the other open source navigation apps and tear apart what they've implemented, but there's nothing simple and out-of-the-box that I'm aware of.

**Comment by nilsnolde** [comment]
2 years later still not, though there is currently some momentum at maplibre (can't find it right now). Obviously it'd be very interesting to have a portable open-source navigation library.
