### ISSUE TITLE
Doesn't route through footpath bridge for bicycles 

### ISSUE THREAD

**Issue by cranik** [valhalla/valhalla#3100]
<img width="1146" alt="Screenshot 2021-05-25 at 16 12 08" src="https://user-images.githubusercontent.com/5064130/119513166-436cec80-bd74-11eb-9dc4-411303ffd7b6.png">
<img width="370" alt="Screenshot 2021-05-25 at 16 16 15" src="https://user-images.githubusercontent.com/5064130/119513486-8fb82c80-bd74-11eb-86f3-ce3e3ef7149a.png">

Should be like in OSRM:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=55.66805%2C37.83704%3B55.66812%2C37.83925#map=19/55.66806/37.83815

**Comment by kevinkreiser** [comment]
It looks like you only just added bike access to it an hour ago :smile: 

![image](https://user-images.githubusercontent.com/697548/119514791-50bdb300-bd43-11eb-9426-c66d4549bae2.png)

@gknisely what are the rules for assuming bike access on pedestrian ways in Belarus? i forget if that is a country specific override or not

**Comment by dnesbitt61** [comment]
https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions
seems like this should allow bicycles on footway by default.

**Comment by kevinkreiser** [comment]
excellent link, i see it:
![image](https://user-images.githubusercontent.com/697548/119517153-5d430b00-bd45-11eb-8dd6-e5b540b7d055.png)

**Comment by gknisely** [comment]
Yes, we have this override already in the code/admin db, but something is not correct.  I will have to dig into this issue.

**Comment by cranik** [comment]
Hi, thanks for attention to this issue. But this is route example in Moscow, Russia. not Belarus if it essential.

**Comment by cranik** [comment]
>>It looks like you only just added bike access to it an hour ago 😄

yes, I did, but this doesn't affect the issue with other similar foot bridges:


https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=55.65903%2C37.83912%3B55.65905%2C37.84006#map=19/55.65891/37.83960

<img width="1089" alt="Screenshot 2021-05-25 at 17 28 52" src="https://user-images.githubusercontent.com/5064130/119525669-fc382900-bd7e-11eb-9baa-28470716e650.png">

**Comment by dnesbitt61** [comment]
Russia seems to not allow bicycle access by default on highway=footway. Likely need to explicitly add bicycle=yes tags in these cases.

**Comment by gknisely** [comment]
@dnesbitt61 is correct.  @cranik you need to added it to all the other way too.  https://www.openstreetmap.org/way/46770226#map=19/55.66753/37.83689

**Comment by gknisely** [comment]
@cranik please reopen if need be.

**Comment by molind** [comment]
After discussion with Russian OSM community in https://t.me/ruosm we concluded that bicycle should use cycleway. If there is no cycleway it should use footway. And if there is no cycleway or footway, then right side of the road should be used. Does it makes sense? Could we add some penalty to the footway, comparing to the cycleway and some bigger penalty to the roads, to make this logic work?

**Comment by dnesbitt61** [comment]
No - bicycle routing should follow the rules of each country and where cycling is not allowed on footways it should not take them. Adding penalties and bringing in footways would decrease the performance of bicycle routing, which is already pretty slow since there is no optimization done as there is for driving routes. I am firmly opposed to allowing cycling on footways unless it is the default behavior for a country or if there are bicycle=yes tags that explicitly allow bicycles. This is a slippery slope - what is next - bicycles on sidewalks?!  I have also had others who want to allow cycle routes to go the wrong way down oneway roads (with explicit dismount instructions) but I also oppose that kind of logic.

**Comment by kevinkreiser** [comment]
Yeah I think we should follow the rules for Russia: https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#Russia

If those rules in that table are incorrect, we should suggest a change to that table get it approved and then change the code in valhalla to match it.

**Comment by molind** [comment]
![Screenshot 2021-05-27 at 11 09 59](https://user-images.githubusercontent.com/102496/119799236-2e12d200-bedc-11eb-84f5-64a20091e433.png)
No one talking about breaking the rules. There is a yellow zone in the table and valhalla treat it like `No`, while OSRM treat it like `yes`. :)
This is the rules for Russia. Section about bicycles and mopeds: http://www.pdd24.com/pdd/pdd24
https://deepl.com produces readable english version:

24.1 Cyclists over 14 years of age must use a cycle lane, cycle-pedestrian lane or cycle lane.
24.2 Cyclists over the age of 14 shall be allowed to ride
on the right-hand edge of the carriageway - in the following cases:

- there is no cycle lane, cycle-pedestrian path or cycle lane or it is not possible to use them;
- the overall width of a bicycle, its trailer or its load exceeds 1 m;
- cyclists ride in columns;
- by the roadside - if there is no bicycle lane, pedestrian lane, bicycle lane, or no possibility to use these or the right edge of the carriageway;

on the pavement or walkway - in the following cases:

- there is no bicycle lane, bicycle-pedestrian lane, bicycle lane or there is no possibility to use them, or the right edge of the carriageway or the kerb;
- the cyclist accompanies a cyclist under the age of 14 or carries a child under the age of 7 on an additional seat, in a wheelchair or in a trailer designed for use with a bicycle.

24.3 Cyclists aged 7 to 14 years old must ride only on pavements, footpaths, bicycle paths and cycle paths, as well as within pedestrian zones.
24.4 Cyclists under the age of 7 must only use pavements, footpaths and cycle-pedestrian paths (on the side for pedestrian traffic), as well as within pedestrian zones.

According the rules there is some cases when movement on footway is allowed. And there is no universal answer 'yes' or 'no'. That's why it's yellow in the table. I think there should be an option in valhalla, that will allow to use footway in bicycle routes.

And even cell footway + footway=crossing that is 'no' in the table is not denied for bicyclists. But they should dismount if there are no bicycle crossing markings.

**Comment by dnesbitt61** [comment]
Not sure how that all might be coded into sqlite rules (at least I think that is how country dependent access conditions are done - need @gknisely to chime in on that). It seems that perhaps treating this like a dismount tag might be what is best. That will set the speed used in costing to a walking speed so if there are other paths near where cycling is allowed it will likely take them.

**Comment by kevinkreiser** [comment]
yeah that yellow spot in the table has a description below which made zero sense to me:

>  Vehicles of road's and communal's stuff allowed. Vehicles, which move cargo to objects, which located directly close to footway, allowed, if they use shortest way. Moving of vehicles should be safe[9].

I would suggest, again, that we propose a change to the wiki and get it updated so that a person reading it would have a clue that bikes could use footways to some circumstances degree

**Comment by molind** [comment]
@kevinkreiser zero sense for me too. I'll ping this issue again, when table will be updated according to the rules.
