### ISSUE TITLE
Bridleways with foot=true tag results in edges without bicycle access 

### ISSUE THREAD

**Issue by davidjcohen** [valhalla/valhalla#3135]
When an OSM way (in the UK) has the following tags:

highway=bridleway
foot=true

e.g. https://www.openstreetmap.org/way/33114857

we lose bicycle access

see http://localhost:8002/locate?json={"verbose":true,"locations":[{"lat": 53.5992164, "lon": -1.5830084}],"costing":"pedestrian","directions_options":{"units":"miles"}}

Is this the intended behaviour?

It looks like lua/graph.lua sets the "use" to pedestrian in this case, and we don't get the defaults from the admin database.

Thanks in advance

**Comment by dnesbitt61** [comment]
interesting - especially since this is part of a cycling route (relation)

**Comment by kungfu303** [comment]
Having a similar issue with a pedestrian bike/walk bridge in Providence, RI. [Here](https://www.openstreetmap.org/way/609950799) it is marked highway=cycleway, but it has foot=designated. This seems to be removing it completely from bicycle access. What's a resolution (maybe an override as mentioned [in this issue ](https://github.com/valhalla/valhalla/issues/3705)?

**Comment by kungfu303** [comment]
Update: I'll try modifying graph.lua with some extra conditionals ([similar to this](https://github.com/valhalla/valhalla/blob/master/lua/graph.lua#L1813)) at the end so that it checks for bicycle=designated and foot=designated, and ensures that it does have bike_forward access. If there's a better solution, feel free to share

**Comment by kevinkreiser** [comment]
@gknisely would be better to advise here but what you're saying is where I would look first

**Comment by kungfu303** [comment]
Thanks! Also quick question on recompiling after modifying the graph.lua. It says in one of the READMEs that if you modify the lua file, you'd be able to build valhalla without needing to remake the tiles. I tried running from the `valhalla_build_extract -c valhalla.json -v` command, but it seems to not have taken the new graph.lua into account.

**Comment by gknisely** [comment]
This should be working correctly as the user added the bicycle access tags.  This should override any country overrides in the code.  It does look like this is happening for pedestrian access, but it is removing bicycle access for some reason.  I will have to dig more.   @kungfu303 you need to make sure you have a admin db in use for country overrides.  Do you have it created?  Also, in order to build tiles, you use `./valhalla_build_tiles -c ../../conf/valhalla.conf ../Path_to_your_pbf/your.pbf`

**Comment by kungfu303** [comment]
Hey @gknisely, thank you so much. My team and I figured it out - right before you enter the pedestrian bridge from the right, there are two footways. If you're in bicycle costing, footway_forward = "false". Thus, it's not routing that way because there was never bike access - only footways to get onto the bridge from that side. 

We'll play around a bit with the lua and can PR if we come up with a solution. For now, I think I'm set (no need for the admin db)

**Comment by gknisely** [comment]
@kungfu303 actually if you look at this [access chart](https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions#United_Kingdom) for the UK you can see that bicycles are allowed by default.  This is a bug and should be address in code.  I am going to fix this now.

**Comment by gknisely** [comment]
@kungfu303 looks like the bug was only related to Scotland and Wales.  However, I added a test showing that the bridges in question needs to have bicycle access added.  (i.e., https://www.openstreetmap.org/way/33114856 and https://www.openstreetmap.org/way/147854243) Basically, if a user adds any access tags to a way, we will not override this tag with the country defaults.  We assume that if a user takes the time to override an access then they are certain that the only access is what they set for the way.  So for your example, foot is only set.  Please add `bicycle=yes` to both of these bridges or remove `foot=yes`in order to fix access.  If you remove `foot=yes` then the country defaults will be reactivated.  Here is the same [test](https://github.com/valhalla/valhalla/pull/3746/files#diff-087ea29b525b947493034ef35d936b8ef6e62e22a71e16291d58df4ca0ed928f).
