### ISSUE TITLE
readme azure badge has "never built" text

### ISSUE THREAD

**Issue by matkoniecz** [valhalla/valhalla#3161]
See https://github.com/valhalla/valhalla#build-status
![screen](https://user-images.githubusercontent.com/899988/122916140-db9ec700-d35c-11eb-93d0-0b9686d24782.png)

it seems to be incorrect

sadly I have no idea how to fix it

**Comment by kevinkreiser** [comment]
@matkoniecz no it is correct. at the moment macos builds are failing even though the linux ones arent. to fix it you might try looking into fixing the macos builds for us. we have another issue for that though

**Comment by kevinkreiser** [comment]
oh i see. yeah we use github actions to build windows now. i think we should be able to update it

**Comment by nilsnolde** [comment]
> yeah we use github actions to build windows now.

that’s news 😄you maybe confuse it with mingw64? Though that’s disabled since a while.. reminds me: should I try again or it’s too annoying for you?

Wouldn’t be surprised if the badge issue is an azure-side problem..

**Comment by kevinkreiser** [comment]
@nilsnolde sorry i think the lines are blurring, if you look at the builds it show up like they do for github actions though they run with azure: 

![image](https://user-images.githubusercontent.com/697548/122988212-7b655080-d36f-11eb-9c39-2f08aaa3018f.png)


this is probably because microsoft owns github but i thought maybe the badge could be gotten in the same way we get other actions/checks badges? or maybe we still have to get from azure. sorry for the confusion im creating here :frowning_face:

**Comment by nilsnolde** [comment]
AFAIU that’s simply the way GitHub decided to display the Azure CI stuff (and yeah probably bcs they’re part of it now), but the actual CI is not GitHub Actions, it’s still MS Azure. You also have to go there to see any CI logs. 

I wanted to port the azure one to GitHub actions a long time ago and continue your earlier quest of porting all builds, but somehow other stuff always got in the way😅

anyways, just wanted to clear that up:)
