### ISSUE TITLE
Reduce Boost Usage to Header-Only and Vendor Whatever Version We Like

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#3220]
a while ago we made a big push to reduce the dependencies, particularly boost, required to build valhalla in #1465. at this moment in time we use lots of header only bits of boost but only a tiny handful (maybe only `program_options`) of boost that need linking and actually prebuild library. in order to reduce the possibility that valhalla is not buildable on a target platform we can bring our own version of boost and just the bits that we need. to do that we need to find and stomp out any boost linking that we are doing. there is one catch though, we do expose boost in our public apis which means if we vendor it we need it to not conflict with any system boost that is installed. that means it has to live under the same include path where we install our own headers. cmake will handle all of that for us if we do the work right but still its worth noting that vendoring it means even to the install destination.

@nilsnolde what do you think about this?

**Comment by nilsnolde** [comment]
totally @kevinkreiser I thought the same thing (and probably would've been less work than building boost on mingw64 back in the days, but you know..)..

I'm almost 100% sure you're right, it's only program_options we use these days to link. Since we ideally don't roll our own, how about this one: https://github.com/jarro2783/cxxopts? header-only, well maintained and compatible with all (realistic) build chains it seems..

**Comment by nilsnolde** [comment]
I can take care of re-writing the command opts over the next weeks as initial step and pull in the above (or other) lib. Would be great if someone could jump in with the cmake leg work after.

**Comment by kevinkreiser** [comment]
@nilsnolde yeah i looked at actually porting to that last time we were discussing this but ive lost the branch at this point, best to do it fresh anyway :+1:

**Comment by kevinkreiser** [comment]
i can start a branch with the cmake work for sure
