### ISSUE TITLE
Using modified OSM data for routing

### ISSUE THREAD

**Issue by liquidsun** [valhalla/valhalla#3313]
Hello!
Is there any way to use modified OSM data? Custom data converted to OSM schema?
I am getting an error "Detected unsorted input data" during my custom .osm.pbf file parsing.
Thanks!

**Comment by nilsnolde** [comment]
it does work out of the box, I also did it many times. your input PBF needs to be sorted after type and within a type again sorted after OSM ID. it's much harder to do it that way though, so you could continue like this and then use a `osmium sort` on it: https://docs.osmcode.org/osmium/latest/osmium-sort.html

more of a discussion topic rather than an issue though

**Comment by liquidsun** [comment]
Thanks for the answer, working now!

Yeah, sorry for posting this under issues
