### ISSUE TITLE
 How can i make a connection between my Valhala Server and my map?

### ISSUE THREAD

**Issue by phoenixproject** [valhalla/valhalla#3382]
Hello!

I use Leaflet Route Machine with OSRM (Open Source Route Machine) and my connection this is

```
L.Routing.control({
        router: L.Routing.osrmv1({
            serviceUrl: 'http://192.168.0.33:5000/route/v1'
        })
}).addTo(map);
```
    
My Valhalla Server is **http://192.168.0.33:8002/routes** on Debian 11.

How can i make a connection between my Valhalla Server and my map?

Best Regards,

**Comment by kevinkreiser** [comment]
it should be `/route` not `/routes` so that is one thing though your main problem is going to be that we dont support parsing osrm style requests. so while we do support osrm style response format (just add `format=osrm`) you would need to do some work to make a valhalla style request. once upon a time (a couple major versions ago of valhalla) we had an lrm plugin for valhalla, it is mentioned in the readme here: https://github.com/perliedman/leaflet-routing-machine

Indeed we still have some form of that implementation here: https://github.com/valhalla/demos/blob/gh-pages/routing/js/lrm/L.Routing.Mapzen.js

If I were you though I might try to make something new directly inside of leaflet. I can say that our plugin is not maintained and the leaflet routing machine is also not maintained. If you take a bit of time to understand the response format you can easily add routing support to leaflet without much effort. We have already a minimal example right here: https://github.com/valhalla/demos/blob/gh-pages/routing/simple.html

**Comment by nilsnolde** [comment]
would be nice if someone stepped up to at least provide a npm client for valhalla.. maybe we'll look into that in the next months, would make sense for the new global server we soon set up with FOSSGIS when we finally add it to the frontend (fossgis.de and/or osm.org).

@phoenixproject there's a nice js package for openrouteservice which @TimMcCauley created years ago and is still being very well maintained (and on npm): https://github.com/GIScience/openrouteservice-js

no direct leaflet plugin, but well abstracted so it's be fairly easy to integrate into a leaflet map. it'd be mostly mechanical work to take that and change it to communicate with a valhalla json api instead of ORS.

**Comment by phoenixproject** [comment]
> 
> 
> it should be `/route` not `/routes` so that is one thing though your main problem is going to be that we dont support parsing osrm style requests. so while we do support osrm style response format (just add `format=osrm`) you would need to do some work to make a valhalla style request. once upon a time (a couple major versions ago of valhalla) we had an lrm plugin for valhalla, it is mentioned in the readme here: https://github.com/perliedman/leaflet-routing-machine
> 
> Indeed we still have some form of that implementation here: https://github.com/valhalla/demos/blob/gh-pages/routing/js/lrm/L.Routing.Mapzen.js
> 
> If I were you though I might try to make something new directly inside of leaflet. I can say that our plugin is not maintained and the leaflet routing machine is also not maintained. If you take a bit of time to understand the response format you can easily add routing support to leaflet without much effort. We have already a minimal example right here: https://github.com/valhalla/demos/blob/gh-pages/routing/simple.html



> 
> 
> it should be `/route` not `/routes` so that is one thing though your main problem is going to be that we dont support parsing osrm style requests. so while we do support osrm style response format (just add `format=osrm`) you would need to do some work to make a valhalla style request. once upon a time (a couple major versions ago of valhalla) we had an lrm plugin for valhalla, it is mentioned in the readme here: https://github.com/perliedman/leaflet-routing-machine
> 
> Indeed we still have some form of that implementation here: https://github.com/valhalla/demos/blob/gh-pages/routing/js/lrm/L.Routing.Mapzen.js
> 
> If I were you though I might try to make something new directly inside of leaflet. I can say that our plugin is not maintained and the leaflet routing machine is also not maintained. If you take a bit of time to understand the response format you can easily add routing support to leaflet without much effort. We have already a minimal example right here: https://github.com/valhalla/demos/blob/gh-pages/routing/simple.html

Hi!

Hello my friend.

I've already been reading this example. I want to read all the OSRM and Valhalla documentation, but I'm not sure I can do this quickly.

Thanks to reply

**Comment by phoenixproject** [comment]
> 
> 
> would be nice if someone stepped up to at least provide a npm client for valhalla.. maybe we'll look into that in the next months, would make sense for the new global server we soon set up with FOSSGIS when we finally add it to the frontend (fossgis.de and/or osm.org).
> 
> @phoenixproject there's a nice js package for openrouteservice which @TimMcCauley created years ago and is still being very well maintained (and on npm): https://github.com/GIScience/openrouteservice-js
> 
> no direct leaflet plugin, but well abstracted so it's fairly easy to integrate into a leaflet map. it'd be mostly mechanical work to take that and change it to communicate with a valhalla json api instead of ORS.

Dear @nilsnolde 

I will read carefully about openrouteservice. I really liked the result at https://maps.openrouteservice.org.

Thanks.
