### ISSUE TITLE
Can't build Valhalla with geos-3.10.x

### ISSUE THREAD

**Issue by weigangd** [valhalla/valhalla#3388]
Hello,
I tried to build Valhalla on macOS Monterey.  It seems that the new geos version has changed something in it's API. The build produces the following error:
`Undefined symbols for architecture x84_64: geos::geom::Coordinate::Coordinate(), ....`
I could fix this on my system by building geos-3.9.3 from source and install it.

Homebrew by default installs geos-3.10.1 at the moment and it is not possible to install older versions of geos.

**Comment by danpat** [comment]
The issue is that the macOS binaries of `geos` you install with Homebrew were built with `-DGEOS_INLINE` - this means that some of the functions (like the constructor for `Coordinate()`) are not present in the binaries, only in the Geos headers.

Unfortunately in the headers, those functions are wrapped in `#ifdef`, so by default, they're not visible.

The fix is to build Valhalla with:

```
CXXFLAGS=-DGEOS_INLINE cmake ..
```

but honestly I think this is pretty messed up.  `geos-config` should be emitting the `-DGEOS_INLINE` to match how the binaries were built on that system, but it is not.

I haven't looked at how this issue is solved on other platforms that distribute `geos` binaries - maybe it is not, or maybe by default the binaries aren't built with `-DGEOS_INLINE`, so it works by luck.

3.10 of geos _switched_ the default from not inlining to inlining, so I suspect this issue is going to come up again on other platforms as they update to 3.10.

**Comment by nilsnolde** [comment]
Should be solved by now with geos 3.11? Best open a new one if not.
