### ISSUE TITLE
Missing edges in Map Matching service API

### ISSUE THREAD

**Issue by khchin93** [valhalla/valhalla#3392]
By making `POST` request to endpoint `/trace_attribute`. the returned edges is not complete.

For example:
Making request A to `/trace_attributes` with following body content 
``` json
{
    "costing": "auto",
    "search_radius": 20,
    "shape_match": "map_snap",
    "filters": {
        "attributes": [
            "edge.id"
        ],
        "action": "include"
    },
    "encoded_polyline": "_`jvDcowu`E^~}@I|k@Ht|@_CbXwHp`@mYdf@mYnUmQvKc[vLyd@tFqkEi@"
}
```
Response
``` json
{
    "edges": [
        {
            "id": 1111490577120
        },
        {
            "id": 1645106709216
        },
        {
            "id": 1644603392736
        },
        {
            "id": 1315535078112
        },
        {
            "id": 1365363409632
        },
        {
            "id": 1315602186976
        },
        {
            "id": 1245037216480
        },
        {
            "id": 1316038394592
        }
    ],
    "alternate_paths": []
}
```

Making request B to `/locate` with following body content
``` json
{
    "verbose": true,
    "locations": [
        {
            "lat": 3.004803,
            "lon": 101.556007
        }
    ]
}
```
Response: 
2 edges with edge_id : `1315568632544` and `1644603392736`

Comparing the response of both request, only the 2nd edge_id (1644603392736) is included but not the 1st (1315568632544). Expecting all the edges along encoded_polyline is included in the Map Matching service API. 

What is the reason of having multiple edges (same shape) in locate API but only part of them is included in the route_attribute API?

**Comment by nilsnolde** [comment]
that's because most OSM road segments actually consist of 2 directed edges (for both directions). but when you call `/trace_attributes` it will only return the edge it actually matched to the road network from your polyline input, bcs the route only uses one directed edge (unless your polyline also includes a return on the other street side). the `/locate` action matches both directed edges by default, unless you tell it to filter by heading, road_class or others: https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#locations.

**Comment by nilsnolde** [comment]
I'll leave it open until you could confirm. you can look at the verbose output of the locate call, you should see the exact same shape twice and somewhere an attribute `forward: true/false`

**Comment by nilsnolde** [comment]
and we think there's a bug there as well in /locate, where heading and road_class filters don't play well together. we'll look into that more soon, for now we solved it client-side.

**Comment by kevinkreiser** [comment]
yeah @nilsnolde is right. our graph is a directed graph. which means any edge between two nodes in the graph has two directions. the polyline shape input is directional, meaning the order of the points in the linestring matter. indeed the map matching will return only the direction of the edge that matchs the direction of the shpe.

with respect to the locate service, it returns the same shape for both edges simply because the edges share the same shape. our data model is such that one direction of the edge use the shape in the forward direction and one uses it in the reverse. you will notice that if you look at the `forward` property of the edge. one edge will be true and one will be false.

**Comment by khchin93** [comment]
Thanks @nilsnolde for the highlight of the `forward` flag, I wasn't aware of the flag before that. 

If the `shape` property in `/locate` response can be directional, it might be more helpful, but I still can reverse it since the `forward` property is provided. Anyway, thanks @kevinkreiser for the detailed explaination. It's super helpful!
