### ISSUE TITLE
Traffic tiles updates

### ISSUE THREAD

**Issue by mesozoic-drones** [valhalla/valhalla#3414]
Hello! I have a question about the [traffic-influenced routing concept.](https://github.com/valhalla/valhalla/blob/master/docs/thor/simple_traffic.md)

What is the mechanism to re-read updated tar with traffic tiles inside valhalla_service? Valhalla calls memory map for traffic tiles. But how does it update overwritten tiles? For example traffic tiles are updated by some daemon every 5 minutes. How does valhalla pick up the changes?

**Comment by nilsnolde** [comment]
we're just going through the process ourselves, so I can share a bit from what I understood so far:

valhalla does not update the traffic tiles, that needs to be done by an external process which writes directly into the tar. valhalla then reads the changes on-the-fly as everything around traffic tiles is declared `volatile` and yeah it's memory mapped as you said. so the challenge is really to set up the feeder architecture: pulling live traffic data, possibly converting the info to valhalla internal `GraphId`s after possibly matching the traffic source geometries to the graph, to then update the edge infos in the traffic tile tar. it's a pretty involved process, depending on your traffic source, very involved! we're currently working with tomtom data and it was somewhat a pita. it's consequently also not really a detailed recipe I'd like to (and actually can't contractually) share at the moment. but the info should be enough to nudge really really interested people in the right direction.

**Comment by kevinkreiser** [comment]
> What is the mechanism to re-read updated tar with traffic tiles inside valhalla_service

that is automatic, its how shared memory (ie the memory map) works. any threads or processes that have access to the same shared memory map will see the changes each other make. because we were careful to make the size of the structures in the traffic tiles 64bits (the read width of modern processors) we dont have any race conditions either (32bit platforms beware)

**Comment by mesozoic-drones** [comment]
@nilsnolde Thank you for detailed answer! 

My question was particularly about the "valhalla then reads the changes **on-the-fly**" part. I don't understand why reading on-the-fly is safe. 

```TrafficTile``` has volatile pointers to memory mapped block of memory (the ```memory_``` private member):
```C++
  volatile TrafficTileHeader* header;
  volatile TrafficSpeed* speeds;
```

But what happens if some process updates traffic tiles while valhalla uses data inside these tiles? Isn't it dangerous? Can  it potentially lead to reading corrupted data? 

So the main question is: don't we need to ensure the safety of access to the shared region somehow? All we have is mmap and volatile pointers to its regions. But I've found no documentation or manuals explicitly saying it is a safe, common, OS- and FS-independent practice.

**Comment by mesozoic-drones** [comment]
Or does volatile guarantee that every use of  ```header``` and  ```speeds ``` will force a new read so data will never be corrupted?

**Comment by kevinkreiser** [comment]
@mesozoic-drones yes `volatile` forces the compiler not to reorder or optimize out (cache) reads/writes to that particular object.

**Comment by mesozoic-drones** [comment]
> 64bits (the read width of modern processors)
> (32bit platforms beware)

This was the tricky part for me. Thank your for explanations!

**Comment by mickgrig** [comment]
> valhalla does not update the traffic tiles, that needs to be done by an external process which writes directly into the tar. valhalla then reads the changes on-the-fly as everything around traffic tiles is declared `volatile` and yeah it's memory mapped as you said. so the challenge is really to set up the feeder architecture: pulling live traffic data, possibly converting the info to valhalla internal `GraphId`s after possibly matching the traffic source geometries to the graph, to then update the edge infos in the traffic tile tar.

@nilsnolde @kevinkreiser 
Actually I'm also interested in this issue and would appreciate any assumption and views.

I experimented a little bit with it and my main concern is not about volatality, because it's quite clear that volatality will suppress all compiler's optimization. But main question is about memory mapping. So, how can we be sure that updating our tar-file externally will definetly affect our mapped data? Because if we take a look into mmap() manual (https://man7.org/linux/man-pages/man2/mmap.2.html) we will see some descriptions about used flags, but I didn't find some info about this case (direct modifying of file).

For traffic-tiles currently MAP_SHARED is used. And they say about this flag:
>Share this mapping.  Updates to the mapping are visible to other processes mapping the same region, and (in the case of file-backed mappings) are carried through to the underlying file.  (To precisely control when updates are carried through to the underlying file requires the use of msync(2).)

So, maybe it's more reasonable to update tar-file not directly, but via memory mapped data from another process, because it is definetely guaranteed by mmap with MAP_SHARED flag? What do you think?

**Comment by kevinkreiser** [comment]
> So, maybe it's more reasonable to update tar-file not directly, but via memory mapped data from another process

@mickgrig that is exactly how it is done. you run your valhalla process which mmaps the traffic tar,  you run another process, written in whatever langauge you want, that also mmaps that same traffic tar. that other process gets updated traffic records from somewhere and when it does, it overwrites those sections of the tar which contain those out of date records.

**Comment by mickgrig** [comment]
Thanks, Kevin. It clarifies for me a lot about your approach.
