### ISSUE TITLE
Including constructions with #3455 not working

### ISSUE THREAD

**Issue by schlage-tg** [valhalla/valhalla#3512]
Hello,
we are using valhalla to match different road networks onto the osm road network.
I saw the new merged PR and compiled a new router and created new tiles.
I tried to match some of our ways on the problematic construction ways. 
One example would be on this osm way https://www.openstreetmap.org/way/896102842.

Do I need to set a new parameter in the locations parameter like `exclude_ramps'?

Thank you for your work.

**Comment by schlage-tg** [comment]
I forgot to mention I also set the parameter "include_construction" in the valhalla.json to true before building the new tiles.

**Comment by nilsnolde** [comment]
do you have a request for us with e.g. curl @schlage-tg ?

**Comment by kevinkreiser** [comment]
@schlage-tg at the moment we just include ways under construction in the graph. i put a bunch of comments on that pr about your use-case (because i was thinking of it too) but at the moment there is no way for a costing model to allow using edges that are under construction.

my opinion was that if you supply the `ignore_access` flag we should allow you to take edges that are under construction but we didnt include that in the original pr. its not a lot of work to include that though, and it would allow you to achieve what youa re looking to do. in general when trying to match different road networks it is sometimes useful to make use of the various ignores we provide: ignore_oneway, ignore_restrictions and ignore_access. sadly though construction is not yet in the list. imho ignore_access should allow edges under construction.

**Comment by schlage-tg** [comment]
@kevinkreiser I guess that explains my issue and i misunderstood the PR. I thought this was already possible with the constructions.
Thank you for clarifying.
