### ISSUE TITLE
/route service and lack of bike paths?

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3521]
We are using valhalla's /route service for bike routing in our mobile app. We are getting complaints however from users who say that the /route service isn't taking them on bike paths and doesn't seem to know about bike paths. Is this true, and if so, is it because of a lack of bike path data in OSM? Might it instead be because we are not passing in more to costing options?

The json input to the /route service is the following (just simple): "costing_options":{"bicycle":{}}}

**Comment by kevinkreiser** [comment]
This can be for a variety of reasons, but there are two reasons that I can think of:

1. There are a lot of bicycle options for you to choose from and these do impact which edges in the graph are used. The problem is you have to know something about the user to be able to pick the right options to meet their expectations. I would carefully read over the docs here: https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md#bicycle-costing-options `use_roads` is of particular interest if you know that your user prefers bike only paths or lanes. Also of importance is setting the correct `bicycle_type` as this will exclude/include certain types of edges in the graph depending on what we think your wheels/tires can handle.
2. OSM may be missing ways/correct attribution in the area where the user is riding. To find you're going to need information about where the user was and exactly what their expectation was for the route.

Let me know if that doesnt make sense.

**Comment by dnesbitt61** [comment]
Echo'ing what Kevin said. Try setting bicycle type to Cross or Mountain. That would allow use of cycleways that perhaps have poor surfaces. Setting use_roads = 0 is another way to favor cycleways. However, even with default options (using no extra costing_options) I see bicycle routes frequently using cycleways in my testing near Washington, DC and also the Schuylkill River Trail west of Philadelphia. So perhaps some of what you are seeing is incorrectly tagged OSM data?
