### ISSUE TITLE
/trace_attributes error code documentation

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3531]
Is there documentation on all of the possible error codes for the /trace_attributes service? Wanted to go through and consider each of the possible errors that a call to /trace_attributes could output

**Comment by kevinkreiser** [comment]
we do have documentation for errors: https://github.com/valhalla/valhalla/blob/be537e57eab86ffb8653f179135e47c188ab8047/docs/api/turn-by-turn/api-reference.md#internal-error-codes-and-conditions

but its likely not fully up to date. the best full list is in code: https://github.com/valhalla/valhalla/blob/master/src/worker.cc#L50-L139

map matching happens in the thor worker so the most likely ones you'll see that are specific to map matching would be in the 400 range: https://github.com/valhalla/valhalla/blob/master/src/worker.cc#L122-L137

that said pretty much if anything goes seriously wrong in map matching you get a 444. we need to debug the code to see what exactly the error is since there are several potential reasons.
