### ISSUE TITLE
GUI: allow quick+easy reset of settings to default values

### ISSUE THREAD

**Issue by georg-d** [valhalla/valhalla#3574]
In the GUI, please allow to quickly +easily reset a single or all settings (driveway factor, step penalty,...) to default values. Example use cases

- You changed settings for a very specific, untypical trip, e.g. with your visiting grandpa in his wheelchair or 2 year old nice, and now you'd like to compute a route for yourself with "normal" settings
- You experience a weird routing result like https://github.com/valhalla/valhalla/issues/3573 and would like to rule out that it is caused by a setting you unintetionally changed to a weird value

**Comment by nilsnolde** [comment]
here's the right repo: https://github.com/gis-ops/valhalla-app

we need to make more visible apparently. no worries, you're not the first one confusing it. somehow github's transfer feature is broken since weeks, so I can't transfer it myself. could you please open the same issue over in the right repo?

**Comment by nilsnolde** [comment]
fwiw, we'll add a github logo to the app and link it to the right repo. or other suggestions?

**Comment by georg-d** [comment]
I did report the issue again as https://github.com/gis-ops/valhalla-app/issues/14

About helping users to find the right repo, I added my 2 cents directly in https://github.com/gis-ops/valhalla-app/issues/11
