### ISSUE TITLE
No routing over ways with highway=platform

### ISSUE THREAD

**Issue by szymone** [valhalla/valhalla#3691]
Pedestrian routing is not possible using ways tagged with highway=platform. This tag is often used when bus platform is located directly on sidewalk and the way with this tag creates a gap. Any ideas how to resolve this issue? As I remember, ways with highway=platform are not included in graph for pedestrian routing, is this correct?

<img width="615" alt="image" src="https://user-images.githubusercontent.com/10035692/182098741-cd5f27bc-f196-4a57-9a80-672ff3242d7b.png">

https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=19.006070421201006%2C50.30281311002737%2C19.006421921221776%2C50.302628515537414

**Comment by 1ec5** [comment]
This seems to be the norm among routers unless a linear footway is also drawn through the platform or the platform is dual-tagged as a footway: https://github.com/openstreetmap/iD/issues/8760#issuecomment-948196855. That said, I can’t think of any situations where opportunistically including them in the walking routing graph would result in poorer routes.

**Comment by Woazboat** [comment]
This issue is marked as question, but as I understand it it's actually a request to also consider `highway=platform` for pedestrian routing. That seems very reasonable and necessary. Use of `highway=platform` as shown in the attached image is very common and are always routable for pedestrians. 
Not considering `highway=platform`as routable currently leads to a lot of cases of broken pedestrian routing.

> This seems to be the norm among routers unless a linear footway is also drawn through the platform or the platform is dual-tagged as a footway: https://github.com/openstreetmap/iD/issues/8760#issuecomment-948196855.

Your comment seems to refer to the `public_transport=platform` tag. Dual tagging that as a footway is possible, yes. This issue is about `highway=platform`, which isn't possible to dual tag as a footway because it also uses the `highway=*` key.

**Comment by nilsnolde** [comment]
I think I don't see any issue allowing `highway=platform` for peds. There's a separate effort to (re-)enable public transit via GTFS, such platform OSM edges might disturb a bit potentially.

BTW, the OP is not a good example anymore, apparently someone re-tagged that way, as Valhalla routes as you'd expect.

**Comment by nilsnolde** [comment]
I actually wanted to quickly take care of this one. Then I realized I couldn't find a proper example in OSM. I scoured Berlin for a bit, couldn't find any way tagged `highway=platform` that was actually connected to any other way. Everyone I found was like this:
![image](https://user-images.githubusercontent.com/25637358/218284512-5f718c66-1318-4376-a992-a895ac9c281d.png)

Also, that's what I'd expect. I can definitely imagine that it's done somewhere on the planet, so I'd be open to include it anyways. I'd personally be happier if someone could point out problematic cases (the OP is not an issue anymore, it was converted to the same as the pic). Probably there's other similar tags too like `public_transport=platform` might be similar? Those would definitely clash with GTFS, but we wanted to have support for this optional/configurable anyways, no one will be forced to include those ways.

I'll pin this, since it's a bit older, but I'd still like to do this in case no one really minds.

**Comment by szymone** [comment]
Hi Nils! Here you have some good examples of using highway=platform tag connected to other ways.

https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=18.08330833911896%2C53.128127874973494%2C18.082385659217838%2C53.127548487300594
https://www.openstreetmap.org/way/394418202#map=19/53.12769/18.08286

https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=19.006535410881046%2C50.28711825565948%2C19.00690019130707%2C50.28550728202502
https://www.openstreetmap.org/way/204310689
https://www.openstreetmap.org/way/330903178

**Comment by nilsnolde** [comment]
Exactly what I was looking for, thanks a ton @szymone !
