### ISSUE TITLE
Large Mismatch between /route and /sources_to_targets APIs

### ISSUE THREAD

**Issue by saby1101** [valhalla/valhalla#3701]
Matrix API responds with 183 KM
```
curl --location --request POST 'https://valhalla1.openstreetmap.de/sources_to_targets' \
--header 'Content-Type: application/json' \
--data-raw '{
    "costing": "auto",
    "sources": [
        {
            "lon": 87.328065,
            "lat": 22.074612
        }
    ],
    "targets": [
        {
            "lon": 87.4209209,
            "lat": 21.909807
        }
    ]
}'
```

Route API responds with 24.526 KM
```
curl --location --request POST 'https://valhalla1.openstreetmap.de/route' \
--header 'Content-Type: application/json' \
--data-raw '{
    "costing": "auto",
    "locations": [
        {
            "lon": 87.328065,
            "lat": 22.074612
        },
        {
            "lon": 87.4209209,
            "lat": 21.909807
        }
    ]
}'
```

Here is the link for the routes generated https://valhalla.openstreetmap.de/directions?profile=truck&wps=87.328065%2C22.074612%2C87.4209209%2C21.909807

Route API is giving correct result of 24 KM. Matrix API responds with 6-7 times that value. And if I set `"costing_options": {"auto": {"shortest": true}}`, then the response is weirdly null
```
    "sources_to_targets": [
        [
            {
                "distance": null,
                "time": null,
                "to_index": 0,
                "from_index": 0
            }
        ]
    ],
```

**Comment by saby1101** [comment]
Is there a way to circumvent this bug by setting some cost_options? I tried with costing as pedestrian, matrix api is returning correct results. 
Also, under what conditions Valhalla will return distance as null in the matrix API?

**Comment by kevinkreiser** [comment]
I'm not sure what it thinks the path is. We have to debug it to find out. Would be nice to add some debug to recover the path for just these types of investigations in my opinion. One work around may be to use a specific algorithm if it's just one that has the bug.

**Comment by saby1101** [comment]
If I change hierarchy_limits from
```
constexpr uint32_t kDefaultMaxUpTransitions[] = {0, 400, 100, 0, 0, 0, 0, 0};
```
to 
```
constexpr uint32_t kDefaultMaxUpTransitions[] = {0, 400, 500, 0, 0, 0, 0, 0};
```
the response matches for both the APIs. The comment for `kDefaultMaxupTransitions` says that it is optimized for bidirectional a*. How can we determine the optimal values for the cost_matrix algorithm? And what repercussions are there if I increase it to very high values like 1000 or 10000?

**Comment by kevinkreiser** [comment]
controlling the number of heirarchy transitions is one of the ways that we avoid looking at too much of the graph for any one graph expansion/traversal, its a strategy or heuristic we employ to increase performance at the cost of absolute accuracy. i have to review the cost matrix algorithm as i havent looked at it in quite some time but iirc it is the matrix equivalent of the bidirectional a* algorithm. that said, because it can handle many to many its possible we need to do something different with the transitions based on how many sources or targets you might have. @dnesbitt61 anything spring to your mind here?

**Comment by dnesbitt61** [comment]
This probably is due to bidirectional A* using an A* heuristic to target the expansion between the origin and the destination. CostMatrix expands from each source in the forward direction and each target in the reverse direction but without any A*. This causes hierarchy transitions to occur differently than in bidirectional A*. I had not considered this impact and it may be impossible to get exact matches but it seems increasing hierarchy limits for CostMatrix is required (which will reduce performance).

**Comment by kevinkreiser** [comment]
ah ok so its more like bidirectional dijkstras for matrix good to know!

**Comment by saby1101** [comment]
@kevinkreiser @dnesbitt61 thanks for clearing that up. Increasing the hierarchy limits seemed to have solved most of the errors we were facing at the expense of reducing the performance (which is ok for us). Closing the issue as resolved.
