### ISSUE TITLE
Hello, I wish to meet you folks.

### ISSUE THREAD

**Issue by thehoneymad** [valhalla/valhalla#3723]
Hello peeps,

My name is Prateek. I am from Bangladesh. And I am deeply passionate about routing engines. I have walked on streets to map routes, made free apps for my countryment to find buses. I have a custom navigateion and a on-demand delivery startup.

I don't know any of the maintainers. But I would like to learn, contribute and I hope to either be a maintainer here or modernize Valhalla. I know the graph theory basics.

I would love to meet one of the maintainers. I would gladly accept lessons, helps, and teachings. I work for AWS. I promise not to bank on the code here and steal the thoughts. I will contribute openly, innovate openly.

Will you folks accept someone like me? Help me and teach me? I wrote C++ in uni. So I am a little scared. Im pretty solid with golang and C#.

Thank you. Please leave a reply. I am sincere with my request.

**Comment by kevinkreiser** [comment]
Everyone is welcome to contribute to the project. To get started you can make a fork and review the code. If you have questions about the code make an issue and we'll do our best to answer you. We do not add contributors to the organization lightly. For that you will need to earn your way with quality PRs over a longer time period. If you have more specific goals, like features you want to work on, please open issues for those and we can even guide you during the implementation and design process. Thanks very much for your interest and good to meet you!

**Comment by thehoneymad** [comment]
Hello, thank you for the reply.

I will earn my badge. I am very curious about how Mjolinir and Baldr works. I have been reading the code for a while. But I have not understood everything. Would any of you be open to a call to have a chat with me?

I apologize if I sounded too eager to be part of the org without contributing. I did not mean that.

**Comment by thehoneymad** [comment]
I even started writing a golang clone for it to validate my thoughts. But I am far far away from anything eventful. I am curious on producing serialized route graphs that can be serverless friendly, iteratively loaded. For example, I see we have 3 level of tiles. But it does not look like a balanced tree. My curiosity was to know why that is the case.

**Comment by kevinkreiser** [comment]
valhalla can be run in a serverless mode but the latency is abhorent. if you wanted to you could use aws lambda with valhalla configured to pull its graph tiles from s3 (this is supported today) but because a graph algorithm needs the graph it has to pull that as  its computing the path, this means your lambda will take a while compute the route as it pulls data from s3 to be locally used for the graph traversal. like i said the latency sucks, if you want through put you need long running processes and to keep some of the graph in memory to remove the data fetching part from the graph traversal.

what do you mean it doesnt look like a balanced tree? do you mean there are negative weight cycles in the graph? if so, i am very skeptical of this, we dont even store weights in the graph so if you've been looking at baldr and mjolnir then you got the wrong idea there. sif is what determines the weight of a given edge (we call it cost) and this should always be positive unless there is a bug, which is always possible but not intended :smile:

**Comment by kevinkreiser** [comment]
also i would suggest starting a new discussion in the repo so that we can answer questions there as you have them. id rather not lengthen this issue with many many different topics.
