### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rwrx** [valhalla/valhalla#3771]
Hello devs, I just have a quick question, when will be released new version of Valhalla?

**Comment by kevinkreiser** [comment]
We get this question enough I'm beginning to have a radical idea.

First i saw that github now has its own integrated docker container registry. I like the idea of using it rather than dockerhub because it will show our releases on the main github repo page.

Second, what if every pr that got a new changelog entry was a release. The logic could be something like if I find a new changelog entry the docker github action publishes a release. The changelog would become slightly more verbose but all the changes would be isolated and no one would be waiting for a release.

The main downside is it would be hard to hold back something from release. Perhaps that isn't a problem though? I understand that it's not always possible to do all the bits of a project in one pr but this could force us to always merge stuff that had no side effects in production (I think we already do this but I'm just saying it outloud)outlook.

@nilsnolde or anyone else, what do you think? if there is positive support for the idea we can close this issue and I can make a new one suggesting this outcome

**Comment by nilsnolde** [comment]
> Second, what if every pr that got a new changelog entry were a release

For me, that's pretty much the same as no releases at all. And the same as most people have probably been using Valhalla so far, either `master` or `latest`. We have to keep some notion of versioning because of the tile schema. Other than that we could actually get rid of it, no? Also a bit radical :smile: 

I know you'd like to make everyone happy while keeping some sense of realistic maintainability. Still, I personally wouldn't really like every commit to `master` becoming its own docker image. That sounds like a huge digital waste.

So all in all, I guess I'd be in favor of absolutely no versioning other than major version when we (in the far future) change the tile schema. Changelog could have dates next to the items to give some temporal context.

That was my spontaneous thoughts. I'll dwell over it a bit more tmrw:)

**Comment by kevinkreiser** [comment]
Hmm maybe I didnt think it through all the way. More specifically what I was thinking of was that each time someone updated the changelog with a new version string we'd cut a release automatically. Obviously we wouldnt merge anything that would break backwards compatibility wrt the tile schema without upping the major version. But the idea is that when someone increments the minor version it makes a release and the etiquette could be that most times we update the minor version.

I agree that people can just use master or latest but you have to consider how someone who doesnt know the project as well as we do interact with it. From their point of view a recent release means the project is actively maintained and supported. Sure they can see we are merging stuff to master but they cant really tell if its something they could just use and not expect stability problems, the official release is like a stamp of approval. Thinking of that though, maybe that is the argument that we shouldnt release every or almost every merged PR. Perhaps the stamp of approval should be a manual thing that we base on our judgement after using master for a while, in other words the way it is today.

I dont really have strong feelings either way about it, i can see the arguments for both approaches. Honestly I would just rather not have to think about how long its been since last release. Oh and one other thing it solves is that our docker releases for latest and so forth are always tip of master, if  someone wants to get a release in between they are out of luck, its either the last tag or tip of master none of the other master builds stick around as we overwrite them. i understand though that you think its wasteful to keep each master build. i dont really disagree. i just dont want to think about when to release. there are so many prs adding and working on different things its hard to find a spot to cut a release that makes logical sense. anyway im babbling. probably best to just keep the release point manual for now

**Comment by nilsnolde** [comment]
IMO it’s fine to state things about releasing (or the fact that we’re not) in the README. Honestly, everyone using any kind of more esoteric OSS software (in the broadest sense 😄), should be aware of the project and at the very least look at the README. And as you point out, commit history is, next to releases but before PRs/issues, by far the most important metric by which to judge the activity of a project. 

We don’t publish on any package manager or run some sort of special benchmarking only when we release. And you’re right, it’s a headache when to cut one. It’s long overdue, yet there’s always one or more PRs which we’d like to merge before cutting one, literally always haha. 

I see 4 options:

1. release on every changelog item with all the advantages and disadvantages listed above
2. don’t release at all and clearly state in the README that the tip of master is in a usable state and the Changelog can be used to track back and build other “versions”
3. simply release on a fixed schedule, once a quarter or so, maybe even timestamp based like 01.10.2022
4. keep on like now. I’m happy to, now and then, suggest cutting one and we can agree which PRs to merge before and prioritize those, but then be strict about it and subsequent PRs will be in the next one unless they’re trivial

No hard feelings about it either. But I’d like to have a consensus about it so we’re clear for ourselves:)

**Comment by kevinkreiser** [comment]
Yeah I'd prefer number 4 the statusquo for now I guess. I really preferred the ppa we had but cmake screwed that all up :)

**Comment by nilsnolde** [comment]
closing and opened #3775 :)

**Comment by ImreSamu** [comment]
Some of the prospective users are conservative and are willing to use only the released versions. So I would prefer a regular 1-2-3 monthly release as a user.

### master ...

> I agree that people can just use master or latest  ...

The version is important for the `/status` API ..  https://valhalla.readthedocs.io/en/latest/api/status/api-reference/
```json
{
"version": "3.1.4",
"tileset_last_modified": 1664460446
}
```
The new users 
* checking the https://valhalla1.openstreetmap.de/status   and the result is:  ` "version": "3.1.4", `
* and checking the relevant version https://github.com/valhalla/valhalla/releases/tag/3.1.4 ( Release Date: 2021-10-07 )

so the master is not yet ideal for a large setup  ( not supported with the  `/status` API )

### packaging ...

also need a released version:

Repology - Valhalla is still in the latest release.  ( 3.1.4 )
* https://repology.org/project/valhalla/information
* https://repology.org/project/valhalla/versions

[![Packaging status](https://repology.org/badge/vertical-allrepos/valhalla.svg)](https://repology.org/project/valhalla/versions)

**Comment by nilsnolde** [comment]
Ha, I wasn't aware we're on "that many" package managers! Never bothered to check for AUR, wanted to do that actually soon. 

Yes, you're right, in that case it's really important to still release, so option 2 is definitely out:)
