### ISSUE TITLE
DirectedEdge as a straight line (for midpoint calculation)

### ISSUE THREAD

**Issue by kungfu303** [valhalla/valhalla#3786]
Can we assume that a DirectedEdge's geometry is a straight line? Asking since I need to grab the midpoints of a DirectedEdge. 

On the same note, what's the best way to go about finding the midpoint of a way (find a list of the DirectedEdges that make it up, then find the midpoint of the middle one? Using an ordered list of way to DirectedEdge ids)?

**Comment by kevinkreiser** [comment]
`DirectedEdge`s are not straight lines, the describe a topological connection between two nodes in the graph and not the physical geometry between them.

To find the midpoint of a way, you would need to do a graph traversal.

- Find an edge with the way id you are looking for
- Follow edges that are connected to its end and begin node
- If the edge has a matching way id but isnt the opposing edge of an edge you already looked add
  - add it to the beginning or end of your search depending on which node you expanded from
- For each edge in the sequence (in order)
  - Get the shape of the edge and append it to the full shape (you need to reverse the shape if edge.forward is false)
- Call the polyline length function to get the full length
- Call the resample polyline function with distance == length/2
- Use the middle point that its returned from the resample function

**Comment by kungfu303** [comment]
Just to clarify, these are the polyline length function and resample polyline function respectively? valhalla::midgard::Polyline2<valhalla::midgard::PointLL>::Length() and resample_polyline() in util.cc, right?

**Comment by kungfu303** [comment]
Also, if instead of wanting the midpoint of just one way, I wanted to get midpoints of every single way, would this graph traversal be the best method? I would imagine that it would take up a lot of compute to run this on every way id. Any ideas on how to get the polyline shape of each way (and from there, easily use the length and resampling function as you suggest)?

**Comment by kevinkreiser** [comment]
we have an application called `valhalla_export_edges` which does almost exactly this. it doesnt spit out the midpoint, but it does spit out the shape of every contiguous set of edges that share the same name property. you could take that code, modify it to care about the way id (and add in the bit about not wanting the opposing edges) and then run it to spit out the wayid and shape. that code, for the full planet, runs in about 7 minutes on decent hardware.

alternatively, you can avoid graph traversal completely by using raw osm. valhalla needs edges because it needs to do graph stuff, but you seem to only care about the ways. osm data comes with the ways already there so you could just pull them out of that and compute the mid points

**Comment by nilsnolde** [comment]
Guess that's answered extensively:)
