### ISSUE TITLE
Fastest route takes more time than shortest

### ISSUE THREAD

**Issue by monteirodom** [valhalla/valhalla#3828]
Valhalla is not very smart with routes around Milano (Italy).
I've come with the example below (but many little variations behave the same), where a fastest routes takes 6 minutes longer than the shorter one.

Here are the data for the requests, with the the corresponding routes.

Origin (45.46141, 9.23646)
Destination (45.52777, 9.10579)

Fastest route
- Duration : 1468 secs  = 26 mins 8 secs
- Distance : 28.813 km
![Capture d’écran 2022-11-16 à 15 14 05](https://user-images.githubusercontent.com/82025877/202208344-da336d7f-aa67-441a-be75-b0d6bad214ab.png)

Shortest route
- Duration : 1251 secs = 20 mins 51 secs
- Distance : 14.396 km
![Capture d’écran 2022-11-16 à 15 17 43](https://user-images.githubusercontent.com/82025877/202208527-861099a1-5976-4f37-a2e5-61a8f3bee060.png)

**Comment by nilsnolde** [comment]
Shortest bypasses a lot of costing penalties. It’s somehow wrong to think of it as “fastest” (not sure how to call it better though). We’re applying a lot of extra cost penalties based on road hierarchy etc, and generally hardly care about the time it takes, rather decreasing the overall _cost_. I agree, this looks like an extreme case. You could play around with the costing options, eg decrease the use_highway option.

**Comment by nilsnolde** [comment]
Also from experience it’s definitely not accurate that its the faster route, Milano is crazy traffic and you definitely want to route around it (though I’m aware it’s not really relevant info for your observations, since the data is the data). Still, you might want to look into modulating your speeds with eg https://github.com/OpenStreetMapSpeeds/schema/blob/master/default_speeds.json to have better estimates.

**Comment by monteirodom** [comment]
Thanks @nilsnolde for your comments.
With option `use_distance=1`, I get the same values for distance and duration as with `shortest` option.
And the costs are  `shortest : 14396  /  use_distance=1 : 1046  / use_distance=0 : 1886`

I know the cost calculation drives the route finding, I just wanted to raise this weird behavior to the community.
Actually I think in one's mind (at least mine), the default request means fastest path (least time). The cost does not have any meaning, outside of the computation algorithm.
And if I force a waypoint somewhere in between the 2 paths shown, I do get a route fastest than the "shortest" one.
So I tend to consider there can be some sort of a bias, when computing the default (fastest?) route.

**Comment by kevinkreiser** [comment]
yeah i think @nilsnolde hit a lot of the key points for why this happens. but i'll try to summarize.

by default we estimate the speeds of different types of roads based on their osm tags. this is highly inaccurate. you can increase the accuracy of this (when building tiles) by using OpenStreetMapSpeeds project's data. this would likely "fix" (though i havent test it yet) your issue in that it would still provide the highway route but also the through the city route would have a longer travel time. 

also the router uses many factors in addition to the time (based on the speed) of the edges in the graph. a very important factor, other than time is the road class (motorway, trunk etc). lower classes of roads are penalized (that is they get a costing penalty but not a physical time penalty) because they are often slower and less comfortable to drive on (eg. they require many more maneuvers). this penalization also makes up for the lack of accurate speed information. anyway, routes that favor less maneuvers and stay on higher class roads are arguably a better choice and that is the default that valhalla provides. in other words, the route that you would want to drive might be a little slower (theoretically) than the absolute fastest (theoretically) but that slowness is worth it from a comfort standpoint.

if you are interested in doing something more analytical then perhaps you arent really looking to use the defaults anyway which is totally fine you can tweak all kinds of costing parameters to try to get the types of routes you want. the default, however, was a design decision that we made based on our experiences.

**Comment by monteirodom** [comment]
Thanks @kevinkreiser for those precisions on the cost factors. I do agree with you and @nilsnolde, that one would prefer to take the all around route rather than going through the center.
I didn't test the OpenStreetMapSpeeds (I'll try some day soon), but actually I would think that the "fastest" route is indeed more accurate in time, than the "shortest" one.

By the way, looking at the code, there's a comment in `AutoCost::TransitionCost` saying
```
  // Transition time = turncost * stopimpact * densityfactor
```
But on the actual code, only the cost is computed that way, not the time. Could it be that something is missing or is it just the code and the comment that are not synchronized?

**Comment by kevinkreiser** [comment]
its confusing for sure. let me see if i can explain a little. its true that we say that cost is in imaginary units since it doesnt measure actual time, but since pretty much all the other factors are in seconds units, when we add penalties to the cost, we do so in seconds. so that whole `if` block you saw over there, its doing what we can broadly call a "maneuver pentalty" which is to say we add extra cost (in this case in seconds) to the cost part of the edge label (the path to this spot so far) but since this isn't actual time  that you will spend making the maneuver we dont add it to the time part of the `Cost` struct. essentially because we dont want  you to have to make a bunch of complex maneuvers (that is a poor quality route) we pretend that those maneuver take longer than they would so that the path that is chose favors routes with less maneuvers.

so yeah, we dont actually want to add them to the `time` because then our ETA would be less accurate. instead we add that extra time penalty to the cost metric which is what controls the path selection. i hope this made sense. let me know!

**Comment by monteirodom** [comment]
Yeah, the "maneuver penalty" makes sense, avoiding paths with too many maneuvers makes sense.
I'm just wondering, but never mind ... _some time is accounted for a maneuver turn (depending on the angle), but does the maneuver by itself also take time (even if accounted for with a different factor than for the cost)_?
