### ISSUE TITLE
Odin supports only Germanic-style two-form plural

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#385]
(2016-04-11T12:55:23Z) @mormegil-cz : originally created valhalla/odin#291

(2016-04-11T13:11:27Z) @kevinkreiser : this is great! we were really hoping people would poke holes in our format so that we could find where it didn't support a particular feature of a particular language. we'll try to get something in there to address this. if there are any more things you can think of to improve support for Slavic languages please add more issues!

**Comment by Pohli** [comment]
Is this also related to the following problem? If I'll use German directions it always say "Meters" instead of "Meter" (plural form). In German language the singular and plural forms of the word "Meter" are the same.
I'm using Pure Maps with the Stadia Maps router on Sailfish OS on a Jolla1 smartphone.

**Comment by kevinkreiser** [comment]
@pohli there are some updates needed to the german translation. seems like we just copied english in there and didnt translate the whole thing. should be a quick fix.

**Comment by ianthetechie** [comment]
The timing for this was perfect, as I was just rolling out our weekly data updates, and the changes were very easy to cherry pick. You should be seeing the correct German now.

**Comment by Pohli** [comment]
Thanks! I'll check as soon as it will be included in a future version of Pure Maps.
