### ISSUE TITLE
GraphReader::GetShortcut returns non-shortcut edge

### ISSUE THREAD

**Issue by PhilippVoigt** [valhalla/valhalla#3888]
As briefly discussed in #3887 we have noticed that `GraphReader::GetShortcut` doesn't always return the correct result. I've prepared simple unit tests to showcase the issue: [graph_reader_get_shortcut_bug](https://github.com/PhilippVoigt/valhalla/blob/graph_reader_get_shortcut_bug/test/recover_shortcut.cc).

At first glance it seems to be an index off-by-one kind of error, the returned edge always has ID one higher than the expected shortcut. I will keep debugging myself to deepen my understanding of the data structures, but the root cause is probably immediately obvious to some of your more experienced eyes 😉

Philipp Voigt (<philipp.voigt@mercedes-benz.com>), Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by kevinkreiser** [comment]
@ichliebemath cooler username ;)

yeah i just havent had the time to look into this. the tests that @PhilippVoigt wrote seems to show a mismatch between the output of `RecoverShortcut` (get the edges that make up the shortcut) and `GetShortcut` (get the shortcut that the edge is part of).

on the surface, this seems like it could be a possibility that can happen. recovering the shortcut is not exact in the sense that the graph traversal that it does may have two equally good options. imagine a set of edges like this:

```
                                    __________________
                                   /                  \
A---------X------------X----------X                    X--------------B
                                   \__________________/                                 
```

Assuming all the properties of all the edges there are identical then there are two potential ways to make a shortcut from A to B. We will only make one shortcut so when we recover we hope that we recover the same one but because of the ambiguity i suppose its possible to recover the bottom edge where the shortcut had the top edge or vice versa.

We could make `RecoverShortcut` robust to this. By default i would think it takes the first edge that leaves the node where the ambiguity begins, which i assume is what the shortcutbuilder does. If we can make the behavior between the recovery and the builder match then the only thing that could mess this up are changes to the graph topology after the shortcuts are built.

Deeper investigation is required here.. what i would do is add logging to the code where the shortcuts are made for certain shortcuts by their id (the ones that fail the tests). Then id step through both the builder and the recovery methods to see how they differ in traversal. it is also possible that `GetShortcut` has a bug or the one of the other methods has a small off by one bug. have to get into the debugger to find out

**Comment by ichliebemath** [comment]
Hi Kevin @kevinkreiser ,

thank you for your prompt reply and also your helpful suggestions! I will have a deeper look also on `RecoverShortcut` and the shortcutbuilder. Please let me know when you have some new insights or findings on this issue.

Cheers and have a nice weekend :)

**Comment by PhilippVoigt** [comment]
Hi @kevinkreiser, thank you for sharing your thoughts!

I actually do believe that `RecoverShortcut`is deterministic, maybe at least in the real world 😄
I have not seen any mismatches between `RecoverShortcut`and `GetShortcut` anywhere in a graph of Europe.

That's why I still believe the issue is directly inside `GetShortcut`, but you might be right about the off by one bug actually happening in the shortcut builder. I will continue debugging in that direction and keep you posted.

**Comment by PhilippVoigt** [comment]
I just wanted to quickly share my findings.
In [graphreader.cc#L808](https://github.com/valhalla/valhalla/blob/98fa75242d1853dcf2a58e9f29b775cc5d4dedc2/src/baldr/graphreader.cc#L808) the `GraphId` of the shortcut is reconstructed from the `superseded` mask:

`uint32_t idx = node->edge_index() + (directededge->superseded() - 1);`

It turns out this fails as soon as the node has 3 or more shortcuts connected to it. We set the superseded mask like this: `1 << (superseded - 1)` so one way to retrieve the original index would be `log2(superseded_) + 1` instead of `superseded - 1`. Interestingly, both versions return the same result for the first and second shortcut of a node but are off by one for the third (apparently 3 shortcuts are rare enough already and 4 or more practically don't occur). Changing the line like this solves most of the cases:

`uint32_t idx = node->edge_index() + log2(directededge->superseded());`

Now I'm left with a few instances where no continuing edge and as a consequence no shortcut can be found. I'll keep digging!

**Comment by PhilippVoigt** [comment]
Hi @kevinkreiser, @nilsnolde,

we've made good progress and identified another issue in `GetShortcut` by comparing it with `RecoverShortcut`and `AddShortcutEdges`in shortcut builder. We found that there are two additional conditions that disqualify edges during shortcut construction:
- `directededge->use() == Use::kConstruction`
-  `directededge->bss_connection()`

I've added both conditions to likewise filter potential continuing edges during shortcut recovery and it solved the cases in which `GetShortcut` found multiple candidates for the continuing edge.
Does this seem valid to you? I'm not fully confident because `RecoverShortcut` in turn checks for `kConstruction`but not for `bss_connection`.

Apart from this we found several edges (that are in fact not superseded) for which we `GetShortcut` returned a nearby shortcut. Below is a visualization of one such example. If we pass edge 1/51305/48 (highlighted in red), the algorithm follows the blue edges until it eventually finds the start of shortcut 1/51305/121 (highlighted in magenta).

![Screenshot 2023-03-09 at 10 53 44](https://user-images.githubusercontent.com/114676310/223985857-0d97acfa-edd2-462d-b0a7-b8760b0f95f0.png)

We could implement a sanity check after the fact to make sure the shortcut is only returned if it really covers the given edge. Still I believe there must be an algorithmic way to prevent this case. Any ideas are greatly appreciated :)

**Comment by kevinkreiser** [comment]
@PhilippVoigt that sounds promising! i hadn't reviewed the heuristic in a while but indeed if there is a mismatch between the 3 different functions differences could certainly arise. it would be awesome if we could encapsulate the heuristic into a single function that all 3 could call so that they all always agree on all the criteria of an edge that matter for shortcut generation, recovery and matching.

as for the second issue why doesnt `GetShortcut` immediately return if the edge passed in isn't marked superseded? why does it even try to do a traversal, or have i misunderstood you?

**Comment by kevinkreiser** [comment]
why dont we just exit early somewhere around here:

https://github.com/valhalla/valhalla/blob/98fa75242d1853dcf2a58e9f29b775cc5d4dedc2/src/baldr/graphreader.cc#L768-L778

like so:

```c++
  if (!directededge->superseded()) {
    return {};
  }
```

**Comment by PhilippVoigt** [comment]
> it would be awesome if we could encapsulate the heuristic into a single function that all 3 could call so that they all always agree on all the criteria of an edge that matter for shortcut generation, recovery and matching.

I can do that while I'm at it 👍 

> as for the second issue why doesnt `GetShortcut` immediately return if the edge passed in isn't marked superseded? why does it even try to do a traversal, or have i misunderstood you?

For this one, I'm not sure if I understand you correctly, should every superseded edge have a superseded mask? The way I understood it, the whole point of the `GetShortcut` algorithm is to continue traversal until an edge with a superseded mask > 0 is found?

**Comment by kevinkreiser** [comment]
hmm seems like indeed we only mark the beginning of the shortcut.. that does complicate things. i guess technically one could call RecoverShortcut from within GetShortcut after one has found a candidate and then if the recovered version doesnt include the edge in question its not actually part of the shortcut... I dont love this suggestion at all... need to think about it more

**Comment by ichliebemath** [comment]
> hmm seems like indeed we only mark the beginning of the shortcut.. that does complicate things. i guess technically one could call RecoverShortcut from within GetShortcut after one has found a candidate and then if the recovered version doesnt include the edge in question its not actually part of the shortcut... I dont love this suggestion at all... need to think about it more

Hey Kevin @kevinkreiser, thanks and this idea works for me practically, but I also feel like there must be a more elegant way to deal with this :) would appreciate it if you can give some more insights or updates

**Comment by kevinkreiser** [comment]
so to summarize this second issue, some edges are not part of shortcuts at all. they aren't marked in any way so that you could differentiate them from edges that are internal to a shortcut. the traversal, even if it uses the same heuristics as the builder and recovery methods, can find false positives when the edge doesnt really belong to a shortcut. basically this method was only meant to be called when you know the edge is part of a shortcut. we can think of it like this, the `GetShortcut` can answer the question:

> what shortcut does this edge belong to?

it cannot answer the question:

> does this edge belong to a shortcut?

the answer to that question you need to know before calling this and then only call this method if that answer was `yes`. im not sure if this is inherent due to ambiguity in the shortcut traversal (as i mentioned earlier) or if it can be deterministic and we have a bug. 

all that said, i agree, it would be awesome if we could figure out a way to make the method foolproof so that it can tell if an edge is not part of a shortcut and bailout with an invalid graphid before finding a false positive.

looking more at the code i am now wondering about this line and whether at the very beginning it lets us get into a traversal when we should have stopped immediately:

https://github.com/valhalla/valhalla/blob/98fa75242d1853dcf2a58e9f29b775cc5d4dedc2/src/baldr/graphreader.cc#L790


gegen abend werd ich es mir weiterhin überlegen..

**Comment by PhilippVoigt** [comment]
One thing I keep thinking about, is there a way to identify a node that is the end of a shortcut? If we encounter such a node during traversal we would know that we haven't been "inside" a shortcut in the first place.

Not ideal but probably better in performance than calling `RecoverShortcut`, we could also keep a small list of nodes that we visited along the way and once we found a shortcut check the end of it against that list 🤔

**Comment by kevinkreiser** [comment]
we can definitely tell if a node is the end of a shortcut because its also the beginning of a shortcut. all edges in our graph have opposing edges**, shortcuts included. so wherever one shortcut ends, its opposing edge (also marked as a shortcut) goes back from the original shortcuts end node to the original shortcuts begin node. now this does require that you look at the edges at the node, but we are already doing that in the lambda inside of `GetShortcut` so no extra penalty.

so, what we could maybe do is, if one of the edges leaving the node in the lambda is a shortcut we remember that and then in the while loop that calls the lambda we can say there was a shortcut here and this edge im taking isnt part of it so we can bail.

updating the code to do this is very simple: https://github.com/valhalla/valhalla/commit/3f73e05d41090911a5ab999ef79ee1fe58ee5df5

but it does assume a few things, any node that a shortcut touches is not used for any other shortcuts. i think this is the case but the last time i reviewed shortcut builder was a long time ago so we should vet this assumption. also i left a big todo in there (about pulling the heuristic out into a function to use in all 3 places) which i think, when implemented should mean that we can rely on this method to accurately find the correct shortcut and not find false positives.

anyway those are my thoughts on it for today, maybe tomorrow i review `shortcutbuilder` and change my mind haha. its increasingly difficult to remember all the things :smile: 

**this is not strictly true, transit service edges do not, but @nilsnolde and i have it in our minds to fix that because it doesnt sit right with us, its irrelevant to this discussion though
