### ISSUE TITLE
Empty polygon in avoid_polygons causes Valhalla to crash

### ISSUE THREAD

**Issue by isakengstrom** [valhalla/valhalla#3905]
Reference to issue outlined in [docker-valhalla](https://github.com/gis-ops/docker-valhalla), as requested: gis-ops/docker-valhalla#82

**Comment by nilsnolde** [comment]
I just briefly looked into it. It's easy for us to "fix" and I will, but in truth having an empty array containing an empty array is invalid input (in my book). Simply an empty array for `avoid_polygons` surely behaves fine (and is not invalid input), but when it's containing another empty array, the outer array has a size and that's why it fails with the current code.

**Comment by nilsnolde** [comment]
The real reason I fix it should be the segfault actually. That's always a bit scary for services:)
