### ISSUE TITLE
Hot swapping tile extract

### ISSUE THREAD

**Issue by rochadt** [valhalla/valhalla#3938]
Is there any documentation or additional information on being able to hot swap tar files? We've had success with hot swapping `tile_dir`. However this does not seem to work for `tile_extract`, even if the tar file is built with an index (added by `valhalla_build_extract` script). Any additional information here would be helpful, thanks!

**Comment by nilsnolde** [comment]
That “success” must be coincidental.. AFAIK there’s no way for any thread know its cache has been invalidated.. unless you have almost zero cache or got otherwise lucky. Long story short, hot swapping would be great to have, but not possible as of now in almost any mode of running Valhalla.. I’m sure there’s quite a few past issues outlining that.

**Comment by nilsnolde** [comment]
Since there’s so many old issues, I’ll close. Hot swapping is, IMHO, less of a feature than incremental updates (somehow I conflated the two when I answered last night, though I think it doesn’t make any of my answer invalid).

**Comment by kevinkreiser** [comment]
indeed there are other issues already talking about this particular feature. i should say that we are also very close to being able to support this feature now that we have the index in the tar and can load the tar relatively quickly. the problem there though which we have yet to tackle is how to warm the os memory cache so that once one would swap out one wouldnt get a huge increase in latency. i guess my point is, with the current code we are much closer to being able to support this but we are still unsure how practical it will be for a typical high qps service deployment without special care (eg. round robbin request quiescence during the swap).

**Comment by rochadt** [comment]
Thank you for info!
