### ISSUE TITLE
Question: route api and radius

### ISSUE THREAD

**Issue by kd509** [valhalla/valhalla#4025]
Hello,

when I have a given set of coordinates and have to calculate the route, I will sometimes get the error msg:
{"error_code":442,"error":"No path could be found for input","status_code":400,"status":"Bad Request"}

The reason is, that some of the coordinates are in an area without street network or next street is too far away. For example inside a pedestrian zone. 

Here is an example
This request doesn't work with the default radius of 50.

`route?json={"locations":[{"lat":48.1375617980957,"lon":11.574857711792},{"lat":48.1582565307617,"lon":11.5032968521118}],"costing":"truck","costing_options":{"truck":{"top_speed":120,"height":3.45,"width":3.0,"length":8.0,"weight":40.0}},"units":"km","directions_type":"none","alternates":0}
`

To get it working, just change the radius for the first coordinate:
`route?json={"locations":[{"lat":48.1375617980957,"lon":11.574857711792,"radius":130},{"lat":48.1582565307617,"lon":11.5032968521118}],"costing":"truck","costing_options":{"truck":{"top_speed":120,"height":3.45,"width":3.0,"length":8.0,"weight":40.0}},"units":"km","directions_type":"none","alternates":0}`

Because I don't know, if the coordinate is inside a pedestrian area or not and I don't know what radius is needed to get a valid result, I could change the default value for radius high enough (e.g. 1000). But this will result in a much higher duration in cacluation time if you have about 20 coordinates.

A possible solution is to get a more detailed error description. If I would know which coordinate cannot be connected to the street network, I could higher the radius for this coordinate(s).

So my question:
Is there another parameter which I have to use, that a coordinate is always connected to the street network without raising computing time so much? 

Regards

Karsten

**Comment by kevinkreiser** [comment]
@kd509 you should try using a higher value for `minimum_reachability`, for a detailed description of this parameter see here: https://github.com/valhalla/valhalla/blob/master/docs/docs/api/turn-by-turn/api-reference.md#locations

basically your problem is that you find a small island of roads that looks good enough to start on but once the algorithm actually tries it, it founds out, hmm actually i'm stuck in here! you can pass a higher number for reachability and before the algorithm runs it will try to find a road to start/end on which has at least as many nodes available to it as you specified. the more nodes it has the less likely a candidate edge is a part of a small "subcomponent" (ie a mini graph disconnected from the rest of the larger graph).

anyway i didnt test your route but this is my hypothesis. let me know if this does or doesnt help. viel spaß dabei!

**Comment by kd509** [comment]
@kevinkreiser thank you for your quick answer.

changing this value doesn't make any difference. I tried with a very small value of 1 and also with a high value of 5000.

Regards

Karsten

**Comment by kevinkreiser** [comment]
then this must be a bug with truck costing, im going to flag it as such until i have time to debug it

**Comment by kd509** [comment]
@kevinkreiser you are right. When I change costing from truck to auto it works even with default radius of 50.

```
{
	"locations": [
		{
			"lat": 48.1375617980957,
			"lon": 11.574857711792,
			"radius": 50
		},
		{
			"lat": 48.1582565307617,
			"lon": 11.5032968521118
		}
	],
	"costing": "auto",
	"units": "km",
	"directions_type": "none",
	"alternates": 0
}
```

Regards

Karsten

**Comment by OptiMael** [comment]
@kevinkreiser can you estimate roughly when this bug will be fixed?

**Comment by kevinkreiser** [comment]
hard to say, there are some other open issues similar to this specifically with truck routing and the hypothesis is that there are some specific properties of an edge that affect truck costing but that we dont consider when we make shortcuts in the graph, this can lead to a situation where depending on when in the search the edge is encountered the cost will and wont be able to use the edge.

can you maybe do a little testing for me to narrow it down? can you set very low height/width/weight/length characteristics for your truck requests and see if that also fixes the issue? if it does then that tells us that our hypothesis is still potentially valid. if it doesnt fix it then we need a new hypothesis

**Comment by OptiMael** [comment]
@kevinkreiser 
reducing the trucks height by 1 meter to `"height": 2.45,` was sufficient to get a result for the mentioned example.

**Comment by kevinkreiser** [comment]
cool so that further supports the hypothesis. looking over in shortcut builder i noticed this comment about `access_restriction`s:

https://github.com/valhalla/valhalla/blob/532358650d9a628bf04d9238e9dbf4a6418c3332/src/mjolnir/shortcutbuilder.cc#L426-L427

the comment would suggest that we allow shortcuts across these height/weight/length/width restrictions which we shouldnt do for those modes that use shortcuts (ie truck). looking at the code further i can see that indeed the presense of `access_restriction`s does not appear to stop the contraction of edges in the creation of a shortcut edge (there were no calls to look for access restrictions on the edges we contract to make the shortcut).

**Comment by kevinkreiser** [comment]
@kd509 or @OptiMael would either of you be able to try the branch from the pr above by building test data in the area where you found the issue and seeing if this resolves it?

**Comment by OptiMael** [comment]
> @kd509 or @OptiMael would either of you be able to try the branch from the pr above by building test data in the area where you found the issue and seeing if this resolves it?

Should I wait till #4326 passes CI?🙃

**Comment by kevinkreiser** [comment]
@OptiMael yeah ill ping back when its closer to ready. sorry about that!

**Comment by nilsnolde** [comment]
@kd509 @OptiMael the branch is ready now:) would be cool if you could test this out.
