### ISSUE TITLE
Request 425 was interrupted 

### ISSUE THREAD

**Issue by kk2491** [valhalla/valhalla#4091]
Hi All,  

I am using Valhalla to fetch the distance and duration matrix. Valhalla server configuration is as given below:  

* PBF file - Planet   
* CPU - 4 cores 
* Threads with which valhalla service is running - 4
* RAM - 32 GB 

Whenever there is increase in the number of simultaneous requests below WARNINGS are generated in Valhalla.  

```Request 425 was interrupted ```

This usually results in client waiting indefinitely and causes the system to fail.  

Could you please help me understanding the cause and the impact of the above WARNING message? 
 
Thank you,  
KK

**Comment by nilsnolde** [comment]
32 gb of ram is quite optimistic, depending on how your request patterns are geographically. Esp concurrent requests will probably need to a lot of paging for bigger matrices, so it’ll take even longer than a matrix request already takes in the best scenario.

Have a look at the config json generator in ./scripts, there are a few timeout settings, it’s all self documenting. Other than that your server (Apache or whatever) might also have a timeout.

**Comment by kevinkreiser** [comment]
interrupted means the client hung up. the default is no timeout so if the client is hanging up you might have a server in front of valhalla with a timeout configured which is what nils is saying or your client library might have a timeout configured that causes it to give up. if you are on aws the elbs usually have a 30 second timeout configured as well which would also do this if your requests take longer than 30 seconds

**Comment by kk2491** [comment]
Sorry for the delayed response.  

Regarding the 32 GB RAM: The geo-coordinates in requests are always within 100 km radius. However each request may belong to different part of the world. In this case, is 32 GB RAM is sufficient ? 

This is the current setup we have:  

![image](https://user-images.githubusercontent.com/38481564/235568199-cbc9fc22-1ae8-4087-b8ae-d433c743080c.png)

I do have set timeout for each request which I am sending it to valhalla servers. However in some of the cases it was not effective, and client used to wait indefinitely. The issue occurrence was matching with the the time when we observed the `Request 425 was interrupted` warning. 

Right now I have added a cancel request logic to cancel the request after specific amount of time if no response received.  
However we are still trying to figure out the root cause. 

Thank you,   
KK

**Comment by nilsnolde** [comment]
> However each request may belong to different part of the world. In this case, is 32 GB RAM is sufficient ?

That highly depends on the network density and also the distribution of the locations. There's 2 things to consider:
1. tile cache, usually mmap'ed (use the tar archive, not the plain tile directory!), which will be read into (virtual) memory over time, ideally you have enough RAM for the entire planet, otherwise it'll have to page a lot back and forth as requests in not-yet-available tiles come in. This is mostly a performance thing, and you'll see when load testing
2. RAM used during processing and this can be significant for matrices! 100 km max distance in e.g. [Ruhrgebiet, Germany](https://www.openstreetmap.org/#map=11/51.4820/7.1089) with e.g. 100 locations will pretty sure overflow memory with a few concurrent requests (or even a single one). The CostMatrix is the worst offender in terms of memory: it does 1 (half-bidir) Dijkstras per source/target, i.e. 100 in this example and each would load a significant area. It's not uncommon to have dozens of GB on a single request, where the impact of the amount of locations and network density is generally higher than the impact of the distance between pairs. To mitigate, you could force a TDMatrix instead (by supplying a `date_time` object/string), which is much less RAM intense, but also a magnitude or so slower in most many:many scenarios.

You'll need to (load-)test realistic scenarios to find out about your specific situation, unfortunately there's no one-size-fits-all advice.

**Comment by kk2491** [comment]
Thanks for the detailed explanation. I have few doubts.  

1. To avoid crashing due to memory issues, does the system flush the RAM when it needs to read new data into the memory? I have seen cases where I wanted to crash the system by supplying locations from different locations, but it did not. 

2. `The CostMatrix is the worst offender in terms of memory: it does 1 (half-bidir) Dijkstras per source/target, i.e. 200 in this example and each would load a significant area.` - If 1 (half-bidir) Dijkstras per source/target is it 100 x 100 instead of 200 ? 

3. In our use case we can not make use of `date_time` object/string, as we need the cost matrix irrespective of that and also Expected date/time for the user to be at the location will be calculated by using the data fetched from Valhalla. 

4. Load testing - We have been performing load testing with North America coordinates, we have not see any memory related issues yet. Probably the reason could the coordinates are from the same region.

5. `otherwise it'll have to page a lot back and forth as requests in not-yet-available tiles come in` could you please let me know the magnitude of the difference in response time when the tile is present in memory and tile is not present have to read into memory? 

Thank you,  
KK

**Comment by nilsnolde** [comment]
1. It will but only if the allocations in the algorithm exceed available RAM, not by loading more graph tiles. So you'd have to increase the distances & amount of locations in dense environments to make it crash
2. No, 100 bidir Dijkstra, i.e. 2 x 100 (half) Dijkstras
3. It's just to force another algorithm. However, yes, it'll also respect some time-dependent restrictions (which is good, not bad). You don't need to use the resulting `date_time`..
4. good for you:)
5. No, you need to benchmark.

**Comment by nilsnolde** [comment]
If you have further expert questions, feel free to ping me on my public email.

**Comment by kk2491** [comment]
Thank you so much for the explanation, I do have few other doubts. I will send an email with the details. 
 
Thank you,  
KK
