### ISSUE TITLE
Landmark Routing 1: Intermediate Storage for Parsed Landmarks

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#4134]
- decide on a storage format for the landmarks we parse out of the osm pbf, sqlite is a good one but we could do something simpler and custom like we do for the regular graph data
- write the code to interact with this intermediate storage format (putting, getting and probably spatially indexing are needed)
- write tests to validate the code, you dont need an actual gurka map for this. you should be able to do the 3 operations, put a new record, index it, get back all records within a bounding box

**Comment by vesperlou** [comment]
Hi, 

I just created a PR https://github.com/valhalla/valhalla/pull/4189 for my current progress. 
Have one critical problem: the bounding box select query`LandmarkDatabase::getLandmarksInBoundingBox()` doesn't select the correct rows but select all data in the database. 
Tried a few other select queries, I think the problem is incorrect data in the geometry column. May be wrong `geom` value when inserting landmarks in `LandmarkDatabase::insertLandmark()`, or incorrect geometry part of the select query in `LandmarkDatabase::getLandmarksInBoundingBox()`. 
Spent a whole night but still have nothing. Need some help :)

Junzhen
