### ISSUE TITLE
Valhalla server (planet) - hardware requirements

### ISSUE THREAD

**Issue by JohnMartin10000** [valhalla/valhalla#4140]
Where I can find hardware requirements to run server with planet coverage?
Or if this is not written, what RAM, CPU, SSD size my server have to has to generate route in reasonable times?

**Comment by nilsnolde** [comment]
That's because it very much depends on your use case, Valhalla pretty much only needs a few 100 MB RAM, and what "reasonable times" are is in the eyes of the beholder and also very much depends on the request patterns, endpoints etc. It can run on a 2011 iPhone (if it has the disk size). There's many threads in this repo, but you'll need to search a bit for it (also in discussions).

**Comment by nilsnolde** [comment]
SSD is the only answerable one: current OSM planet has around 80 GB. Building graphs is a totally different story, but you were asking about "running".

**Comment by JohnMartin10000** [comment]
So to run full planet Valhalla server, I only need 100 MB?
What are recommended configurations?

And second question, what is recommended configuration for building graph?

**Comment by ImreSamu** [comment]
@JohnMartin10000 : 

> So to run full planet Valhalla server, I only need 100 MB?

Approximately yes; if there's only one user, without much parallel requests, and route searches aren't spanning continents (in extreme cases). However, if there are such queries, a much larger area needs to be held in memory, which means the data needs to be loaded in and out - a high-speed NVMe for swapping would be beneficial.

My rule of thumb: If there are more serious requirements, then 64 GB RAM + 1 TB fast disk should be enough in the first round. (if elevation data is not needed)

Personal opinion: Since OSM data is growing day by day and I assume the freshest data is needed, I would not attempt to run a full planet server with less than 16- ... -64 GB RAM + at least 4 CPUs. 
And   ~ 64 GB RAM + 600 GB DISK should also be sufficient for graph building. ( ~ probably ; I don't have a fresh information )

IMHO:
* It's advisable to test on a cloud-based machine so you can try out multiple configurations.
* Initially, it's worth testing with only one country's data, as it will make the familiarization process much quicker.
* Additionally, I would start the initial familiarization with a powerful CPU, especially if you mean a Raspberry Pi by 'server'. Once you gain some experience, you can then scale down the hardware requirements gradually.

If you're interested in scaling strategies (which will affect memory requirements), here's a link: 
* https://github.com/valhalla/valhalla/issues/3953

According to the documentation the requirements is lower; so you can test this is valid or not .. and if you need elevation info - you need an extra 1.6 TB disk space.
* https://valhalla.github.io/valhalla/mjolnir/getting_started_guide/
  * _" If you wish to convert the entire planet, we have successfully run conversions on quad-cores(CPU @ 2.70GHz) machines with 16 gigs of RAM utilizing a SSD. Conversions with administrative areas and timezones, but without elevation data will take around 15 hours. This route graph will include motor vehicle, pedestrian, and bicycle route information."_
  * _"If needed run valhalla_build_elevation. I will create an elevation dataset **which is about 1.6TB for the whole world**"_
