### ISSUE TITLE
OSM maxwidth / maxweight are ignored on truck profile

### ISSUE THREAD

**Issue by PartTimeDataScientist** [valhalla/valhalla#4257]
While playing around with the truck profile I realized that on the infamous "Leverkusener Brücke" the maxwidth / maxweight restriction is ignored for the truck profile and Valhalla is happily routing over the bridge

![260945888-8e4f80bf-15d8-4ed5-9763-af9a8b86240b](https://github.com/valhalla/valhalla/assets/30908795/33c389a5-968f-4b0f-b3a6-05fc34757598)

[Corresponding Route](https://valhalla.openstreetmap.de/directions?profile=truck&wps=6.949024200439454%2C51.059519698855276%2C6.939926147460938%2C51.01266308334306)
[Related Way](https://www.openstreetmap.org/way/133838845#map=14/51.0298/6.9628)

Interestingly @nilsnolde pointed out that a [much shorter route](https://valhalla.openstreetmap.de/directions?profile=truck&wps=6.965181775252557%2C51.03668505570838%2C6.956751282292306%2C51.031948745824195) does not work, while adding only a little more distance the bridge is routed again.

Potentially related to #3487 and #3377 although the width restrictions posed by the way referred to in #3377 seems to be respected which puzzles me even more...

![image](https://github.com/valhalla/valhalla/assets/30908795/25cffc42-b35f-40d9-8da7-a827ff714d28)

[Corresponding Route](https://valhalla.openstreetmap.de/directions?profile=truck&wps=-4.260056018829347%2C55.849482539690996%2C-4.2652273178100595%2C55.8518652298043)
[Related way: Cook street](https://www.openstreetmap.org/way/972410214#map=17/55.85024/-4.26043)

If these restrictions are generally susceptible IMHO the truck profile is basically rendered not usable.

**Comment by nilsnolde** [comment]
Hm, interesting.. For some reason it doesn't behave like it did a few mins ago :sweat_smile: I don't understand..

**Comment by nilsnolde** [comment]
Hmpf, [this route](https://valhalla.openstreetmap.de/directions?profile=truck&wps=6.949024200439454%2C51.059519698855276%2C6.946707076098453%2C51.026496667384635) is not right even when disabling hierarchies. That's very puzzling, since the OP's route does work correctly then. In fact when you move the destination almost anywhere else it'll take the restricted road regardless of the parameters passed. 

I'm very sure it's because of the `disable_hierarchy_pruning` option. The OP's destination is inside a industrial park, which I'm sure has a few `dest_only` roads and the route works because it's a second pass which also relaxes the hierarchies IIRC. Of course that doesn't make any sense as hierarchy limits should be disabled already. Glancing at the code I can't see anything wrong.. Shortcuts shouldn't be expanded and down transitions are always allowed in bidir a* when setting that costing option. I'm sure it's got smth to do with a 2nd pass.

Also, there's no actual gurka test which we might want to add one using an actual algorithm.

**Comment by nilsnolde** [comment]
Yeah, I think we caught another bug while hunting this one. What I can tell with 99% certainty is that without shortcuts all those routes will work as expected. I'll dig into it now.

**Comment by nilsnolde** [comment]
I seem to not really having the time to look into it. But maybe someone who's more dependent on proper truck routing could help out, e.g. @rochadt: would you be able to help out with this?

**Comment by xxhh1112** [comment]
t

**Comment by nilsnolde** [comment]
I'll also look into this in the next 1-2 weeks. What I'd suggest:
- make the shortcutbuilder configurable to conditionally break at weight/height/etc restrictions, controlled by the config somehow
- if the option is on, we break them up
- if the options is off, we record the lowest restriction of any of the actual edges and put that on the shortcut, but don't break it up

That way the default wouldn't introduce more shortcuts/edges, but people who care about those restrictions can do it too. 

Though I'm honestly not sure if it's not pretty identical to have that option on or off. If it's on there's more shortcuts, if it's off, truck would traverse more simple edges. Gotta be tested I think.
