### ISSUE TITLE
Using heading on one way highways

### ISSUE THREAD

**Issue by mkandulavm** [valhalla/valhalla#4323]
Hi

Currently when heading is provided, it provides routing on a 2-way road using it.
However, there are instances where it is desired where the heading can hint to use which of the parallel one-ways to use to compute the routing required.
Here are some examples:
1) low location precision
2) offset of GPS location  even if very accurate (this seems to be happening to me on some devices.. ) overlaps to the other parallel one-way road

Is this possible currently ? Can I know some hints to implement if not ?

Thank you.

**Comment by nilsnolde** [comment]
> where it is desired where the heading can hint to use which of the parallel one-ways to use to compute the routing required.

I don't really understand the question tbh. You mean like multi carriageways, where each direction is digitized? And it selects the wrong direction, despite setting the heading appropriately? Or you mean totally unrelated roads which run in parallel?

Maybe you can draw a pic of what the problem is, so there's no misunderstanding.

**Comment by kevinkreiser** [comment]
yeah the hint about gps being low accuracy is a clue here. you should use the radius parameter and set it to something related to the accuracy of the gps (typically also measured in meters). this will allow the edge finding bit to consider both directions of a one way (since both will be in the radius) and pick the one that matches the heading you are providing

**Comment by mkandulavm** [comment]
@kevinkreiser thank you. Setting the radius has solved the issue. This was exactly what I needed.

**Comment by nilsnolde** [comment]
Still leaves me a bit puzzled @kevinkreiser: if a heading is set but no radius and the closest edge is in the opposite direction of the heading, we select that segment? I figured that filter would also apply for radius=0.. Maybe I should take the minute to look into the code :sweat_smile:
