### ISSUE TITLE
deprecate auto to car?

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4453]
I _still_ often enough write `car` instead of `auto`.. (not being a native English speaker) I'd never think about actually saying auto out loud (on German though obviously I would:)). Maybe there was a reason in the first place to name it like that?

**Comment by kevinkreiser** [comment]
why did we do it? i dont remember! in english there is a very very slight difference though

automobile is always a generic term that can refer to lots of types of motor vehicles: sedans, suvs, jeeps, vans, trucks, whatever

car is used the same exact way, as a synonym for automobile. however it has a second meaning which is sequestered to just sedan.

this might sound like bs so let me clarify with an example:

you and your wife are getting ready to leave for work. in the garage you have a sedan and an SUV. you both walk into the garage and you look at her and say, "which one are you taking?" she says to you, "i'll take the car today." in this scenario you know she means the sedan and not the SUV.

in my opinion auto(mobile) is slightly better because its unambiguously generic where as car could be thought to mean only sedan (in the context of other options). also i think its not hurting anything. you might be the first person that has mentioned it :smile: my vote would be let it as is but maybe my english is different than the rest of the english speaking world hard to say haha

**Comment by nilsnolde** [comment]
My confusion is actually stemming from the fact that "auto" is so generic, while we also have "truck". Though it might be that you originally thought to not even have a truck costing and do it all with "auto", which is what I might've seen in https://github.com/valhalla/valhalla/pull/4430.

> you might be the first person that has mentioned it

Really?! Hahah I'd have expected many many more people to comment on that :D If that's the case, never mind, then it's maybe me..

**Comment by kevinkreiser** [comment]
i thought you might ask about truck and because i love language stuff so much i cant help but reply. truck is a hugely overloaded word, it can fit into our definition of auto when you are referring to what are also called "pickup trucks", which is what i meant above. but indeed there are dump trucks, cement trucks, fire trucks and of course tractor-trailers which can be called trucks though this mostly refers to the tractor part technically rather than to the whole thing. i think this is why osm uses heavy goods vehicle since its generic but properly communicates the distinction that its a class of larger, typically load carrying vehicles. we probably could have picked a better word than truck. communication is hard :smile:

**Comment by nilsnolde** [comment]
Yeah OSM is definitely good at naming stuff, especially compared to their routing data “competitors”, benefit of the collective mind I guess:) though I remember the discussion about what’s a “vehicle”, which proved that language can be very contextual and not absolute as it should be.
