### ISSUE TITLE
`IsClosed` evaluating the wrong direction on reverse search

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#4456]
E.g. in 

https://github.com/valhalla/valhalla/blob/d7b0dccdc33ac3a7cf214a88c1f43af9d0790e4a/src/thor/bidirectional_astar.cc#L337-L343

On reverse search it seems we evaluate the closed state of the _expanded_ edge, not its opposing, which is what we're really interested in. That's the same across the board for reverse trees, so I wonder if that was intentional. I just can't understand why.. The function eventually checks the state of traffic for that exact edge, not its opposing:

https://github.com/valhalla/valhalla/blob/d7b0dccdc33ac3a7cf214a88c1f43af9d0790e4a/valhalla/baldr/graphtile.h#L788-L792

**Comment by kevinkreiser** [comment]
https://github.com/valhalla/valhalla/pull/2846/files

so all that stuff came in one pr and interestingly it looks like it was correct in the allowed method (specifically the allowedreverse method) but then not correct in the expandreverse. i am guessing we dont get bitten by it because allowed reverse happens when it must and protects us from missing it in the reverse expansion.

**Comment by nilsnolde** [comment]
this was fixed recently
