### ISSUE TITLE
Out of RAM

### ISSUE THREAD

**Issue by jjoloka** [valhalla/valhalla#4464]
Hello.

With multiple requests to valhalla (20-25 consecutive requests, one after another), the following situation occurs:
![image](https://github.com/valhalla/valhalla/assets/9629917/8c6e5fad-54cc-43b2-a934-fc765ca11e5b)
In the server out of RAM. Which is not cleaned. Have to restart Docker container.

We use /trace_route

**Comment by ImreSamu** [comment]
> With multiple requests to valhalla (20-25 consecutive requests, one after another), the following situation occurs:

Can the issue be replicated, or is it entirely unique?

Could you provide precise details to replicate the issue?
- Specifically,  which Valhalla Docker,
- What server, exactly what CPU, how much RAM? And what is the RAM per CPU ratio?
- What are the types and lengths of the traceroute queries? (Are they city-wide or cover half the country?)
- Additionally, anything else that might be important (such as Docker version).

If the data is not confidential, could you create a simple script from the 25 requests that replicates the problem?
Or if the data is sensitive, could you anonymize the requests?

**Comment by nilsnolde** [comment]
Dup of https://github.com/valhalla/valhalla/issues/4322 pretty sure

Rules to live by when writing issues:
- be informative and to the point (highly subjective though)
- provide **minimum** examples if examples are needed
- copy JSON as text into the issue, not as files, unless it's completely impossible to reproduce the issue less than 100s of lines
- never screenshots of text pls, text is there to be copied not photographed

Those rules are important so that you help people to help you. Remember no one owes you anything and we're not paid to provide any support, our only allegiance is to the project, so you'll need to put some effort in the first place. If you don't, why would we?

I think that goes into an issue template.

**Comment by jjoloka** [comment]
> Can the issue be replicated, or is it entirely unique?

Yes, the data is unique; there are 25,000 routes in our database (with points). We need to calculate the mileage.

> * Specifically,  which Valhalla Docker,
Yes. Valhalla work in Docker. Now the container has been trimmed according to RAM.
[valhalla.json](https://github.com/valhalla/valhalla/files/13712684/valhalla.json)
[docker-compose.zip](https://github.com/valhalla/valhalla/files/13712583/docker-compose.zip)

> * What server, exactly what CPU, how much RAM? And what is the RAM per CPU ratio?
Cloude server - 12Gb Ram, 4 core-CPU  Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz

> * What are the types and lengths of the traceroute queries? (Are they city-wide or cover half the country?)
The length of the traceroute is up to 350-400 kilometers.
![image](https://github.com/valhalla/valhalla/assets/9629917/df738877-cc4d-4d6a-b612-d5c019461d76)
[test.csv](https://github.com/valhalla/valhalla/files/13712946/test.csv) - 50 test json data in export
[error.json](https://github.com/valhalla/valhalla/files/13712846/error.json)   - error reaquest:
![image](https://github.com/valhalla/valhalla/assets/9629917/5b585605-2aaf-40ed-aee7-fb09e3caf70e)

**Comment by nilsnolde** [comment]
Back to the point: #4322 explains what's happening (or not happening). Just needs someone with some more knowledge of the map matcher to take a quick look. We'll track progress there.
