### ISSUE TITLE
Router ignores access=no barrier

### ISSUE THREAD

**Issue by Kamerijker** [valhalla/valhalla#4534]
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_foot&route=50.74176%2C4.29074%3B50.74190%2C4.29528#map=17/50.74208/4.29326&layers=N

The Valhalla foot router ignores a barrier coded access=no on the referenced path in openstreetmap.

**Comment by kevinkreiser** [comment]
we allow routing over access=private iirc because it makes sense for long lanes that go back to houses where the person that lives there wants the route to contain this beginning or ending geometry.

i see that afterwards you re-tagged the stuff with access=no and foot=no. this all happened in the last 10 days. with the tags you added the router wont allow access im pretty sure. the problem is more that we dont update the data every day on this server. @nilsnolde handles it so he can say what the update cadence is there.

**Comment by nilsnolde** [comment]
Didn’t have a look on the server in a few days, I recently did lots of updates on that server, it’s possible smth broke (incl the notification that it did break possibly;)). But usually it’s close to 1 day update cycle, like 36 h or so, it just builds and builds and builds on a semi-powerful machine:) new code though is very irregular, rather when I feel like it.

**Comment by nilsnolde** [comment]
Yeah, indeed the planet update failed since I updated the server, forgot re-install pyosmium to for when upgrading the OS.
