### ISSUE TITLE
Bus error and Min Requirements

### ISSUE THREAD

**Issue by akifaktas** [valhalla/valhalla#4612]
Hello,

I'm working with the Planet file.

I was able to complete the valhalla_build_config, valhalla_build_admins operations successfully. However
valhalla_build_tiles -c valhalla.json planet-latest.osm.pbf
When I use this command, I first try to process for 10-15 minutes and then I get a bus error.

`ubuntu@valhallaserver:~/data$ valhalla_build_tiles -c valhalla.json planet-latest.osm.pbf`

```
2024/02/27 09:38:15.02355 [INFO] Start stage = initialize End stage = cleanup
2024/02/27 09:38:15.03160 [INFO] Parsing files for ways: planet-latest.osm.pbf
2024/02/27 09:38:15.03472 [INFO] Parsing ways...
Bus error (core dumped)
```

I purchased a used server for this job. My HP Gen8 server contains 352GB of RAM (DDR3) and 24 CPUs x Intel Xeon CPU E5-2695 v2 @ 2.40GHz. I virtualized it with VMware and assigned 24 cores, 1.5 TB disk, and 150GB of RAM for setting up Valhalla. However, I still encounter this error.

If this error is related to hardware:

Should I buy a new disk?
Should I switch to DDR4 RAM?
Should I upgrade to a more powerful and newer generation processor?
What kind of system should be set up within 24-36 hours to be able to run the planet file in Valhalla?

Thank you very much.

**Comment by nilsnolde** [comment]
on server specs that's WAY overprovisioned for valhalla. the more threads you have the better, but RAM isn't too important since it's mostly mmapping. the first 12 hours will be pbf parsing on a single thread, only higher clocked processors will give you an edge there, 2.4 GHz is on the low side. 1.5 TB could be too little, see https://github.com/valhalla/valhalla/issues/4548. with 24 threads you should easily build in 36 hours, probably rather 30.

what does your disk say when you hit the bus error?

**Comment by nilsnolde** [comment]
The relevant PR was just merged so with newest master it should work with your server. Feel free to re-open if not.
