### ISSUE TITLE
way_nodes.bin has an incorrect size for type

### ISSUE THREAD

**Issue by karthiksk5111** [valhalla/valhalla#4615]
hi team,

I encountered a problem while trying to generate routing for a planet file today. The error message I received was:

"....../planet/valhalla_tiles/way_nodes.bin has an incorrect size for type Aborted (core dumped)"

it appears that the issue might be caused by an incorrect size for the file 'way_nodes.bin' within the 'valhalla_tiles' directory. I have confirmed that there is enough disk space available on the system.
Can you please help me resolve this issue?

**Comment by gknisely** [comment]
@karthiksk5111 closing for now due to no response.  Let me know if you are still having issues.

**Comment by mkandulavm** [comment]
hi 

I am getting same error when  processing the planet with the latest from master for release build.
The problem is I don't get this for debug build.

**Comment by gknisely** [comment]
Most likely you are running out of space due to the [sorting](https://github.com/valhalla/valhalla/blob/master/src/mjolnir/pbfgraphparser.cc#L5181) of the `way_nodes.bin` file during the `ParseNodes` phase in the tile building process.  It makes a copy of the `way_nodes.bin` file in order to sort it, so you need to have enough space and then some to do that logic.
