### ISSUE TITLE
Memory mapping with multiple threads does not share tile memory

### ISSUE THREAD

**Issue by ktnr** [valhalla/valhalla#4736]
# Observed behavior

When running valhalla with multiple threads, memory increases linearly with the number of threads, even when the *exact same requests* are fired repeatedly. It happens with route and matrix requests and for the native and gis-ops image [[1]](https://github.com/gis-ops/docker-valhalla/issues/81#issuecomment-1343999540), [[2]](https://github.com/gis-ops/docker-valhalla/issues/58#issuecomment-1343374763). This suggests that each thread independently maps/allocates memory for the tiles, which was also observed by @nmalasevic in https://github.com/gis-ops/docker-valhalla/issues/63#issuecomment-1058269585 and https://github.com/valhalla/valhalla/issues/3556. 

Memory usage limit is capped by `max ram requirement of the tiles * server_threads`. 

For example, an OSM extract of Germany is roughly 5 GB and the valhalla tiles are about the same size. Tested on a machine with 128 GB of RAM:
- the same matrix request with 150 locations all over Germany, fired multiple times
  - 1 thread: Memory usage maxes out at around 5 GB
  - 4 threads: Memory usage maxes out at around 20 GB
- the same matrix request with 50 locations only within a subsection Germany, fired multiple times
  - 1 thread: Memory usage maxes out at around 1.2 GB.
    <details><summary>Memory usage</summary>
    
     I fired 7 single requests sequentially and then 12 requests at the same time. The request were exactly the same. 
     
     We see a baseline memory consumption of 1.2 GB (tile memory) and then temporary allocations of about 0.3 GB (temporary runtime memory). As expected the temporary algorithm memory is freed again after the calculations and the tile memory remains in use for subsequent requests (even after an hour of idle time it is still reserved, which is fine when used with a single thread).
    ![image](https://github.com/valhalla/valhalla/assets/11096873/e5e8ec60-b90b-41bb-a748-a850526756dc)

    
    </details>
  - 4 threads: Memory usage maxes out at around 4.8 GB
  
    <details><summary>Memory usage</summary>
    
     I fired 7 single requests sequentially and then 12 requests at the same time. The request were exactly the same.
     
     With the first request, memory usage is at 1.2 GB. With each requests it increases by another 1.2 GB until it reaches 4 threads * 1.2 GB = 4.8 GB at request number 4. Subsequent requests do not result in further memory increases.
        
    ![image](https://github.com/valhalla/valhalla/assets/11096873/2ef87a99-7e19-41a9-a130-5eb18c31ca3c)

    </details>

The changes in matrix memory alloactions from https://github.com/valhalla/valhalla/issues/4064 did not change the overall behavior. Similar behavior can be observed with route requests, but with lower total ram usage, depending on the distribution of locations. 

# Expected behavior

The behavior for `server_threads=1` is fully as expected.

For `server_threads > 1`, I would expect that the memory usage does not substantially increase proportional to the number of threads, because the tile data must only be accessed in read-only mode and can be shared across threads. Granted, some memory mapping overhead and some fixed and temporary runtime overhead for the algorithms. However, not to the extent that it exceeds the .osm/tile-dir size by multiples.

For example:
- the same matrix request with 150 locations all over Germany, fired multiple times
  - 1 thread: Memory usage maxes out at around 5 GB
  - multiple threads: Memory usage maxes out at around 5 GB
- the same matrix request with 50 locations only within a subsection Germany, fired multiple times
  - 1 thread: Memory usage maxes out at around 1.2 GB.
  - multiple threads: Memory usage maxes out at around 1.2 GB or at most at 5 GB (the extract/tile size), but it should not substantially and permanently exceed 5 GB, even if 20 threads were used.

# History

Similar issues were observed before and suspected to be memory leaks. It turned out that was not the case. The memory increase only occurs when multiple threads are used, see https://github.com/gis-ops/docker-valhalla/issues/81#issuecomment-1343999540.

In the hopes of helping to pin-point the root-cause, I collected info you communicated to explain and mitigate the observed behavior:
- @kevinkreiser, because it happens for the exact same request, it directly contradicts the expected behavior you communicated in https://github.com/valhalla/valhalla/issues/3556#issuecomment-1061971041
  > if you send the same 20 requests over and over the OS will only ever page that data into ram that those 20 requests intersect, so it is easy to see why that wouldnt cause ram to increase. however if you send tons of different requests that touch all parts of your data extract then you should expect to see the OS page stuff in until it has to start swapping between ram and FS cache.

- Kevin, you have suggested that, [because of the advanced memory mapping you use, the memory usage is not reported correctly by the OS, overestimating actual memory usage](https://github.com/gis-ops/docker-valhalla/issues/81#issuecomment-1343438368). When I limit the memory usage in a valhalla container with a single thread, I can fire unlimited requests and the container is stable. When I run the container with `server_threads > 1`, and fire the same request as for the single thread container, it crashes with OOM errors:
  <details><summary>OOM Errors</summary>
  
  ```
  May 17 08:03:06 dantzig kernel: [779180.091955] Memory cgroup out of memory: Killed process 2039568 (valhalla_servic) total-vm:146990944kB, anon-rss:2061144kB, file-rss:2400672kB, shmem-rss:0kB, UID:0 pgtables:23516kB oom_score_adj:0
  root@dantzig:~# dmesg | grep -i oom
  [779180.091762] valhalla_servic invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=0
  [779180.091776]  oom_kill_process.cold+0xb/0x10
  [779180.091805] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
  [779180.091810] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=docker-1ecdb0f5d892284360d78c23b74d035e5222641ad76ceaab7da8ae4bbad3b936.scope,mems_allowed=0,oom_memcg=/system.slice/docker-1ecdb0f5d892284360d78c23b74d035e5222641ad76ceaab7da8ae4bbad3b936.scope,task_memcg=/system.slice/docker-1ecdb0f5d892284360d78c23b74d035e5222641ad76ceaab7da8ae4bbad3b936.scope,task=valhalla_servic,pid=2039568,uid=0
  [779180.091955] Memory cgroup out of memory: Killed process 2039568 (valhalla_servic) total-vm:146990944kB, anon-rss:2061144kB, file-rss:2400672kB, shmem-rss:0kB, UID:0 pgtables:23516kB oom_score_adj:0
  ```
  and from `docker container inspect`
  ```
  State
  Dead false
  Error
  ExitCode 0
  FinishedAt 2024-05-17T08:03:06.293958961Z
  OOMKilled true
  ```
  
  </details>
  
  To me, this suggest that memory is actually reported correctly. Either way, it crashes containers, the process and makes valhalla impractical to use with multiple threads on a europe or planet extract.
- @nilsnolde, you suggested to [use tar files for more efficient memory usage](https://github.com/valhalla/valhalla/issues/3556#issuecomment-1385862581), which [your images uses by default](https://github.com/gis-ops/docker-valhalla/issues/81#issuecomment-1359435350). Per https://github.com/gis-ops/docker-valhalla/issues/81#issuecomment-2046129267, I tried the default and set it explicitly, yet the memory increase still occurs.

# Related issues

The described behavior is the same as/similar to and I think these issues should still be open:
- https://github.com/gis-ops/docker-valhalla/issues/81
- https://github.com/valhalla/valhalla/issues/3556
- https://github.com/gis-ops/docker-valhalla/issues/63
- https://github.com/gis-ops/docker-valhalla/issues/58

# Steps to reproduce
Please refer to: https://github.com/gis-ops/docker-valhalla/issues/81.

# Version info
Running the latest native and gis-ops valhalla images on Ubuntu 22.04 with Docker 25/26.

**Comment by kevinkreiser** [comment]
there are so many things in this issue its hard to know where to begin :smile: 

let me start with basics around how the library works wrt to allocations. there are largely two classes of allocations:

- ones involving the graph data itself and making that accessible to the cpu
- ones that occur as a result of a given graph traversal algorithms implementation/use-case

thus far, the explanations/justifications you linked are primarily concerned with the first of those two. so before we go further lets make sure we understand that one as its the same regardless of what you are doing with the library.

so the graph storage interface (graphreader) has two primary modes. one in which it memory maps a tar file (thus memory mapping and using the tar file are the same thing, im not sure if you understood that based on the above). in this mode the the OS reports will report usage over 100% if the application has multiple threads or processes accessing the same memory map. its just like how top reports cpu usage over 100% when you run multiple threads/processes. its not actually using more than 100% ram or cpu as that isnt actually possible. 100% is relative to the units the os uses to report on that metric. this is just my inference from experience i have not looked for documentation on this.

anyway, the other mode we have is having individual graph readers load individual tiles from disk rather than using a memory mapped single tar file. in this mode any instance of a graph reader will own its own copy of an individual tile in memory (it wont share address space with other threads/procs to get at the same data). so if you ran your test in this mode, then i could see you getting OOM-killed because of that. if you were using the tar then you can leave graph storage out of the discussion.

then we can move on to allocations which occur as a result of graph traversal algorithms. matrix is the heaviest one (though map matching is somewhat heavy in a different way). wrt matrix algorithms we have a couple implementations and those have different memory characteristics. it might be that you are doing matrix requests which are too large for your configuration. 128gb of ram is a lot but if you run 32 threads and have 32 simultaneous reasonably large matrix requests you could run yourself out of ram. it seems to me though that you are saying ram increases for your types of requests and eventually gets OOM killed. this is also possible, i have no looked into via valgrind but that seems like the next step.

also with respect to this comment:

> Either way, it crashes containers, the process and makes valhalla impractical to use with multiple threads on a europe or planet extract.

i would say that there are 100's of companies running it in exactly this way without any significant operational issues, i myself have been running it in production for 3 years straight and have only been paged for it 1 time. it depends on the requests and it depends on the data and it depends on which commit you are running. as im sure you know software is complex.

so at this point we need to reproduce it and then we need to send it through valgrind to see if we can detect any leaks that arent false positives. i see you linked an issue in gis-ops. im truly disinterested in debugging anything related to that image. maybe its maintainers would be but i want to see steps that dont involve that container. its fine for me if thats as simple as:

- build tiles with the default config for the european extract off geofabrik
- make a tar with this command
- update the config to use the tar
- start valhalla_service with n threads
- then hit it with this request n times or whatever

something like that is good enough for me. then i can build that stuff locally and i can valgrind it without worrying about docker or whatever the conveniences in that image are doing (not that the image is bad, by all means use it, its just not a place to start debugging)

**Comment by ktnr** [comment]
Thanks for the detailed response, very much appreciated. I did not want to suggest that Valhalla is not usable in production, just that it has very demanding RAM usage for calculating large matrices on wide geographic regions, especially when parallelized.

Also I don't think its a memory leak issue, which I have confirmed by running valgrind: clean. 

I was questioning whether the memory sharing across threads works as expected. Because for large requests, memory and swap will be filled until the system crashes. By now, I have understood that the memory consumption most likely comes from the runtime components of the matrix algorithms. Regarding that I have observed different strange behavior, which I will report in a separate issue/discussion. 

From my side, this thread can be closed. Thanks again for the detailed answer, which was indeed helpful.

**Comment by kevinkreiser** [comment]
> By now, I have understood that the memory consumption most likely comes from the runtime components of the matrix algorithms.

correct, the only sharing is for the graph data itself (since its read only this is easily possible) not the intermediate storage that is needed for the algorithms inner workings. the only thing that could be done there would be a memory pool that could be shared but this would be a complicated design with nonobvious benefits imho
