### ISSUE TITLE
Avoid this stairs?

### ISSUE THREAD

**Issue by hup333** [valhalla/valhalla#4820]
Why are valhalla taking the long route?
![image](https://github.com/user-attachments/assets/d0349064-8d7a-4cc2-b885-4e1481198bfd)
https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=9.472644925117494%2C55.478917259723815%2C9.473964571952822%2C55.478473465765546

**Comment by kevinkreiser** [comment]
quite a bit of strange tagging here with cycleways and foot access but the biggest problem is this way is tagged as a driveway but its clearly a connector: https://www.openstreetmap.org/way/858931381

it should probably modifed so that only the part that deadends is marked as a driveway and the rest is tagged as service or whatever makes the most sense.

**Comment by kevinkreiser** [comment]
i just fixed the way on osm, have a look at it to see what i mean

**Comment by hup333** [comment]
Oh, that small part of the road
