### ISSUE TITLE
/expansion dijkstras add previous cost and duration

### ISSUE THREAD

**Issue by baileyheading** [valhalla/valhalla#4848]
When using /expansion I wanted to interpolate the line segments (in python) which required me to know the time for the start and end of the line segments given I don't have the paths to reach each line segment. Would anyone be against adding this into the response?

Something like this works in my build although I'm unsure if there are some edge cases where it gives an unexpected result. I couldn't find a way to use the previous edge id (in the response) because I think the expansion data has a lot of other stuff in there making it impossible to use in this way.

dijkstras.cc

```
    sif::BDEdgeLabel prev_pred = pred.predecessor() == kInvalidLabel ? pred : bdedgelabels_[pred.predecessor()];
    float previous_duration = pred.predecessor() == kInvalidLabel ? pred.cost().secs : prev_pred.cost().secs;
```

While I'm at it, are there other ways to get smaller line segments and time intervals I should be considering instead?

Edit: when it's invalid, does that mean it should be zero? or are there other possibilities for when it's invalid edge label?

**Comment by chrstnbwnkl** [comment]
A `dedupe` option was recently added to the expansion endpoint (#4728). With that you should be able to use the previous edge ID to uniquely identify a feature in the collection and get the least cost/duration to that edge. 

Regarding your other questions, `DirectedEdge` is the smallest unit already, and the only case where invalid labels are used here is to indicate an edge has no predecessor because it's correlated to the input location(s).
