### ISSUE TITLE
Map matching fallback for non-existing roads e.g. driveways

### ISSUE THREAD

**Issue by bjtrounson** [valhalla/valhalla#4964]
Hi

I know I'm probably shooting into the dark with this but, I'm doing some matching of some routes that don't always go on roads that is in OSM like driveways in rural areas. I'm using these routes in MapLibre Navigation using the OSRM format with instructions. 

I'm noticing that these ending / starting driveways get cut off the map matched route. I'm wondering whether there is a way to get these last parts of the route even though they aren't matched. I'm also not to concerned about whether there are instructions for these driveway segments of the route.

I'm assuming I will probably have to either update OSM with these driveways themselves or create my own PostGIS system that has them to match these driveways.

My main end goal with this is not to have a matched route as our route already follows the road quite nicely. I'm mostly interested in obtaining the instructions for most of the route excluding the driveway parts.

If there is anyone that has any ideas or solutions for this it would be greatly appreciated. 

This is the current route:
![image](https://github.com/user-attachments/assets/b870456e-97eb-4a55-8b5a-6dc6d8676ef9)

This is after matching:
![image](https://github.com/user-attachments/assets/03aaec13-12a7-42de-afc4-45e4d6666766)

**Comment by kevinkreiser** [comment]
from your description im just not sure what it is that you actually want. you said you dont care about instructions based on the unmapped part and you said you dont want to do matching on the unmapped part. what would you like to happen? you just want that extra shape point at the beginning/end of the route where its off road so that the blue line in the second picture draws off road to the start/end point? if so you can do you that client side. sorry im just having trouble understanding what you'd like to see in the output.

**Comment by bjtrounson** [comment]
Yeah that's the route I've ended up going with. I couldn't find anything that could add the extra parts I needed in the OSRM format so I'm looking at creating my own. Was mainly just looking for suggestion or options as I couldn't find much else for the OSRM format for the navigation stuff apart for the OSRM API output.

Thanks for your help
