### ISSUE TITLE
Proposal for changes to make Valhalla more mobile-friendly

### ISSUE THREAD

**Issue by mtehver** [valhalla/valhalla#6]
I have been evaluating Valhalla for offline routing on iOS/Android/Windows Phone targets and 
with several changes got it working. Some of the changes I had to do were technical (missing #includes, for example), while other were workarounds due to compiler/platform limitations. The main issue (that is not directly Valhalla related, more like our build system limitation/convenience issue) - we really do not want to use boost libraries that require linking. Header-only boost libraries are fine. The boost libraries that require linking are: regex, filesystem, date_time, system.

The first thing I noticed that though you require C++11 compiler, you still use boost::regex instead of std::regex. Is there are a particular reason to do this? 

Another general suggestion - perhaps it would be a good idea to use abstract interface for tile loading?
I made some quick changes to graphreader.cc and graphtile.cc in baldr to use zip archive for tile storage, instead of file system. This allowed me to get rid of boost::filesystem dependency also. 

I can prepare pull requests with the changes I made, the question is which of the following changes would you accept:
- Use std libraries where possible instead of boost libraries
- Add common header that is included to fix platform/compiler specific issues
- Implement GraphStorageHandler interface that has FileSystemStorageHandler logic copied from current graphreader and graphtile

**Comment by kevinkreiser** [comment]
This all sounds good but the bit about regex. The reason we use boost regex is because 4.8 gcc is what comes with ubuntu trusty by default which is one of our primary target platforms. We could write some helper string functions to do the work that regex is being used for until we get off of trusty as a work around.

Wrt boost we'd like to remove as much of those deps as possible too but yeah boost Filesystem is just so convenient... except when cross platform build systems can't get easy access. 

Anyway PR's are always welcome we would love to get your changes in.

**Comment by kevinkreiser** [comment]
This all sounds good but the bit about regex. The reason we use boost regex is because 4.8 gcc is what comes with ubuntu trusty by default which is one of our primary target platforms. 4.8 has some parts of regex unimplemented. We could write some helper string functions to do the work that regex is being used for until we get off of trusty as a work around.

Wrt boost we'd like to remove as much of those deps as possible too but yeah boost Filesystem is just so convenient... except when cross platform build systems can't get easy access. 

Anyway PR's are always welcome we would love to get your changes in.

**Comment by dnesbitt61** [comment]
recent work to remove boost dependencies as well as other work to ease mobile implementations have been completed. We can open new and more focused issues as needed
