### ISSUE TITLE
No path could be found from A to B but is found from B to A

### ISSUE THREAD

**Issue by kei42** [valhalla/valhalla#640]
Hello,

Here is an example: 
- [not found](http://valhalla.github.io/demos/routing/#loc=18,43.627021,7.035550&locations=[{"lat":43.625,"lon":7.06},{"lat":43.627,"lon":7.033}]&costing="auto")
- [found](http://valhalla.github.io/demos/routing/#loc=15,43.626508,7.046635&locations=[{"lat":43.627,"lon":7.033},{"lat":43.625,"lon":7.06}]&costing="auto")

It also occurs with this point: {"lat":43.69512893737303,"lon":7.264590617269277}

Note that using the following link on OSM it works:
https://www.openstreetmap.org/directions?engine=osrm_car&route=43.6250%2C7.0600%3B43.6270%2C7.0330#map=15/43.6267/7.0479

Do you have any idea why it fails ?

Thanks

**Comment by kevinkreiser** [comment]
Its because that area is gated off but drivable. Basically the algorithm finds that gated area and uses it as the destination. When we try to find the destination we cant because the gates block access. Other software will travel up to the gates and stop. We are working at solving this problem currently tracked here: #58

**Comment by kei42** [comment]
Thanks for your quick reply
