### ISSUE TITLE
Isochrone polygons are shown in levels of gray instead of colors

### ISSUE THREAD

**Issue by BFutterer** [valhalla/valhalla#669]
I just changed "polygons: false" to "polygons: true" in the demo index.html for isochrones, to get polygons instead of isochrones like it is described in the Isochrone service API reference. But the polygons are shown in levels of gray, although the isolines are colored. This happens if I use the default colors as well as when I define my own colors. Is there a way to get them also with colors?

**Comment by kevinkreiser** [comment]
it seems the styling for leaflet geojson polygons uses `fillColor` instead of `fill`. you can work around this in the javascript by doing something like this: https://github.com/valhalla/demos/commit/54a7cc2321d915a4ed46544bba3af83e378ebf58#diff-35f4f770bba3bfede04b5ea7912ef8f6L68

id like to fix this on our side but it could be that someone is relying on it now as `fill`. if the docs dont say we return it as `fill` then i think we are safe to just fix it on the server side.

**Comment by kevinkreiser** [comment]
ok so the docs dont say what properties we include. i think the issue is that we are trying to please two masters here. geojson.io vs leaflet:

leaflet uses: `fillColor` and `fillOpacity`
geojson.io uses: `fill` and `fill-opacity` (i think this because this is what we currently return)

i think the fix is simple we just include both. ill make the change quickly
