### ISSUE TITLE
chunnel train

### ISSUE THREAD

**Issue by gknisely** [valhalla/valhalla#687]
Favor chunnel train over ferries.  Check costing.

**Comment by dnesbitt61** [comment]
This is due to complex restrictions. Returning false from DynamicCost::Restricted allows London to Paris to succeed taking the Eurotunnel Shuttle. Perhaps this relation is causing the issue: http://www.openstreetmap.org/relation/2928437. Since you can use the Eurotunnel Shuttle as a through location I think that implies that the complex restriction includes it.
