### ISSUE TITLE
How to load custom GTFS on local Valhalla build?

### ISSUE THREAD

**Issue by araichev** [valhalla/valhalla#691]
Hi folks, 

I recently installed Valhalla on my Linux machine.
Do you know how i can install a custom GTFS feed to do some transit routing?

**Comment by dnesbitt61** [comment]
Valhalla only accepts transit information through Transitland.

**Comment by araichev** [comment]
Ah, so do i give Transitland my custom GTFS feed, which might be for a fictional network, and then somehow import it into my local Valhalla installation?

It would be a nice feature for Valhalla to build its graph from any OSM tiles *and* any GTFS feeds, which is something that Open Trip Planner allows.

**Comment by dnesbitt61** [comment]
That likely wouldn't work - it has to go through validation and then be moved to the production system. Not sure if you can run your own instance of Transitland and import it then you would have to run the valhalla_build_transit program prior to creating Valhalla tiles.

We hope to publish a protocol buffer format for a tile set that Transitland will output and Valhalla will import. One could write a GTFS to protocol buffer transform and then the data would be able to be ingested into Valhalla. This is not a high priority for us but we could post an issue in Valhalla and ask for contributions.

**Comment by araichev** [comment]
Thanks for the information.
Yes, please post an issue if you can.
If it is a matter of writing a program to convert GTFS to protocol buffer, then i might be able to help.

The way i see it, to have a multimodal routing engine of one's own, one needs to be able to load whatever OSM tiles and whatever GTFS feeds one likes.

**Comment by dnesbitt61** [comment]
Closing - included in issue #699

**Comment by drewda** [comment]
@araichev FYI, you do currently have the option to run your own local instance of the [Transitland Datastore](https://github.com/transitland/transitland-datastore), import hypothetical GTFS feeds into it, and run valhalla_build_transit against it.

We don't provide support for this option -- it defeats the purpose of having a single centralized Transitland Datastore that aggregates data from around the world -- but we do know that some people do run their own Transitland Datastore and Valhalla instances in order to work with hypothetical GTFS feeds.

**Comment by araichev** [comment]
Thanks, @drewda.  
I'll look into that option.

**Comment by mcheung610** [comment]
@drewda will it be possible to host a transitland proxy? It could bring a lot of benefits in term of scaling out the Transitland Datastore.

**Comment by Rui-Santos** [comment]
> We don't provide support for this option

@drewda You don't even provide actionable documentation to run it on a workable state, much less support. Transitland as an opensource project is a joke. I hope you like your API servers getting hammered by Valhalla when people try to build transit.

**Comment by drewda** [comment]
@Rui-Santos first, insults have no place here or on any other open-source forum. I appreciate seeing your code contributions to Valhalla, but being intentionally rude toward others is never appropriate.

Please note that Transitland is an open and shared project run by volunteers, now that Mapzen has shut down. We try our best, but do have limitations on what's possible at present. We are exploring scale-able ways to distribute Transitland data as static files. In the meantime, Transitland users will unfortunately be constrained in the number of API calls they can make. Per-second API rate limits are enforced by proxies in front of the application servers. We advise users to pace their requests by using a queue or a similar approach in their own code.

As always, Datastore itself is open and documented at https://github.com/transitland/transitland-datastore#technical-documentation Contributions to the code and that documentation are welcome.

**Comment by Rui-Santos** [comment]
@drewda Beauty is in the eyes of the beholder, as they say, and so is uglyness. It's just what I feel. Transitland does everything to keep anyone else from running a similar service. You say it very weel: now that Mapzen has shut down. Now what?  What will happen when you don't get the chance or the sponsorship/money to run your service anymore? You don't even make an effort to limit the API calls people make to your service by providing geographically restricted feeds. Is it death that you wish upon Transitland? Your "open source" project can only be run in production by you. You want community contributions but you only want to take, you don't want to give anything back. I take it you never heard about the benefits of decentralization. You go down, transitland as a data source and as a project is dead. Because nobody else can run it usefully. You could have your data replicated in various other sites, and probably also get data from those sites, if they could only exist, and with that get some load off your API servers and redundancy. But no. You guys think centralized data is the way to go. And you are so wrong! Centralization is death, online. Only with replication/decentralization/federation you have a chance to survive. You don't even get new feeds online on a useful time. Your dispatcher has 5 changesets on the last 8 days, and yet, not even the oldest one, 7 days old by now, is live. That is no way to run a service like yours that depends on current data. You talk the talk, but talking is easy, actions are what really count, and Transitland's actions are all about shutting down whoever could be helping transitland. 

All that said, if you want to take what I say as an insult, so be it, that's out of my control. Like my grandfather used to say, if the suit fits...
