### ISSUE TITLE
Delivery of tiles on mobile

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#702]
I am trying to make myself familiar with valhalla, hence probably naive questions.

I would like to deliver the routing data to mobile devices in packages covering countries or parts of them. When delivered, the tiles from the neighboring countries should allow routing from one country to another. Is this possible?

As far as I can see, `valhalla_build_tiles` creates a folder that reminds of slippy map tile storage convention. Does it mean that I would have to import planet.pbf and later split the planet-provided tiles into smaller subsections that would correspond to the territory of the country + tiles on the border from neighboring countries to cover routing between territories next to each other? 

Or is it possible to generate tiles for PBF extracts country-by-country and later use them on device to cover routes between the countries?

PS: As a target platform, I am interested in porting valhalla to Sailfish OS (Linux distribution for mobile).

**Comment by dnesbitt61** [comment]
You could use one of the continental sized extracts from Geofabik and then deliver tiles for the countries (plus borders you need). But all tiles have to be generated in the same run of valhalla_build_tiles (e.g. you can't generate tiles for France and then generate tiles for Spain and have them work together). You can add several country sized extracts within a single valhalla_build_tiles call, but that can lead to duplicate edges at the country borders and possible undesirable behavior route routes crossing these shared borders.

**Comment by rinigus** [comment]
Thank you very much for the fast reply! Do you have some tools allowing me to get the names of the tiles that I need if I give a polygon defining the territory of interest?

**Comment by kevinkreiser** [comment]
> deliver the routing data to mobile devices in packages covering countries or parts of them. When delivered, the tiles from the neighboring countries should allow routing from one country to another

yep this is possible. there are definitely limitations with respect to granularity though. our tiling model is not mercator based. its simple lat,lon based (epsg4326). we have 4 sets of tiles.

level 0 is 4x4 degree tiles and contains the highest classed roads
level 1 is 1x1 degree tiles and contains the middle classed roads
level 2 is .25x.25 degree tiles and contains the lower classed roads and trails etc
level 3 is .25x.25 degree tiles and contains the transit network

as you can see we have some pretty coarse granularity where the network is pretty sparse. for european countries for example itd be pretty common for them to share some level 0 tiles.

> Does it mean that I would have to import planet.pbf and later split the planet-provided tiles into smaller subsections that would correspond to the territory of the country + tiles on the border from neighboring countries to cover routing between territories next to each other

your first intuition is correct. in order for countries to be routable between each other but from different packages of tiles, the tiles must have originally came form the same run of `valhalla_build_tiles`. the most common thing to do is run it on a `planet.pbf`. and then partition the tiles up that that spits out. in order to have fully working whole countries you will have some overlap in what tiles are included for each country. this is actually ok though a bit wasteful.

say a user downloads germany. this will be a tar file which the library natively supports loading. the tar will have all the tiles at all levels that intersect germany. because of the shapes of these tiles they will get routability in neighboring countries but not the whole country. if you then download the denmark tar you will get more tiles but some of them will be in the german tar. on the device you can simply `cat` the tars together and use valhalla to load the combined tar to get routability between denmark and germany.

**Comment by dnesbitt61** [comment]
We have C++ code to get a list of tiles given a bounding box. The AABB2 class in midgard is used to define a bounding box (use PointLL template). Then the midgard Tiles class can be used to get a list of tiles. This class is contained within the baldr TileHierarchy class (contains the tilesizes and a worldwide bounding box which defines the tile numbering system). You would have to call this method once for each tile hierarchy level and combine the lists. At some point we want to make a Python script to wrap this logic and make it easier to run, but we have not done that yet.

**Comment by rinigus** [comment]
@dnesbitt61 and @kevinkreiser: thank you very much for the detailed explanation! This info should be sufficient for now and I think I can follow your pointers to get what's needed for splitting the tiles into smaller chunks of data. If something is missing, I will ask again. Should we close the issue?

**Comment by dnesbitt61** [comment]
If you end up with something of general use that you'd like to contribute back, please do! For now, I'm closing this issue. Feel free to open another one if questions arise.
