### ISSUE TITLE
Requested Boost version

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#715]
The minimal required version of Boost libraries by Valhalla is 1.54. This presents a problem for porting it to Sailfish OS which has 1.51 version of Boost supported. As far as I could see, Boost version was set in commit https://github.com/valhalla/valhalla/commit/efac9535ac52c37d64a2b254c902cedc992c7ada . 

Now, I wonder whether it would be acceptable to reduce Valhalla's requirements regarding Boost to version 1.51? I have managed to run `valhalla_run_route` with 1.51. It required a small patch in one of the header files (inclusion of boost/shared_ptr.hpp). If you would consider reducing the version of Boost, I can test it with the full valhalla build using 1.51 and see if there are any other issues involved. Or maybe there is a feature that you use and which is available only from 1.54?

**Comment by kevinkreiser** [comment]
we'd consider it, the only reason we targeted 1.54 is because its what comes with ubuntu 14.04. the trick with boost is that the api is not gauranteed to stay the same from version to version. this might mean that if something changed from 1.51 to 1.54 you'll need to do `ifdef`s on the versions for certain pieces of code. i thought we used a pretty small set of functionality from boost but a quick grep shows:

ptree
filesystem
program options
regex
optional
lexical_cast
date time
hash_combine
iostreams
geometry
algorithm
format
python

anyway if you pr it with `>=1.51` we'll happily consider it.

**Comment by rinigus** [comment]
OK, then I'll work on getting full valhalla's port to SFOS first. This should allow me to check whether there are more compiling issues and if the functionality is somehow disturbed (as much as I can personally check). If all is fine, I'll submit PR to close this issue. Should probably take 1-3 days.

**Comment by kevinkreiser** [comment]
if all the tests pass that is a good enough indicator. my only real worry would be regex support. we were using boost regex only because gcc 4.8 didnt have a full implementation. now that we are on gcc 4.9 we dont need boost but others with older compilers will need it. the question is whether boost 1.51 has a fully implemented regex namespace or not. i guess you'll find out if the tests pass or fail!

**Comment by rinigus** [comment]
Looking at the boost changelog, I can see that the only changes in regex between 1.51 and 1.54 were fixing the bugs in 1.53: https://svn.boost.org/trac/boost/ticket/7744 https://svn.boost.org/trac/boost/ticket/7644 . But I'll do the tests to see if anything would come out

**Comment by kevinkreiser** [comment]
:crossed_fingers:

**Comment by rinigus** [comment]
I have been testing the route_service today on the system with 1.51 boost. I have not observed any problems. Will send a PR for review.

**Comment by rinigus** [comment]
No issues found during months of use. Closing since PR was accepted and had no side effects for a while .
