### ISSUE TITLE
Dynamic loading of tiles

### ISSUE THREAD

**Issue by rinigus** [valhalla/valhalla#726]
As a part of delivery of the tiles to mobile, I would like to store tiles as they are, in the folder. Advantage when compared to tar file is that the overlapping tiles between different countries would not have to be stored twice. If I would be using tar-file approach, I would have to cat the files together making it rather painful to manage (removal of one country would be more difficult). Since I already have a framework for delivering files and keep them referenced to countries (even overlapping should be fine), storing tiles in a folder is good solution for me.

However, as usual, I do have a question. If the new tiles are downloaded while `valhalla_route_service` runs, would they be recognized automatically? Or do I have to restart the service to initiate tile scan?

**Comment by dnesbitt61** [comment]
Generally the service would have to be restarted. Once a tile is in cache it will not try to re-read from file. We have a method to clear a cache, but no centralized method to make this happen everywhere.

**Comment by rinigus** [comment]
Thank you very much for the fast reply! I was suspecting it and would have to design the application accordingly. Since the reply is clear, should I close the issue?

**Comment by dnesbitt61** [comment]
Yes. If you (or we) can think of a design to allow hot-swapping tiles (or want to add this as a feature request) then a new issue can be opened with the design thoughts/requirements. Thanks!

**Comment by dnesbitt61** [comment]
@kevinkreiser informed me that your architecture might be just downloading "new" tiles from the same base tile set (e.g. have tiles in Germany and want to add tiles to support Poland). As long as the tiles are from the same tile build then you should be able to safely add in new tiles and route into them without reloading your server. Even downloading tiles that already exist (e.g. at the border of Germany and Poland) will be fine - since the tiles in cache should be the same as the newly downloaded tiles.

What is not supported is to download a new tileset from a different tile build and have the cache be cleared and the updated tiles used. We do not support mixing tiles from different tile builds.

**Comment by rinigus** [comment]
That's right, its from the same build. In short, I am going to generate the planet import and then split it into a subsets (by countries or, in case of Germany, by regions). User would be able to download the subsets and use them for offline routing on mobile. 

In respect to the ability of loading tiles. What would happen if the user deleted part of them, aka removed Poland in our example. I presume that the ones that are in the cache would be used, but whether the tile loading part would expect to see the tiles that just disappeared?

**Comment by kevinkreiser** [comment]
Youre right. Whatever was in cache would be used and whatever wasnt on disk anymore just wouldnt be routable anymore. The loading part is opportunistic, it will take whats there and happily work around what isnt. In other words, It doesnt remember what used to be there. Clearing cache clears the notion of that tile being on disk and it will check the disk before it tries to load it again.

**Comment by rinigus** [comment]
OK, thank you very much! That would make my life easier.

**Comment by chrisfosterelli** [comment]
> What is not supported is to download a new tileset from a different tile build and have the cache be cleared and the updated tiles used. We do not support mixing tiles from different tile builds.

Just to jump into this, I thought a major benefit of the tile dataset is that updating the tile dataset is much less costly since only updated tiles would need to be resync'd ('Updatability' was one of the listed reasons in the _Why Tiles?_ docs iirc). Based on what you're saying, it sounds like the entire tile dataset would need to be resync'd if any one tile changes. That would be prohibitive for mobile devices with how often the OSM data source has updates. Am I understanding correctly?

**Comment by kevinkreiser** [comment]
@chrisfosterelli yes that was one of the ideas behind `why tiles`. the trick is that we havent spent any time on making it possible. specifically we use an indexing schema such that an update to any one region will cause a cascade of changes to connected regions around it. if we did spend time on it, the result, with respect to this discussion, would be that we'd need to mark those updated tiles as well as the ones the updates cascaded into so that the client could get all of them.

as i mentioned we sadly didnt get any time to spend on this issue and so its currently unsupported. hysterical raisins etc... basically the `why tiles` docs were as much us looking into the future as us describing the current approach. i hope this helps!

**Comment by chrisfosterelli** [comment]
@kevinkreiser Thanks for clarifying Kevin!

**Comment by rinigus** [comment]
@chrisfosterelli : For me, the fact that we can split the whole dataset and join it on device is a major reason behind choosing Valhalla. In practice, I am targeting renewal of the datasets once a month and, at that rate, there is a decent chance that large fraction of tiles will have one or two records renewed. Having ability to diff would be great, but not crucial at this stage. Taking into account that the code for splitting tiles into datasets intersecting areas described by polygons is still missing, that is probably with higher priority than updating only parts of tiles. I will look into splitting problem when I get there.

**Comment by chrisfosterelli** [comment]
@rinigus It depends on the use case I suppose... for us devices are often offline (and therefore need the whole tileset) and download is *very* expensive. If you have metrics on how often tiles would actually need to be changed in relation to OSM updates I'd love to take a look!

**Comment by rinigus** [comment]
@chrisfosterelli : indeed, you have a different use case then. I don't have such metrics, unfortunately.

**Comment by rinigus** [comment]
Its not exactly an issue, but for documentation purposes I'll write it up here.

I shipped yesterday my first release of Valhalla on Sailfish OS - its now distributed as an offline solution for navigation on this mobile platform. We would have to still make some small adjustments to make "client programs" to call it, but its rather simple to do.

To distribute the tiles, I wrote a small C++ program that mapped Valhalla's tiles into small packages . Level 0 was distributed as it was, Levels 1 and 2 were collected by 1x1 degree boxes. Such packaging ensured that resulting tar archives were not too big and there were not too many files on the server. 

C++ program that made a small TXT file linking package ID with Valhalla tile ID is available at https://github.com/rinigus/osmscout-server/blob/master/scripts/import/valhalla/tiles2packs/main.cpp . Packs were tar'ed together using https://github.com/rinigus/osmscout-server/blob/master/scripts/import/valhalla_make_packs.py . On device, after downloading, they are unpacked into a dedicated directory.

Finally, for each country or territory, I had POLY file describing it. To determine which of the packages would have to be downloaded for a country, I wrote a small script that gave a list of packages for given poly file (function `country_pack`). See https://github.com/rinigus/osmscout-server/blob/master/scripts/import/valhalla_country_pack.py

If someone is looking for solution on how to distribute the tiles, feel free to reuse. In the present form, its probably not ready for PR and I am not sure whether / how to make it ready for it.

**Comment by kevinkreiser** [comment]
@rinigus this is cool, when we get to doing this in sdk form or as a service we'll be sure to take a look! thanks again and im glad it worked out for you!

**Comment by rinigus** [comment]
Thank you very much for your help and  developing this great router! We'll try to contribute back as we can. One translator has already asked how to translate routing instructions , he will probably contact you  a bit later .

Out of curiosity, is it the first known rollout of Valhalla as offline router on mobile?

**Comment by kevinkreiser** [comment]
No problem we're glad you like it. That sounds great about the translations! Sadly this wouldn't be the first offline mobile application using valhalla but it would definitely be the first one on your target platform!

**Comment by rinigus** [comment]
@kevinkreiser, I'll encourage the translators. And thanks for telling insider info regarding Valhalla @ mobile :) . I wonder which application is it and how did they solve the distribution format problem?

**Comment by kevinkreiser** [comment]
Yeah we've been wanted for some time to officially target common mobile platforms with proper build tooling etc. From time to time we'll hear about someone else getting it going but we dont usually end up doing more than answering questions along the way.

So I'm not really sure but I think that distributing of the data is not an on demand thing in the other applications I've heard of. So the tiles are either bundled with the install or there is a one time download for a very large area. The emphasis is on very infrequent updates, or so I think!

**Comment by rinigus** [comment]
I see, thank you! If I learn something about the distribution (its mainly sets based on Geofabrik POLY files, planet imported into tiles and later distributed) or other feedback with our mobile use, we'll let you know. Thank you again for your support!
