### ISSUE TITLE
debian8/gcc4.9 support

### ISSUE THREAD

**Issue by kinnou02** [valhalla/valhalla#751]
Hello here,

For Navitia most of our production platforms run on debian, so we did compile valhalla on it. A recent [commit](https://github.com/valhalla/valhalla/commit/e79dfec18c36b56f5b3b049bc94cdf2023a8b080#diff-f8ffd5f939ae3ff5f7770e7c5c2bb148R692) broke this build.
As debian isn't one of the platform you are targeting we would like to know how do you want to handle that kind of stuff. The best way for me would be to issue a PR on your repo, but I can also easily patch it during our build, this way it won't affect you.

Currently the only change required is a replacement of `{}` by `std:undorerd_map<>()`.

**Comment by kevinkreiser** [comment]
thats fine yes please PR these compatibility changes. until such a time as we have the ability to run builds against multiple compilers on mulitple distros it will be great if you cant help us stay compatible with your environment. we want to be as compatible with as many different environments as possible.

just for reference, does your platform allow using `std:undorerd_map<>{}` instead of `std:undorerd_map<>()` we tend to favor the former as opposed to the latter.

**Comment by kinnou02** [comment]
Great! `std:unordered_map<>{}` should works
