### ISSUE TITLE
valhalla_build_tiles and mem_map performance

### ISSUE THREAD

**Issue by molind** [valhalla/valhalla#932]
I've noticed that at some points of routing tiles generation `valhalla_build_tiles` loads system by kernel calls, more that user calls. I've checked it using instruments and found two issues. Both is not critical, but once solved - they could cause dramatical speedup in tile generation.

midgard/sequence.h and especially mem_map is highly uneffective. It very costly operation to memory map something and then unmap. Especially unmap, because it contains some crazy logic inside. It results in hours spent on unmap function without any sensible reason. See attached file.
[mem_map.trace.zip](https://github.com/valhalla/valhalla/files/1320157/mem_map.trace.zip)

**Comment by kevinkreiser** [comment]
hey thanks for the investigation. yes we make extensive use of memory maps. the reason we need this is so that users with normal computers (like the core developers of this software) can actually make tile data for a planets worth of data. to keep the amount of data we need in memory wouldnt be possible. note that final product is something like 50gb of tiles for the planet, no commodity computers have this much ram. so we avoid this problem by creating large files and memory mapping them.

now you make a good point though. i havent ever tested this but if we are spending lots of time in unmapping then we can avoid this but only ever unmapping at the end of the whole process. for the sake of code complexity we split the tile making process into multiple parts. each part my map and then unmap large files as it makes use of them. instead of doing this we could just map them once and keep the map alive until the end of the process.

i'm not sure how to view the information you've provided in your attachment. can you let me know how to use it? keep in mind none of the core devs have access to macs os.

**Comment by molind** [comment]
Oh. There is an app called Instruments. It's included inside the XCode. It's most powerful performance profiler I ever seen. Just extract zip file and open it with Instruments (I used last version shipped with Xcode 9 to record stats). As you can see on screenshot 98% of time is spent on munmap() during flush().

![screen shot 2017-09-21 at 1 32 10 pm](https://user-images.githubusercontent.com/102496/30691732-5aa78dc6-9ed1-11e7-85d7-c351fc9cdcb4.png)

**Comment by molind** [comment]
Unfortunately you can't view it not on macOS. :(

**Comment by dnesbitt61** [comment]
@molind - if the PR for memory map in the sequence class doesn't fix your underlying issue feel free to open a new issue. Thanks.
