### ISSUE TITLE
Mismatched scaling factor in Polyline Decoder

### ISSUE THREAD

**Issue by Wilhansen** [valhalla/valhalla#976]
Hi, is the following mismatched scale factor in the Polyline Decoder intentional?
 The scale factor as written here is 1e6: https://github.com/valhalla/valhalla/blob/840bb0006654a420ebbcb5117032c7e2f5ab3e1f/valhalla/midgard/shape_decoder.h#L55-L56

But the official documentation for the Google Polyline encoding states that the scale factor is 1e5 (https://developers.google.com/maps/documentation/utilities/polylinealgorithm). Is this intentional?

**Comment by kevinkreiser** [comment]
We use `1e6` everywhere, it is intentional. We found the extra precision was nice when converting a given polyline multiple times. No where do we ever expect or make use of a scale factor of `1e5`. I also dont believe we ever claimed to follow googles suggestion of 5 digits either. The algorithm is general, meaning any scale could be used. In the future we may encode other values (columns of data) in the string and allow the user to specify which column is which data and what scale to use with that column.
